Added email validation on welcome and preferences screen
desktop/desktop pull request #10214
Opened 2020-07-15 19:14 UTC by Pragya007

Closes #[10209]

## Description

- Added email validation on welcome screen and preferences screen

### Screenshots

[gif1.zip](https://github.com/desktop/desktop/files/4927466/gif1.zip)

## Release notes

Notes:

2020-08-06 14:25 UTC, SecretRose7 commented on app/src/ui/lib/configure-git-user.tsx
> +            type="email"
GoldRoses.GR@gmail.com

2020-08-06 14:28 UTC, SecretRose7 commented on app/src/ui/preferences/git.tsx
> +            type="email"
`GitRoses.GR@gmail.com`

2020-09-05 19:40 UTC, rami0r commented on app/src/ui/lib/configure-git-user.tsx
> +            type="email"
58536626+rami-HP@users.noreply.github.com

2020-09-05 19:40 UTC, rami0r commented on app/src/ui/preferences/git.tsx
> +            type="email"
58536626+rami-HP@users.noreply.github.com

2020-09-05 19:41 UTC, rami-HP reviewed
Duplicate of #

2020-09-18 15:45 UTC, niik requested changes
Hey @Pragya007, thanks so much for working on this!

These changes look great, I had two small requests for changes that I'd like for you to look at but after than I think we should be able to get this merged and into the next release.

2020-09-18 15:45 UTC, niik commented on app/styles/ui/_text-box.scss
> +    border-color: $red-500;
Can we use our CSS variable for errors here, that way individual themes can modify it.

```suggestion
    border-color: var(--error-color);
```

2020-09-18 15:45 UTC, niik commented on app/styles/ui/_text-box.scss
> +  :invalid{
Missing a little space here to conform to our conventions

```suggestion
  :invalid {
```

2020-09-18 17:20 UTC, Pragya007 commented
> Hey @Pragya007, thanks so much for working on this!
> 
> These changes look great, I had two small requests for changes that I'd like for you to look at but after than I think we should be able to get this merged and into the next release.

@niik  Sure, I will make the necessary changes.

2020-09-21 09:40 UTC, niik approved these changes
Thank you so much for working on this @Pragya007! Gonna try to get this into the next production release towards the end of the month

2020-09-21 09:40 UTC, merged