refine checks for when running in a fork on GitHub Actions
desktop/desktop pull request #10434
Opened 2020-08-24 22:04 UTC by shiftkey

:wave: I hope you're all doing well. Congrats on a shiny new release today - can't wait to try it out myself! Also, no rush on this PR - I can workaround it in the meantime, but seeing this project leverage Actions will make maintaining the fork much easier for me. Kudos!

This is an infrastructure fix for an issue I've started to encounter over in `shiftkey/desktop` since https://github.com/desktop/desktop/pull/9680 was merged into `development`. 

### Description

When I pushed `development` to my fork I see that the CI build on macOS tries to setup the keychain, which it doesn't have access to, and errors.

https://github.com/shiftkey/desktop/runs/1022917605#step:8:403

```
Setting up keychain…
...
security: SecKeychainItemImport: Unknown format in import.
security: SecItemCopyMatching: The specified item could not be found in the keychain.

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
...
```

I believe it's related to this new check inside `script/build-platforms.ts`:

https://github.com/desktop/desktop/blob/ac3b9e8b871ca57187bcfe5f6332ceaad546be8b/script/build-platforms.ts#L66-L72

My testing indicates that `GITHUB_HEAD_REF` is not always present, and my current working theory is that it's only available for `pull_request` events. I poked at the default branch in my fork to add some tracing output, triggered a `push` event and got these values for the two important environment variables.

https://github.com/shiftkey/desktop/runs/1023228953?check_suite_focus=true#step:6:396

```
Found environment variables GITHUB_REPOSITORY='shiftkey/desktop' and GITHUB_HEAD_REF=''
```

I added the `GITHUB_REPOSITORY` check as that feels more predictable, and matches how we checked Appveyor and Travis back in the day. I've kept the `GITHUB_HEAD_REF` check around as I believe that's still required, but I'm :+1: to adapting this based on the rules you need. **If we should be marking all `pull_request` events as being "from a fork" that might make this change simpler. Does that make sense from your perspective?**

With this fix in place on my fork, the `pull_request` event detects the correct context and now skips keychain setup:

https://github.com/shiftkey/desktop/pull/326/checks?check_run_id=1023484195#step:8:403

```
Found head ref 'shiftkey/fork-detection-linux' for repository 'shiftkey/desktop' which is considered a fork
```

Merging that PR https://github.com/shiftkey/desktop/pull/326 into the default branch of my fork triggered a `push` event, which checks the other criteria and skips keychain setup:

https://github.com/shiftkey/desktop/runs/1023615478#step:6:396

```
Found push event for repository 'shiftkey/desktop' which is considered a fork
```

This PR should trigger a `pull_request` workflow, and avoid setting up the keychain, as these recent PRs indicate is the desired behaviour:

 - `pull_request` event from fork - https://github.com/desktop/desktop/pull/10410 - [[failing console message]](https://github.com/desktop/desktop/runs/1008518373#step:8:409)
 - `pull_request` event from local branch - https://github.com/desktop/desktop/pull/10407 - [[failing console message]](https://github.com/desktop/desktop/runs/1002520685#step:8:407)

TODO:

 - [ ] address any feedback from reviewers

I'll leave this as a draft PR until I've verified the changes work as expected.

## Release notes

Notes: improved fork detection when running CI on GitHub Actions

2020-08-24 23:26 UTC, shiftkey commented
> **If we should be marking all `pull_request` events as being "from a fork" that might make this change simpler. Does that make sense from your perspective?**

I ended up going down this path and not needing to check the `GITHUB_HEAD_REF` environment variable, which simplified the checks.

2020-08-25 10:24 UTC, niik requested changes
Hey @shiftkey, good to see you in this repository again! We're still learning the ins and outs of actions so chances are we're not using these env vars correctly.

That said I took a look at the offending method `isRunningOnFork` and I see that it's only used two spots

https://github.com/desktop/desktop/blob/45f006ec96fcd0e5a38de4080c96a7722321ce32/script/build.ts#L75-L82

and

https://github.com/desktop/desktop/blob/56dc6a59fafe335bbe445a9ebbf6c5ffee5bfa0b/script/test-setup.ts#L10-L23

The first case is installing the certificates needed for code signing and the second one is verifying that the binaries got signed correctly. I don't see how either step would be necessary unless we're building with the intent of publishing so we should be able to remove the `isRunningOnFork` method entirely and substitute its callsites with `isPublishable`...

https://github.com/desktop/desktop/blob/ea6b809b63e336c84bce6f42276682ea659dac06/script/dist-info.ts#L103-L108

...which we're already using for things like notarization...

https://github.com/desktop/desktop/blob/ea6b809b63e336c84bce6f42276682ea659dac06/script/build.ts#L165

...and obviously publishing...

https://github.com/desktop/desktop/blob/ea6b809b63e336c84bce6f42276682ea659dac06/script/publish.ts#L6-L9

2020-08-25 11:49 UTC, shiftkey commented
👍 on swapping it out for `isPublishable()` - will put this back to draft and take a shot at porting those usages over

2020-08-25 14:17 UTC, niik approved these changes
This looks great to me. Gonna merge it and try it out in #10439 in a bit. Thanks!

2020-08-25 14:17 UTC, merged

2020-10-31 20:32 UTC, LisaSante approved these changes
done