Optional commit spell checking
desktop/desktop pull request #10996
Opened 2020-11-08 18:35 UTC by Hovemeyer5

Spell checking in commit summary & description #1597
Closes #1597

## Description
Added an option "Enable spellcheck on commit summary and description." to advanced section in options. 
-> provide input if preferred to be placed somewhere else.

Option sets local storage key commit-spellcheck-enabled.

If enabled, summary and description of commit use spellchecker. 

Set to false by default as to not unexpectedly modify current app behavior.

Note: This implementation does not include adding words to dictionary from context menu.

### Screenshots

![image](https://user-images.githubusercontent.com/7199430/98481152-387eb000-21c6-11eb-9abf-7f619c27053b.png)

![image](https://user-images.githubusercontent.com/7199430/98481215-ceb2d600-21c6-11eb-92b8-474f7b801bda.png)

## Release notes
Notes: "Enable spellcheck on commit summary and description." add to advanced section. When enabled, summary and description of commit use spellchecker.

2020-11-09 11:11 UTC, niik commented
Hi @Hovemeyer5, thanks so much for opening this and for wanting to contribute!

The changes look very idiomatic and well laid out and I especially appreciate the attention given to documentation :sparkles:

> Note: This implementation does not include adding words to dictionary from context menu.

Please see our discussion in https://github.com/desktop/desktop/pull/10398. While being able to toggle spellchecking is on important piece of us being able to ship spellchecking in Desktop this we also need to get a handle on how to surface suggestions to the user, how to let them ignore common false positives etc. If that's something you'd like to work on we'd be happy to take a look at it!

2020-11-14 22:00 UTC, Hovemeyer5 commented
Added Spell Check Context Menu Options:
1. Can now also enable commit spell check from summary and description context menu.
![image](https://user-images.githubusercontent.com/7199430/99157807-5fdbee00-269a-11eb-9564-9e07539fbc34.png)

2. Can disable commit spell check from summary and description context menu.
![image](https://user-images.githubusercontent.com/7199430/99157833-8dc13280-269a-11eb-81ae-7d566a7dd9e0.png)

3. Receive suggestions
![image](https://user-images.githubusercontent.com/7199430/99157845-af221e80-269a-11eb-9f8d-25b11ab449c3.png)

4. Add to Dictionary
![image](https://user-images.githubusercontent.com/7199430/99157854-bcd7a400-269a-11eb-93ce-745d941cb0b2.png)

5. Also does not impact other custom context menus.
![image](https://user-images.githubusercontent.com/7199430/99157876-e395da80-269a-11eb-843b-05c987df6254.png)
![image](https://user-images.githubusercontent.com/7199430/99157871-d8db4580-269a-11eb-9d37-267fec7fd92d.png)
![image](https://user-images.githubusercontent.com/7199430/99157882-f0b2c980-269a-11eb-9f13-57bbf0d2448e.png)

2020-12-15 22:29 UTC, sarim commented
After clicking add to dictionary can the user see the list of custom words added to dictionary somewhere? Maybe i mistakenly added a wrong word to dictionary and want to revert it.
Also for It'd be nice to have a feature to add regex patterns to ignore spell check.  It'd help in commit messages, let me quote a comment from parent issue

> For example, if I type “Refactor FooGlobber”, I don’t want “FooGlobber” to be marked as misspelled. Nor “refactor”, which is not in all dictionaries. The same with file paths – if I write “changed src/core/index.js”, I don’t want “src” to be marked as misspelled.

With regex it'd be very easy to capture `src/core/index.js` part and ignore it.

2021-01-19 16:31 UTC, niik commented
@sergiou87 No rush but it'd be great if you could review this as both me and @Hovemeyer5 / @tidy-dev have touched it 🙇

2021-01-19 17:45 UTC, sergiou87 approved these changes, later dismissed
It looks great to me, great job!!! 😍

2021-01-19 18:31 UTC, sergiou87 requested changes
Aside from removing some changes we discussed in Slack, I wasn't able to make this work (basically I don't see the red line under misspelled words, and I don't get suggestions either).

I'll take a look tomorrow and see if there is anything wrong in my machine :thinking:

2021-01-19 18:31 UTC, sergiou87 commented on app/src/ui/lib/text-box.tsx
> +          spellCheck={this.props.spellcheck === true}
As discussed in Slack, seems like the changes in this file shouldn't be needed (since `TextBox` is not used in the commit message box).

2021-01-20 09:22 UTC, sergiou87 approved these changes
After some testing, I found out the changes in `TextBox` are actually necessary, otherwise you get spellchecking everywhere in the app 😂 

Sorry about that!! I think this can be merged already 😌  Great job!!! 😍

2021-01-20 09:58 UTC, merged

2021-01-20 10:37 UTC, niik commented
![yesyesyes](https://user-images.githubusercontent.com/634063/105163190-e4704000-5b13-11eb-9b07-fec1f448d6a4.gif)