Fix installation instructions in README.md
desktop/desktop pull request #11279
Opened 2020-12-23 13:00 UTC by kawarimidoll

## Description

Fix error when installing using latest Homebrew in macOS. Just fix README.md.

### Screenshots

![Calling brew cask install is disabled](https://user-images.githubusercontent.com/8146876/102998026-aeb65680-4569-11eb-8919-3ef725ce0419.png)

## Release notes

Notes: no-notes

2020-12-23 13:01 UTC, Sifat1998 approved these changes

2020-12-25 10:32 UTC, leonmendezarrona commented
Sas

2020-12-27 17:06 UTC, leonmendezarrona requested changes
Asesorar cambios

2021-01-04 16:02 UTC, billygriffin approved these changes
Makes sense to me.

2021-01-07 16:33 UTC, niik approved these changes
Thank you so much @kawarimidoll!

2021-01-07 16:33 UTC, merged