Focus co-author input after clicking on "Add co-authors"
desktop/desktop pull request #11621
Opened 2021-02-18 13:10 UTC by sergiou87

## Description

This was something that bothered me, whenever I wanted to add someone as a co-author I not only had to click on the "Add Co-Author" button, but also on the textbox itself. Well, not anymore!

### Screenshots

https://user-images.githubusercontent.com/1083228/108361456-5f765600-71a7-11eb-977c-f36abcdba2ae.mov

## Release notes

Notes: [Improved] Clicking on "Add Co-Author" moves the focus to the co-authors text field

2021-02-19 02:04 UTC, killmen136 approved these changes

2021-02-19 02:36 UTC, killmen136 requested changes
F

2021-02-19 02:36 UTC, killmen136 requested changes
T

2021-02-19 02:42 UTC, killmen136 requested changes
F

2021-02-19 02:42 UTC, killmen136 commented
> ## Description
> 
> 
> 
> This was something that bothered me, whenever I wanted to add someone as a co-author I not only had to click on the "Add Co-Author" button, but also on the textbox itself. Well, not anymore!
> 
> 
> 
> ### Screenshots
> 
> 
> 
> https://user-images.githubusercontent.com/1083228/108361456-5f765600-71a7-11eb-977c-f36abcdba2ae.mov
> 
> 
> 
> ## Release notes
> 
> 
> 
> Notes: [Improved] Clicking on "Add Co-Author" moves the focus to the co-authors text field
> 
>

2021-02-19 05:46 UTC, billygriffin approved these changes
I think this is a wonderful change. Thanks @sergiou87! 🚀

2021-02-22 10:43 UTC, tidy-dev approved these changes
Looks awesome!

2021-02-23 08:24 UTC, merged

2021-02-23 10:17 UTC, ruksina25 commented
😊

2021-02-23 10:17 UTC, ruksina25 reviewed
app/src/ui/changes/commit-message.tsx