Release 2.6.4
desktop/desktop pull request #11674
Opened 2021-03-02 19:46 UTC by tidy-dev

## Description

Looking for the PR for the upcoming v2.6.4 production release? Well you've just found it, congratulations! :tada:

We're targeting a release later this week

## Release checklist

- [ ] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [ ] Verify that all feature flags are flipped appropriately
- [ ] If there are any new metrics, ensure that central and desktop.github.com have been updated

2021-03-02 20:08 UTC, billygriffin requested changes
Thanks for prepping this! A couple minor suggestions but overall this looks great.

2021-03-02 20:08 UTC, billygriffin commented on changelog.json
> +      "[Added] Add branch context menu with rename and delete to branch dropdown list - #5803 #10432",
```suggestion
      "[Added] Allow users to rename and delete branches via a new context menu on branches in the branches list - #5803 #10432",
```

2021-03-02 20:08 UTC, billygriffin commented on changelog.json
> +      "[Fixed] Notepad++ is not closed anymore when GitHub Desktop closes - #11518",
```suggestion
      "[Fixed] Notepad++ does not close when GitHub Desktop closes - #11518",
```

2021-03-02 20:34 UTC, billygriffin approved these changes, later dismissed

2021-03-03 07:26 UTC, sergiou87 commented on changelog.json
> +      "[Improved] Remote Git operations are faster and less prone to errors on Windows - #11510",
This one should be removed because right now is only enabled in beta. Or do you want me to enable it on prod for this release @billygriffin?

2021-03-03 14:30 UTC, sergiou87 commented on changelog.json
> +      "[Improved] Remote Git operations are faster and less prone to errors on Windows - #11510",
We decided to enable the new trampoline for this release 🎉

2021-03-03 16:18 UTC, sergiou87 approved these changes
Already shipped! :shipit:

2021-03-03 16:19 UTC, merged