Handle the Fact that themeSource isn't sticky
desktop/desktop pull request #11826
Opened 2021-03-18 23:06 UTC by say25

## Description

- @sergiou87 pointed to me that ThemeSource is actually not persisted to disk in any way https://github.com/electron/electron/blob/14acf00ba9ecdd8103828659b8a4f9d405fd81ec/patches/chromium/feat_add_set_theme_source_to_allow_apps_to.patch#L42-L50. This fixes theme to now persist to disk again

## Release notes

Notes: No Notes

2021-03-19 12:14 UTC, tidy-dev requested changes
@say25 Thanks for looking at this! I was testing it out and am running into some odd behavior. 

I spun up my Desktop-dev. I was in dark mode, which is my system theme setting.. but I have been setting it to light for cherry picking testing. (But due bug this pr is fixing, it doesn't remember that and goes back to Dark on each reload)

I then go to appearance. I expected to be set on system but I was on Dark. I figure this is just because I was last on dark before the update.

I then set my theme to light. It switches to light great! Then I close out Desktop-dev and spin it back up again. I expect it to remember my light mode selection. Sadness... it did not persist my selection. It is Dark again. However... I go to the preferences and light is selected just the light theme is not applied! :) I think this PR is heading the right direction, but needs one more step to apply locally stored theme. 

![image](https://user-images.githubusercontent.com/75402236/111778155-9ca73400-888a-11eb-8a6a-67102ec9e72b.png)

2021-03-22 10:02 UTC, sergiou87 commented
Could that be some kind of race condition? Maybe we need to set the `themeSource` before/after some specific event 🤔

2021-03-23 10:51 UTC, sergiou87 requested changes

2021-03-23 10:51 UTC, sergiou87 commented on app/src/ui/lib/application-theme.ts
> + export function getCurrentlyAppliedTheme(): ApplicableTheme {
Nit (sorry 😆 ): there is a space before `export`
```suggestion
export function getCurrentlyAppliedTheme(): ApplicableTheme {
```

2021-03-23 10:51 UTC, sergiou87 commented on app/src/ui/lib/application-theme.ts
> +}
I'm personally not comfortable having a `get` function that also changes things 😕 

This might be redundant, but I'd rather have in `app-store.ts` line 1471 this:
```
    this.selectedTheme = getPersistedTheme()
    // Make sure the persisted theme is applied
    setPersistedTheme(this.selectedTheme)

    this.currentTheme = getCurrentlyAppliedTheme()
```

Or instead of `setPersistedTheme` add a `applyTheme` function which changes `remote.nativeTheme.themeSource` but doesn't persist it? (if we wanted to decouple persistence from applying the theme).

What do you think?

2021-03-25 03:20 UTC, say25 commented on app/src/ui/lib/application-theme.ts
> +}
I think setPersistedTheme is a little cleaner, going with that

2021-03-25 11:03 UTC, sergiou87 approved these changes
LGTM and seems to work fine now 😌 

Thanks for taking care of this! ❤️ 

:shipit:

2021-03-26 12:24 UTC, tidy-dev approved these changes

2021-03-26 12:24 UTC, merged