Release 2.8.0
desktop/desktop pull request #12081
Opened 2021-04-27 12:12 UTC by tidy-dev

## Description

Looking for the PR for the upcoming v2.8.0 production release? Well you've just found it, congratulations! :tada:

This is based on the development.

## Release checklist

- [ ] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [ ] Verify that all feature flags are flipped appropriately
- [ ] If there are any new metrics, ensure that central and desktop.github.com have been updated

2021-04-27 12:23 UTC, tidy-dev commented
Feature Flags as expected:
```
/** Should the app show hide whitespace in changes tab */
export function enableHideWhitespaceInDiffOption(): boolean {
  return true
}

/** Should we allow expanding text diffs? */
export function enableTextDiffExpansion(): boolean {
  return true
}

/** Should we allow using the save dialog when choosing where to clone a repo */
export function enableSaveDialogOnCloneRepository(): boolean {
  return true
}

/** Should we allow setting repository aliases? */
export function enableRepositoryAliases(): boolean {
  return true
}
```

All other feature flags are either false or beta, except trampoline which is true from last prod release.

2021-04-27 12:24 UTC, tidy-dev commented
New 'architecture' metric to be deployed to central.

2021-04-27 15:04 UTC, billygriffin requested changes
This is looking great! A few suggestions, but all very minor and non-substantive.

2021-04-27 15:04 UTC, billygriffin commented on changelog.json
> +      "[New] Expand diffs to get more context about your changes - #7014",
```suggestion
      "[New] Expand diffs to view more context around your changes - #7014",
```

2021-04-27 15:04 UTC, billygriffin commented on changelog.json
> +      "[Fixed] On hover, show the full branch name in tooltip - #12008",
```suggestion
      "[Fixed] Display the full branch name in a tooltip when hovering over a branch in the branches list - #12008",
```

2021-04-27 15:04 UTC, billygriffin commented on changelog.json
> +      "[Improved] During cloning progress and on hover, show full progress description - #11375. Thanks @maifeeulasad!",
```suggestion
      "[Improved] Display full progress description when cloning a repository - #11375. Thanks @maifeeulasad!",
```

2021-04-27 15:04 UTC, billygriffin commented on changelog.json
> +      "[Improved] Cherry-pick multiple non sequential commits - #12030",
```suggestion
      "[Improved] Cherry-pick multiple non-sequential commits - #12030",
```

2021-04-27 15:10 UTC, sergiou87 requested changes

2021-04-27 15:10 UTC, sergiou87 commented on changelog.json
> +    "2.7.3": [
Shouldn't this be 2.8.0?
```suggestion
    "2.8.0": [
```

2021-04-27 16:12 UTC, billygriffin approved these changes
🚀

2021-04-28 07:47 UTC, sergiou87 approved these changes
:shipit: 🚀

2021-04-28 08:48 UTC, merged

2023-10-04 03:56 UTC, wahabzaib555 commented
> ## Description
> Looking for the PR for the upcoming v2.8.0 production release? Well you've just found it, congratulations! 🎉
> 
> This is based on the development.
> 
> ## Release checklist
> * [x]  Check to see if there are any errors in Sentry that have only occurred since the last production release
> * [x]  Verify that all feature flags are flipped appropriately
> * [x]  If there are any new metrics, ensure that central and desktop.github.com have been updated