Add copy to clipboard for branch/repository name
desktop/desktop pull request #12178
Opened 2021-05-08 22:04 UTC by tsvetilian-ty

Closes #12141

### Screenshots

![image](https://user-images.githubusercontent.com/9341546/117554752-47092f80-b062-11eb-97cc-462215f44153.png)
![image](https://user-images.githubusercontent.com/9341546/117554767-73bd4700-b062-11eb-84dd-9f70b929dfe2.png)

2021-05-10 17:50 UTC, tidy-dev requested changes
@tsvetilian-ty  Thank you so much for contributing! I particularly would like this feature. 😀 

However, we have some minor changes we would like for app congruency. 

For the branch menu:

```
Rename...
Copy branch name
-----
Delete...
```

For repo menu:
```
Create alias
Copy repo name
----
Open in
Show in
Open in
----
Remove...
```

2021-05-10 18:31 UTC, tsvetilian-ty commented
@tidy-dev the pleasure to contribute to the project is all mine 🙌 
![image](https://user-images.githubusercontent.com/9341546/117707234-fcf58a80-b1d6-11eb-8648-c188ccb6f7b5.png)
![image](https://user-images.githubusercontent.com/9341546/117707247-041c9880-b1d7-11eb-8aa2-46cd1c9af4a1.png)

2021-05-11 11:03 UTC, tidy-dev approved these changes
✨ @tsvetilian-ty Thank you so much for those changes!

2021-05-11 11:03 UTC, merged

2021-06-15 19:45 UTC, clary54 commented on app/src/ui/branches/branch-list-item.tsx
> +      label: __DARWIN__ ? 'Copy Branch Name' : 'Copy branch name',
clary54