Show warning before undoing commit if it conflicts changes in working directory
desktop/desktop pull request #12344
Opened 2021-06-02 12:03 UTC by sergiou87

## Description

Depends on #12341 

Adds an `Undo Commit` in the context menu of the commit list, for individual commits.

### Screenshots

https://user-images.githubusercontent.com/1083228/120476668-230fe400-c3ab-11eb-8e00-f8db8f3124d5.mov

## Release notes

Notes: [Improved] Allow to undo the latest commit from the context menu in the History tab

2021-06-03 12:20 UTC, tidy-dev requested changes
I am on your #12353 amend pr branch, which I realized was based off this one so I went ahead and tested this out there instead of switching to this branch.. But the undo does this weird flicker thing.  I was expecting it to work like Amend and bounce me back to the changes view.. but looking at the code, is that not the intention?  

If it is not supposed to bounce to the changes tab, then I still think we need to resolve the flicker.
https://user-images.githubusercontent.com/75402236/120643568-5488be00-c444-11eb-978e-3aef7a4c76b0.mov

2021-06-03 12:20 UTC, tidy-dev commented on app/src/ui/history/commit-list-item.tsx
> +        label: __DARWIN__ ? 'Undo Commit' : 'Undo commit',
Should `Undo Commit` have the `...`?

2021-06-03 13:50 UTC, sergiou87 commented
@tidy-dev Fixed! It seems the selection was cleared twice: once in the `_undoCommit` method, and then again in the `_refreshRepository` method, causing some weird UI glitches to happen 😄 

https://user-images.githubusercontent.com/1083228/120655847-5c1b8780-c483-11eb-9e86-bdd5138e7eb8.mov

2021-06-03 15:25 UTC, tidy-dev reviewed
Awesome! Thank you for that fix. It still feels strange to me tho that amend takes you to the changes tab and undo doesn't. Wouldn't a user more than likely need to go to the changes tab after undoing to fix what they are undoing?

2021-06-03 15:54 UTC, sergiou87 commented
I don't have a strong opinion in this case, since you can also undo from the changes tab. With Amend, I found it difficult to understand the change in the app state if we just left the user in the History tab.

I could buy the "consistency" argument though 😄  @billygriffin any strong opinion about it?

2021-06-03 16:58 UTC, billygriffin commented
I agree with @tidy-dev that Undo should take you to the Changes tab as well, especially since it populates the changes with the contents. Or at the very least, I'd like to see it and make sure it doesn't feel too unreasonable.

2021-06-03 17:07 UTC, sergiou87 commented
Fixed! Thanks for the feedback! 🙌 ❤️ 

https://user-images.githubusercontent.com/1083228/120684409-efae8180-c49e-11eb-8c3a-3a313baf45d9.mov

2021-06-03 17:19 UTC, tidy-dev commented
It maybe feels a little more jarring than amend since it populates the diff after switching... but I still think it is what I expected. Also I think if we do move to the new screen `Undo Commit` needs to be `Undo Commit...` to indicate you are going somewhere.

2021-06-04 10:39 UTC, sergiou87 commented
Good point @tidy-dev!! Done 😄

2021-06-04 11:24 UTC, tidy-dev approved these changes
✨  Thank you for those changes!

2021-06-04 14:33 UTC, merged