Reset to commit
desktop/desktop pull request #12393
Opened 2021-06-07 16:30 UTC by sergiou87

Closes TBD

## Description

Initial work to reset HEAD to a previous commit, up to the first non-local commit. When you use it, it resets the HEAD of the repo to the commit you selected, keeping all the changes in the working dir and in the commits in between. As a consequence, undoing the last commit is equivalent to resetting to the second to last commit, with the only difference that undoing the commit also keeps the commit summary and description.
You can see how you can reset up to the first non-local commit (which would, effectively, “undo” all local commits at once).

TODO: add warnings when the working directory has changes and when merge commits are involved in the operation.

### Screenshots

https://user-images.githubusercontent.com/1083228/121056266-504efe80-c7be-11eb-9438-6ac9d6f00604.mov

## Release notes

Notes: [New] Reset to a previous commit

2021-06-08 10:28 UTC, tidy-dev requested changes
✨  Code looks good and tried it out. Awesome work!

Should we put this behind a feature flag? 

Amanda suggested putting a separator in to make the dropdown easier to scan.  The top four seem like a logical grouping to me. They are kind of like undos/modifies. 

![image](https://user-images.githubusercontent.com/75402236/121169825-67bfd300-c822-11eb-8745-16105d9fe98e.png)

2021-06-08 10:43 UTC, sergiou87 commented
Sounds good! I still see it a bit excessive, but it's definitely an improvement 😂 

Oh and I'll hide it behind a feature flag, I totally forgot about that since I started with just a PoC 🤦

2021-06-08 11:06 UTC, sergiou87 commented
Done! @tidy-dev

2021-06-08 13:25 UTC, tidy-dev approved these changes
✨  Thanks for those changes! The separator does help.

2021-06-08 13:44 UTC, merged

2024-04-21 10:32 UTC, Dan88271988 commented
> ✨ Cod