Release 2.9.0
desktop/desktop pull request #12450
Opened 2021-06-15 08:14 UTC by sergiou87

## Description

Looking for the PR for the upcoming v2.9.0 production release? Well you've just found it, congratulations! :tada:

This is based on the 2.8.4-beta4 release (tag [release-2.8.4-beta4](https://github.com/desktop/desktop/releases/tag/release-2.8.4-beta4)) and just enables the new features.

I left #12432 out because it wasn't in the latest beta and I didn't want to risk the release with unnecessary changes that I've only tested myself 😅 

## Release checklist

- [x] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [x] Verify that all feature flags are flipped appropriately
- [x] If there are any new metrics, ensure that central and desktop.github.com have been updated

2021-06-15 15:28 UTC, billygriffin requested changes
Thanks for getting this set up! A few suggestions, not wedded to any of them so if you don't like them just let me know!

2021-06-15 15:28 UTC, billygriffin commented on changelog.json
> +      "[New] Reorder commits with drag and drop in the history tab - #2507",
```suggestion
      "[New] Reorder commits with drag and drop in your commit history - #2507",
```

2021-06-15 15:28 UTC, billygriffin commented on changelog.json
> +      "[New] Squash commits in the history tab - #2507",
```suggestion
      "[New] Squash commits in the history tab with drag and drop and a context menu - #2507",
      "[New] Squash and merge option available when merging branches - #2507",
```

2021-06-15 15:28 UTC, billygriffin commented on changelog.json
> +      "[Fixed] Show warning before undoing commit if it potentially conflicts with changes in working directory - #4596 #9286 #5874 #6043",
```suggestion
      "[Improved] Show warning before undoing commit if it potentially conflicts with changes in working directory - #4596 #9286 #5874 #6043",
```

2021-06-15 15:55 UTC, billygriffin submitted a review, later dismissed
Awwww yeah! 
![backflip](https://user-images.githubusercontent.com/5091167/122085261-c6a3c000-cdbf-11eb-8f5d-f4beb65c0a3a.gif)

2021-06-16 10:23 UTC, tidy-dev approved these changes
✨

2021-06-16 10:36 UTC, merged