Fix: Missing right border in FilterList and in BranchesContainer tab bar
desktop/desktop pull request #12479
Opened 2021-06-18 10:23 UTC by meJevin

Right border was missing in FilterList and BranchesContainer.
Closes #12478

I'm looking at other parts of the UI and this little issue is driving my OCD crazy so I decided to fix it

## Description

Modified a little bit of CSS to fix the underlying issue.

### Screenshots

Example of UI with border:
![1](https://user-images.githubusercontent.com/16974717/122546754-f3620c80-d037-11eb-84f8-efc7ab38d0d0.png)

Examples of UI with missing border:
![2](https://user-images.githubusercontent.com/16974717/122546820-0379ec00-d038-11eb-97ba-426f344f2c29.png)
![3](https://user-images.githubusercontent.com/16974717/122546825-04128280-d038-11eb-9bab-6612072216d5.png)

2021-06-18 10:27 UTC, meJevin commented
Attaching screenshots of UI with fixed right border issue:
![fixed_1](https://user-images.githubusercontent.com/16974717/122547565-f01b5080-d038-11eb-87af-fecf42111cd4.png)
![fixed_2](https://user-images.githubusercontent.com/16974717/122547566-f0b3e700-d038-11eb-8eca-d11fcfd5e2d1.png)

2021-06-18 10:44 UTC, meJevin commented
Dang, I just noticed that I didn't create a separate branch for this PR. Tell me if that OK or not I'll fix it right up and open up a new PR.

2021-06-18 10:50 UTC, sergiou87 requested changes
OMG I didn't notice this and now I can't unsee it 😱 

I think these changes don't actually fix the underlying issue. I just checked and it works fine with the light theme:

![image](https://user-images.githubusercontent.com/1083228/122549604-f6a6c980-d032-11eb-827a-f6a9a393312c.png)

If you zoom in, there are some subtle differences that make the effect that triggered your OCD:
![image](https://user-images.githubusercontent.com/1083228/122549843-38d00b00-d033-11eb-9c5d-1edd4790353c.png) ![image](https://user-images.githubusercontent.com/1083228/122549875-42f20980-d033-11eb-8370-d5f7755ac1e2.png)

In the light theme, the right border of the button in the top bar disappears, so I think we should probably make sure the same happens in the dark theme.

Other than that, your changes feel too specific to the repository and branch lists, while this should require a more generic fix either in the `.foldout` or `toolbar-button` classes 🤔

2021-06-18 11:40 UTC, sergiou87 commented
> Dang, I just noticed that I didn't create a separate branch for this PR. Tell me if that's OK or not I'll fix it right up and open up a new PR if needed

Don't worry about that! As long as it's in another repo is ok for us 😄

2021-06-18 11:50 UTC, meJevin commented
> Other than that, your changes feel too specific to the repository and branch lists, while this should require a more generic fix either in the `.foldout` or `toolbar-button` classes 🤔

Sure, I'll take a look.

2021-06-18 12:11 UTC, meJevin commented
> In the light theme, the right border of the button in the top bar disappears, so I think we should probably make sure the same happens in the dark theme.

In light theme the border is actually still there, but you can't see it.. If you inspect it in dev tools you will be able to see it. I took a crack at it and `border-right` is actually in the `.toolbar-button`. I'm not really sure how to disable that CSS property for specifically `Current repository` button when the foldout is being shown.

Also, setting border of `.foldout`. Here's what's happening when I set `border-right` on `.foldout` 
![image](https://user-images.githubusercontent.com/16974717/122558672-07f9d100-d047-11eb-9aac-60d8ae9a2902.png)

For some reason not the entire foldout is covered with the right border. Only the upper part is covered with the border..

2021-06-18 12:14 UTC, meJevin commented
@sergiou87 or are you saying that we should ditch the borders and just disable the right border for `Current repository` button when it's open?

2021-06-18 12:26 UTC, meJevin commented
In the case of latter I guess setting `border-right: none` in `ui/toolbar/_dropdown.scss` could work. There's a CSS selector for when it's open and it's a toolbar button.

2021-06-18 12:48 UTC, sergiou87 commented
@meJevin yes and no 😂 

Basically what I had this in mind: 
1. Understand why the button appearance is different on Dark and Light themes.
2. Remove whatever the difference is.

I just took a quick look at the CSS and found why they're different:
- Dark theme: uses the regular border color when it's active https://github.com/desktop/desktop/blob/9630999f5e32f9aef4c3a0ae54ba88153aa6b588/app/styles/themes/_dark.scss#L168
- Default (Light theme): uses the background color when it's active https://github.com/desktop/desktop/blob/9630999f5e32f9aef4c3a0ae54ba88153aa6b588/app/styles/_variables.scss#L229

Since the Light theme is the original one, I assumed (maybe incorrectly) that's the correct behavior, but looking at your screenshots of the Dark theme without the border, it also looks kind of wrong since there is much less contrast with the other button than in the Light theme. Maybe @ampinsk can chime in and tell us what she thinks the right approach is!

2021-06-18 12:51 UTC, meJevin commented
@sergiou87 sure, let's wait for @ampinsk and we'll move on from there.

2021-06-18 20:02 UTC, ampinsk commented
Hey, thanks for this thorough investigation y'all! I do think the fix is what @sergiou87 found: there's a misalignment between the dark and light themes on that variable. The "foldouts" aren't intended to have borders, since they sit "on top" of the interface. I think they end up looking like they have borders on one side because they sit on top of elements that do have a border. But that line being jagged like that is definitely annoying, I like your approach @sergiou87 to align that button border across the themes!

2021-06-19 07:25 UTC, meJevin commented
> I like your approach @sergiou87 to align that button border across the themes

So we're choosing this variation then? https://github.com/desktop/desktop/pull/12479#issuecomment-864001693

2021-06-19 07:36 UTC, meJevin commented
I've committed the changes so you can see the result.

2021-06-19 07:49 UTC, meJevin commented
How it looks on Mac:
![image](https://user-images.githubusercontent.com/16974717/122635331-ee5e9500-d0eb-11eb-9776-fcdffc393076.png)
![image](https://user-images.githubusercontent.com/16974717/122635341-f6b6d000-d0eb-11eb-80a9-a6abd77be149.png)

2021-06-21 08:43 UTC, sergiou87 approved these changes
This is great! Thank you @meJevin for your contribution!!! ❤️ 

Can't wait to have this in a build so I can effectively unsee the bug 😂 😂

2021-06-21 09:05 UTC, merged

2021-06-26 14:39 UTC, get-bent-gaming commented on app/styles/themes/_dark.scss
> -  --toolbar-button-active-border-color: var(--box-border-color);
--toolbar-button-active-border-color: var(--background-color);