Check invalidated tokens and suggest to sign in again
desktop/desktop pull request #12554
Opened 2021-07-02 11:37 UTC by sergiou87

## Description

With the changes in this PR, the app will now check for 401 errors coming from API requests. If those happen, the app will immediately sign out the user and warn them about this, while suggesting them to sign in again.

If they decided to sign in again, they'll be led directly to the sign in flow of the specific account whose token was invalidated (i.e. if the dotcom account was invalidated, they'll sign in that account directly, if the GHE account was invalidated, the account's endpoint will be used to sign in again in that GHE account).

### Screenshots

https://user-images.githubusercontent.com/1083228/124268896-74da9400-db3a-11eb-92eb-42b853ef1ef2.mov

## Release notes

Notes: [Improved] Detect when tokens are invalidated and suggest users to sign in again

2021-07-22 22:38 UTC, billygriffin commented
As discussed in our sync, this is a great improvement but we need to mitigate the problem where this dialog would replace the dialog that you're already in and therefore lose your state prior to merging this.

2021-07-22 22:41 UTC, UpUpnAwaaaay commented
Ok I just got back on and was reading your emails. I trust you on what needs dine. You are the pro. Lol. Thanks you so much for helping and replying

⁣Get TypeApp for Android ​

On Jul 22, 2021, 6:38 PM, at 6:38 PM, Billy Griffin ***@***.***> wrote:
>As discussed in our sync, this is a great improvement but we need to
>mitigate the problem where this dialog would replace the dialog that
>you're already in and therefore lose your state prior to merging this.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/desktop/desktop/pull/12554#issuecomment-885280479

2021-07-22 22:43 UTC, UpUpnAwaaaay approved these changes, later dismissed
Thank goodness for you and your services are very helpful

2021-07-26 08:32 UTC, sergiou87 commented
@billygriffin no worries! That was already addressed in https://github.com/desktop/desktop/pull/12554/commits/c4eb1a6f3f4d3e764a9b65259317043d42394600 😄

2021-07-26 10:07 UTC, tidy-dev commented on app/src/ui/invalidated-token/invalidated-token.tsx
> + * directory where they are gonna be resetting to a previous commit.
Think this maybe some copy/pasta comments that should be updated. :)

2021-07-26 10:25 UTC, tidy-dev requested changes
Looks and works great. Only nit is updating the copied comments on the new component. :)

2021-07-26 10:38 UTC, tidy-dev approved these changes
✨  Thanks for the update!

2021-07-26 11:00 UTC, merged