Workaround for Electron issue with setImmediate
desktop/desktop pull request #12765
Opened 2021-08-12 14:18 UTC by sergiou87

## Description

This PR includes a workaround for https://github.com/electron/electron/issues/29261 that basically replaces calls to `setImmediate` with `setTimeout(…, 0)`.

Given it will need some time in testing, I created a very original abstraction with `setAlmostImmediate` and wrote an eslint rule to make sure we don't use `setImmediate` (@shiftkey I'd love if you could take a look at it and share any feedback… but only if you have time!!!)

After testing it, I haven't noticed any issues, and of course I wasn't able to repro the aforementioned issue after bumping Electron to one of the affected versions, so we could say this temporary workaround is actually useful 😌 

## Release notes

Notes: no-notes

2021-08-12 19:04 UTC, tidy-dev requested changes
✨  Seems like a reasonable work around. I like the name. 😸  

One comment need updated from copy/paste of previous lint rule.

2021-08-12 19:04 UTC, tidy-dev commented on eslint-rules/set-almost-immediate.js
> +     * Check each member of the interface body and ensure it is marked `readonly`.
Copy/Pasta comment

2021-08-12 19:04 UTC, tidy-dev commented on eslint-rules/set-almost-immediate.js
> + * set-almost-immediate
These custom rules are neat!

2021-08-13 00:49 UTC, shiftkey commented
@sergiou87 ESLint rules look fine to me :shipit:

2021-08-16 07:10 UTC, sergiou87 commented on eslint-rules/set-almost-immediate.js
> +     * Check each member of the interface body and ensure it is marked `readonly`.
Ouch! Fixed now, thanks 😄

2021-08-17 13:46 UTC, tidy-dev approved these changes
✨

2021-08-17 14:00 UTC, merged