Enhancing tag creation with autocompletion
desktop/desktop pull request #12777
Opened 2021-08-16 13:46 UTC by matrixnl

This PR Fixes #12509 

## Description

This shows the last 3 tags within the **Create Tag** component. 
It also filters the shown tags as the user type the tag name. (as suggested by @sergiou87)

### Screenshots

![screen shot](https://user-images.githubusercontent.com/32475101/129573665-dcb21b0f-ae0a-4a34-8149-b9a048ef3f93.gif)

## Release notes

Notes: no-notes

2021-08-16 15:26 UTC, sergiou87 commented
Thank you @matrixnl!! We love it 😍 

The only thing that feels jarring is when there are no matches and the whole `Previous Tags` section just disappears. We think it might be nice to keep the `Previous Tags` section with something like `No matches found for '7'` or something similar.

(Aside from that, I still have to review the code itself, I'll give it a first pass tomorrow 😄 )

2021-08-17 14:35 UTC, sergiou87 requested changes
Looks good overall! Only a few suggestions 😄

2021-08-17 14:35 UTC, sergiou87 commented on app/src/ui/create-tag/create-tag-dialog.tsx
> +          {this.state.previousTags && (
Nit, we try to avoid falsy/truthy checks
```suggestion
          {this.state.previousTags !== null && (
```

2021-08-17 14:35 UTC, sergiou87 commented on app/src/ui/create-tag/create-tag-dialog.tsx
> +
We prefer checks + early returns, and also I think you can create an array from `localTags.keys()` just using `Array.from`

```suggestion
  private getExistingTagsFiltered(filter: string = ''): Array<string> | null {
    if (this.props.localTags === null) {
      return null
    }
    const previousTags = Array.from(this.props.localTags.keys())
    return previousTags.filter(item => item.includes(filter))
  }

```

2021-08-18 02:26 UTC, matrixnl commented
Thanks @sergiou87, added **No matches found** and updated according to the suggestions 🙂

2021-08-18 13:41 UTC, sergiou87 approved these changes
I love it, thank you!!! ❤️

2021-08-24 10:16 UTC, sergiou87 requested changes

2021-08-24 10:16 UTC, sergiou87 commented on app/src/ui/create-tag/create-tag-dialog.tsx
> +                  <Ref>{`No matches found for '${this.state.tagName}'`}</Ref>
Just noticed in your screenshot (thanks for sharing that) something I overlooked while reviewing it.

I think for this specific scenario, we don't want to use a `Ref`, just normal text 😅 

Sorry about that!

2021-09-10 06:35 UTC, Lulu-Lucinka approved these changes

2021-09-16 13:11 UTC, mahezsh commented
Created a new PR for this issue at #12966. Have cherry-picked the first 2 comments and addressed @sergiou87's comment.

2021-09-17 06:58 UTC, sergiou87 commented
Thanks, @mahezsh! I don't really understand why creating a new PR, but it's ok 😄  I guess we can close this one.

2021-09-17 06:58 UTC, closed without merging