Release 2.9.3-beta1
desktop/desktop pull request #12840
Opened 2021-08-25 16:25 UTC by tidy-dev

## Description

Looking for the PR for the upcoming first beta of the v2.9.3 series? Well you've just found it, congratulations!

## Release checklist

- [x] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [x] Verify that all feature flags are flipped appropriately
---- No new flags.
- [x] If there are any new metrics, ensure that central and desktop.github.com have been updated
---- No new metrics

2021-08-25 17:18 UTC, billygriffin requested changes
One super minor thing then I'll approve.

2021-08-25 17:18 UTC, billygriffin commented on changelog.json
> +      "[Added] Adds syntax highlighting for dart - #12827. Thanks @say25!",
```suggestion
      "[Added] Add syntax highlighting for dart - #12827. Thanks @say25!",
```

2021-08-25 17:19 UTC, billygriffin approved these changes

2021-08-25 18:14 UTC, merged

2021-08-28 08:24 UTC, bossman84 reviewed
Good

2021-08-29 00:54 UTC, jungjuheeer commented
app/package.json