Check Run Logs
desktop/desktop pull request #13028
Opened 2021-09-27 14:23 UTC by tidy-dev

## Description

WIP of showing check run logs in GitHub Desktop. Currently for Actions, we only show the logs of a failed check run step as we are optimizing for actionable info a user needs to determine if they want to rerun the jobs or fix something. 

### Screenshots

https://user-images.githubusercontent.com/75402236/134927073-12ea13d1-b5fc-450a-a32d-f31edcadfc3d.mov

## Release notes

Notes: [Added] View actionable portion of check run logs.

2021-09-30 11:24 UTC, sergiou87 requested changes
Looks good overall! I mainly found a few nits, and also a couple of things that look suspicious but I might be missing something.

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/api.ts
> +  readonly workflow_runs: IAPIWorkflowRun[]
Any reason for not using `ReadonlyArray`?
```suggestion
  readonly workflow_runs: ReadonlyArray<IAPIWorkflowRun>
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/api.ts
> +  readonly jobs: IAPIWorkflowJob[]
Any reason for not using `ReadonlyArray`?
```suggestion
  readonly jobs: ReadonlyArray<IAPIWorkflowJob>
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/api.ts
> +        `Failed fetching workflow runs for  ${branchName} (${owner}/${name})`
Nit affecting my OCD 😆 
```suggestion
        `Failed fetching workflow runs for ${branchName} (${owner}/${name})`
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/api.ts
> +      // because a log file doesn't makes sense for the workflow. Thus, we just
Nit: typo
```suggestion
      // because a log file doesn't make sense for the workflow. Thus, we just
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +  public async getLatestPRWorkflowRunsLogsForCheckrun(
Nit: typo
```suggestion
  public async getLatestPRWorkflowRunsLogsForCheckRun(
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +      const cr = checkRuns[i]
Why not just a "for each"? I don't see `i` being used 🤔 
```suggestion
    for (const cr of checkRuns.length) {
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +        logHash.get(matchingWR.name) ??
Is `name` safe enough to use here as a unique identifier? I've seen workflow runs have an `id` field so maybe it's better to use that? 🤔 

Or even better, why not use `logs_url` directly? It should always be the same, right?

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +      const workFlowRunJobs = await api.fetchWorkflowRunJobs(matchingWR)
Should we cache this per check suite id? At least in this function call, as you do with `logHash`.

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +    allBranchWorkflowRuns.workflow_runs.forEach(wr => {
Given you don't need the index of each element, is there a reason for not using `for( … of …)` here again? In theory [it should perform better than `forEach`](https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/#arrayforeach-vs-for-and-forof) and it is, IMHO, more readable.

Also if you make this change, beware of the `return` you have a few lines below that must be changed to `continue` if I'm not wrong.
```suggestion
    for (const wr of allBranchWorkflowRuns.workflow_runs) {
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +        return
If you 👍  my suggestion above, this needs to be changed to `continue`
```suggestion
        continue
```

EDIT: I just noticed I wrote `break` here instead of `continue` as I did in my previous message 🤦

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +      const storedWR = wrMap.get(wr.name)
Same question as in the method above: is `name` the best field to cache by? Better than `id`?

2021-09-30 11:24 UTC, sergiou87 commented on app/src/lib/stores/commit-status-store.ts
> +      const step = job.steps[j]
```suggestion
    for (const step of job.steps) {
```

2021-09-30 11:24 UTC, sergiou87 commented on app/src/ui/branches/ci-check-run-list.tsx
> +      this.props.repository !== prevProps.repository ||
Shouldn't we check the hash here? 🤔 
```suggestion
      this.props.repository.hash !== prevProps.repository.hash ||
```

2021-10-01 13:55 UTC, tidy-dev commented on app/src/lib/api.ts
> +  readonly jobs: IAPIWorkflowJob[]
Original solution I added jobs to existing object - but refactor to not do that. Thanks!

2021-10-01 14:00 UTC, tidy-dev commented on app/src/ui/branches/ci-check-run-list.tsx
> +      this.props.repository !== prevProps.repository ||
Hmm. Yes. I copied that from the badge output component.. Likely should be the hash there as well.

2021-10-01 18:09 UTC, tidy-dev commented on app/src/lib/stores/commit-status-store.ts
> +      const storedWR = wrMap.get(wr.name)
Done. Good point. Thanks!

2021-10-01 19:42 UTC, GetBentGaming commented on app/src/lib/stores/commit-status-store.ts
> +        logHash.get(matchingWR.name) ??
Ok

2021-10-01 19:43 UTC, GetBentGaming commented on app/src/ui/branches/ci-check-run-list.tsx
> +      this.props.repository !== prevProps.repository ||
I'm really not sure

2021-10-04 11:31 UTC, sergiou87 approved these changes
Thanks for those changes! 🙌  ❤️ 

I tested it and all worked as expected 😄 :shipit:

2021-10-04 11:45 UTC, MadMena approved these changes

2021-10-04 14:04 UTC, merged

2021-10-13 15:10 UTC, GetBentGaming commented
Im New to Github But Smart, Somewhat, Any help i greatly appreciate