Release 2.9.4-beta4
desktop/desktop pull request #13059
Opened 2021-10-04 15:35 UTC by sergiou87

## Description

Looking for the PR for the upcoming fourth beta of the v2.9.4 series? Well, you've just found it, congratulations!

## Release checklist

- [x] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [x] Verify that all feature flags are flipped appropriately
--- `setAlmostImmediate` is still disabled, the new CI check runs are only enabled for dev and the tag creation improvements enabled for beta. All looking as expected!
![image](https://user-images.githubusercontent.com/1083228/135880479-3e55ddc4-1ea9-44fc-b366-f3b2fd114171.png)

- [x] If there are any new metrics, ensure that central and desktop.github.com have been updated
--- No new metrics

2021-10-04 17:39 UTC, tidy-dev requested changes

2021-10-04 17:39 UTC, tidy-dev commented on changelog.json
> +      "[Fixed] Add syntax mapping for HAML - #13009. Thanks @alexanderadam!",
```suggestion
      "[Added] Add syntax mapping for HAML - #13009. Thanks @alexanderadam!",
```

2021-10-04 17:39 UTC, tidy-dev commented on changelog.json
> +      "[Fixed] Diff are scrolled to the top when switching between files - #12980",
```suggestion
      "[Fixed] Diffs are scrolled to the top when switching between files - #12980",
```

2021-10-04 19:49 UTC, billygriffin reviewed
A couple minor changes but otherwise looks good!

2021-10-04 19:49 UTC, billygriffin commented on changelog.json
> +      "[Fixed] Syntax highlighting is once again applied when viewing a small change for the first time - #13004",
```suggestion
      "[Fixed] Apply syntax highlighting when viewing a small change for the first time - #13004",
```

2021-10-04 19:49 UTC, billygriffin commented on changelog.json
> +      "[Improved] Added offending file name to the file exceeds size limit error - #10242. Thanks @ADustyOldMuffin!",
```suggestion
      "[Improved] Add offending file name to the file exceeds size limit error - #10242. Thanks @ADustyOldMuffin!",
```

2021-10-05 10:35 UTC, tidy-dev approved these changes
✨

2021-10-05 10:43 UTC, merged

2021-10-05 11:53 UTC, wmgl5593 commented
https://github.com/desktop/desktop/pull/13059#issue-1015332503

2021-10-05 16:54 UTC, likeremix715 commented
- [ ] Likeremix715