Add checks summary header
desktop/desktop pull request #13088
Opened 2021-10-07 19:33 UTC by tidy-dev

## Description

Adds a header to the check runs so the rerun button has a home. Additionally provides an overall summary/meta data.

### Screenshots

![image](https://user-images.githubusercontent.com/75402236/136450529-edfe2bb4-0309-4099-95e5-62c46594eb68.png)

There are multiple conclusion types. Technically, the summary could get very lengthy.. tho probably very unlikely.:
```
if (conclusion === null) {
    return 'In progress'
  }

  switch (conclusion) {
    case APICheckConclusion.ActionRequired:
      return 'Action required'
    case APICheckConclusion.Canceled:
      return 'Canceled'
    case APICheckConclusion.TimedOut:
      return 'Timed out'
    case APICheckConclusion.Failure:
      return 'Failed'
    case APICheckConclusion.Neutral:
      return 'Neutral'
    case APICheckConclusion.Success:
      return 'Successful'
    case APICheckConclusion.Skipped:
      return 'Skipped'
    case APICheckConclusion.Stale:
      return 'Marked as stale'
  }
  ```
Here is what it would look like if there were multiple of conclusion types:
![image](https://user-images.githubusercontent.com/75402236/136450342-6e5274da-e280-4982-b256-e24251216885.png)

UPDATE:
![image](https://user-images.githubusercontent.com/75402236/136571412-b3a50f19-01f8-4e2d-ac60-ab5f1e26dfa6.png)

## Release notes
Notes: no-notes

2021-10-07 19:34 UTC, tidy-dev commented
@sergiou87 I also fixed the inside square contents popping out of the popover at the corners in this PR. Thanks for pointing that out. 🙂

2021-10-08 11:08 UTC, sergiou87 reviewed
Thanks for that fix 😄 

The code looks good to me overall, what feels a bit off is the location of the re-run jobs button, especially with a long summary:

![image](https://user-images.githubusercontent.com/75402236/136450342-6e5274da-e280-4982-b256-e24251216885.png)

It's like the margins of the button are uneven (top vs right), and the long summary is too close to the button.

I wonder if it makes sense to move the button down a bit (to make margin.top = margin.right) and then wrap the summary when it reaches the button. Not perfect but maybe better / less jarring?

I don't have a strong opinion about what to do, nor whether or not it should be done in this PR, but it definitely feels weird to me 😆

2021-10-08 13:59 UTC, tidy-dev commented
Yeah. I think it looked funny too.. but wasn't sure about clipping it at the button due to that could cause pushing the summary to three lines quicker.. but again likely edge cases. I will give that a shot and see what it looks like.

2021-10-08 14:58 UTC, sergiou87 requested changes

2021-10-08 14:58 UTC, sergiou87 commented on app/src/ui/branches/ci-check-run-list.tsx
> +    return `${summaryArray[0]} check`
I just noticed that this should be plural the first and only `count` is > 0, otherwise…
![image](https://user-images.githubusercontent.com/1083228/136579092-8d09a264-1ad9-47fc-a3ac-f34b1ca09e66.png)

2021-10-08 16:41 UTC, tidy-dev commented on app/src/ui/branches/ci-check-run-list.tsx
> +    return `${summaryArray[0]} check`
Good catch. Thanks!

2021-10-08 20:38 UTC, darck-storm commented
hello

2021-10-08 20:38 UTC, darck-storm commented
hello

2021-10-12 07:27 UTC, sergiou87 approved these changes
Looks good! Thanks for that change 😄 

:shipit:

2021-10-12 14:08 UTC, merged