Better performance for non actions output
desktop/desktop pull request #13096
Opened 2021-10-08 18:17 UTC by tidy-dev

## Description
Approach from #13064 was undesirable from a code maintenance/concept coupling stand point.

In this PR, I still wait until the user clicks the PR badge. However, instead of waiting for the actions workflow call, jobs call, and logs call/parsing to complete. I split it into two waitings. We have a boolean that is for loading only the actions workflow call where we can determine whether a check run has actions jobs/logs associated with it. Then, we have the original boolean for when the jobs/logs api call and parsing is complete.

The actions workflow call is very lightweight in comparison to the logs retrieval/parsing. Thus, even tho this approach is not as fast #13064 in terms of performance for non-actions, I only saw the loading image for a couple of seconds for non actions check runs when my network setting was for slow 3g ... when compared 20-30s for the action logs. On my regular settings, I was hard-pressed to ever see the loading image for them. Thus, I think this is just as useable a solution.

Side note: We hope to subscribe a websocket for action logs which would likely mean they would become individualized as opposed to currently waiting on all the logs for all the check runs - thus much faster.

### Screenshots

https://user-images.githubusercontent.com/75402236/136603603-e84b6329-6fed-4a88-8ffd-42d1c1089efb.mov

## Release notes
Notes: no-notes

2021-10-12 11:31 UTC, niik requested changes
I like this approach much better @tidy-dev :sparkles:

While I was testing out #13106 I disabled the cache and happened to see that we're making multiple consecutive requests to the same jobs endpoint (for the same id). This is certainly not a huge problem when caching is enabled but it is typically indicative of potential areas of improvement as even if the resource is cached there's still parsing overhead and likely logical overhead on our end as well.

I haven't dug into why it's happening so it's absolutely possible that the complexity of maintaining our own high-level cache isn't worth it but since I saw mentions of a logCache in there already I figured I should at least raise the issue and understand it a little bit better.

2021-10-12 11:31 UTC, niik commented on app/src/lib/api.ts
> +    jobs_url: string
I realize this isn't a new change in this PR but I would like to see if there's a way for us to pass a repo name, owner, and id here instead of an opaque url? The request-method was intended to take a relative url and construct the absolute url and I'd rather we have more control over which urls we make requests for. There are exceptions to this in the current code base though, see [fetchAll](https://github.com/desktop/desktop/blob/7f164be1198622441996218cbb39f226c4dcbb86/app/src/lib/api.ts#L1174-L1198) as an example.

Unless the jobs_url is impossible/hard for us to construct?

2021-10-12 11:31 UTC, niik commented on app/src/ui/branches/ci-check-list-item.tsx
> +  private hasActionsWorkflowLogs = (): boolean => {
It doesn't appear as if we're calling this from an unbound context anywhere so we can probably just make it a regular class field

```suggestion
  private hasActionsWorkflowLogs() {
```

2021-10-12 11:31 UTC, niik commented on app/src/ui/branches/ci-check-run-list.tsx
> +    this.setState({
Given that these methods can end up taking a bit of time it's pretty easy to get into a scenario where we call setState after unmount

![image](https://user-images.githubusercontent.com/634063/136947533-dd9b45ec-2c4c-49a7-b4d1-dca15a3d4f68.png)

Could we either add a flag that we toggle on unmount (i.e. the [good ol' so-called anti-pattern](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html#:~:text=An%20easy%20migration%20strategy%20for%20anyone%20upgrading%20their%20code%20to%20avoid%20isMounted()%20is%20to%20track%20the%20mounted%20status%20yourself.%20Just%20set%20a%20_isMounted%20property%20to%20true%20in%20componentDidMount%20and%20set%20it%20to%20false%20in%20componentWillUnmount%2C%20and%20use%20this%20variable%20to%20check%20your%20component%E2%80%99s%20status.)) or could we use `this.subscription` as a proxy for that?

```suggestion
  if (this.subscription === null) {
    return
  }

  this.setState({
```

If nothing else it'll prevent us from calling `getActionsWorkflowRunLogs` unnecessarily

2021-10-12 11:31 UTC, niik commented on app/src/ui/branches/ci-check-run-list.tsx
> +    this.setState({ checkRuns, loadingActionLogs: false })
Same question here about calling setState after unmount

2021-10-15 11:49 UTC, niik commented
> While I was testing out #13106 I disabled the cache and happened to see that we're making multiple consecutive requests to the same jobs endpoint (for the same id). This is certainly not a huge problem when caching is enabled but it is typically indicative of potential areas of improvement as even if the resource is cached there's still parsing overhead and likely logical overhead on our end as well.

Just realized I forgot to include any more information on this. My bad, I had recorded a small GIF to illustrate but forgot to attach it.

![2021-10-12 13-11-58 2021-10-12 13_13_57](https://user-images.githubusercontent.com/634063/137482185-4646d914-d577-41d4-bab0-ac353d40ac95.gif)

2021-10-15 11:54 UTC, tidy-dev commented on app/src/lib/api.ts
> +    jobs_url: string
Sure can. This would also apply to the logs_url - but that one I just found out I was doing in a more complicated way than I needed to because I had overlooked where I believe I can get individual job log in the API. Thus, I am going to open a separate PR to improve that anyways and I will make build the url then. :)

2021-10-15 11:55 UTC, tidy-dev commented
Surprised on the multiple calls to same jobs url id.. cause I am doing a cache to try to prevent just this.. :/

2021-10-15 12:07 UTC, tidy-dev commented
Fixed duplicate job calls:

https://user-images.githubusercontent.com/75402236/137484221-6788d4fe-302e-4509-b685-193c78e469f4.mov

2021-10-15 12:24 UTC, niik approved these changes
:sparkles:

2021-10-15 13:02 UTC, merged