Custom tooltips
desktop/desktop pull request #13116
Opened 2021-10-13 13:58 UTC by niik

Closes #6384 

## Description

The day has finally come. We've been talking about better tooltips for years now and hopefully this is it. We've done attempts before but have been thwarted either by complexity (positioning tooltips without overflowing the bounds of the window is tricky) or simplicity (using a primer-style CSS-only solution will only let us have text tooltips).

In designing this I had a few objectives that I hoped to achieve

1. Tooltips should not affect the element tree of the target (i.e. don't force me to wrap my button in a div)
2. Tooltips should be usable inside of our lists and should not be affected by `overflow: hidden` (i.e. absolute positioning relative to window[^1]). Additionally they should work transparently within a dialog (i.e. we can't rely entirely on z-index).
3. Tooltips should be accessible
4. We should allow interactive tooltips with images, buttons, you name it

I'm happy to say I think this PR achieves the objectives or at least comes pretty close. The accessibility part is tricky as I'm not an expert in it. I have followed the accessibility guidelines for custom tooltips as best I've could though.

This turned into a rather large PR, the majority of the changes being additions of tooltips, or removals of tooltips that shouldn't be tooltips (a tooltip with the same content as the button to which it's referring to doesn't add much value). I'll try to describe a few concepts and changes and hope that will alleviate some of the review burden but I'm also **happy to pair-review on this**

#### createObservableRef

React has two recommended ways of [capturing references](https://reactjs.org/docs/refs-and-the-dom.html) to component instances or underlying DOM elements. Either [createRef](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) or callback refs. You typically use `createRef` for its advantageous syntax and callback refs if you care about when the ref change.

For `Tooltip` I wanted a combination of both. I wanted the ease of use for consumers of `createRef` but I needed a way to get notified when the Ref changed. That's what `createObservableRef` does. For all intents and purposes it can be thought of as a normal Ref except that it also allows consumers to subscribe to change events.

#### Tooltip placement

When a tooltip is about to be displayed it'll look for the closest ancestor of the target element which is considered a suitable host for tooltips. For GitHub Desktop that's either the `body` or `dialog` element in case the target lives within a modal dialog.

#### Disabled buttons aren't disabled any more

One change of note in this PR is how we're handling disabled buttons. Previously we just slapped the `disabled` attribute on 'em and called it a day. Unfortunately that means no pointer events will trigger on the button which in turn means we have no way to know when to show the tooltip. Since showing tooltips for disabled buttons was called out even in the initial issue for this as being useful I had to take a different approach.

Instead of `disabled` we're now using `aria-disabled` to let a11y tools know what's up and we then disable the pointer events in react.

A side-effect of this is that disabled buttons are now reachable by keyboard navigation. This is a change in behavior but one that I think it beneficial from an accessibility standpoint.

See https://a11y-101.com/development/aria-disabled which recommends this approach over `disabled`

### Screenshots

<img src="https://user-images.githubusercontent.com/634063/137140811-098c01e6-90ca-4edb-b9cc-63bc4b704716.png" width="247" />

<img src="https://user-images.githubusercontent.com/634063/137140878-d5f6b533-73b7-42eb-8537-632d0a6d781f.png" width="555" />
<img src="https://user-images.githubusercontent.com/634063/137141139-588537fc-0a83-4675-9766-7e0127d21373.gif" width="566" />

<img src="https://user-images.githubusercontent.com/634063/137141580-70a4a6f0-56c9-42cc-96a0-86fb3e9ac83b.png" width="303" />

## Release notes

Notes:

[^1]: Rather closest modal container so window or dialog

2021-10-15 12:31 UTC, niik commented on app/src/ui/branches/pull-request-list-item.tsx
> +  readonly isDragInProgress: boolean
All of the changes related to this come from https://github.com/desktop/desktop/pull/13116/commits/0c0675843f54e9d4f897cbb034cd712141544de0 where we previously disabled all pointer events for all PR list items we only do so now when a drag operation is in progress.

2021-10-18 07:55 UTC, niik commented on app/src/ui/branches/branch-list-item.tsx
> -      : ''
This is handled by the `RelativeTime` component now instead

2021-10-18 07:56 UTC, niik commented on app/src/ui/branches/ci-check-list-item.tsx
> -              title={step.name}
This didn't add information which wasn't already present

2021-10-18 07:57 UTC, niik commented on app/src/ui/diff/side-by-side-diff-row.tsx
> -        }
This is sufficiently covered by the whitespace hint popover on click now

2021-10-18 07:58 UTC, niik commented on app/src/ui/lib/avatar-stack.tsx
> -      elems.push(<Avatar key={`${i}`} user={users[i]} title={null} />)
This is a change in behavior. We want to show tooltips for avatars even inside of an avatar stack

2021-10-19 11:45 UTC, sergiou87 requested changes
Looks great overall!! This approach feels super clean 😍 

Awesome job! Reviewing this was very educational too 🙇‍♂️

2021-10-19 11:45 UTC, sergiou87 commented on app/src/lib/is-empty-or-whitespace.ts
> + */
I guess `null` and `undefined` are not options anymore, right?
```suggestion
/**
 * Indicates whether the given string is empty or consists only of white-space
 * characters.
 */
```

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/tooltip.tsx
> +// Curse you SVGSVGElement
🤣 

What happened here? 😂  Is it worth explaining in the comment?

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/observable-ref.ts
> +  (instance: T): void
TIL about [Call Signatures](https://www.typescriptlang.org/docs/handbook/2/functions.html#call-signatures)

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/tooltip.tsx
> +  readonly onlyWhenOverflowed?: boolean
Could we have a comment for this one too?

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/tooltip.tsx
> +  for (const candidate of candidates) {
I was surprised to see this logic based on a Set, because in my experience with other languages sets were always unordered. TIL JavaScript uses the insertion order when you iterate over its entries!

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/tooltip.tsx
> +    }
Shouldn't this (or even better, `beginHideTooltip`) take into account not only whether or not the mouse is over the target, but also if it's over the tooltip (when it's interactive)?

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/tooltip.tsx
> +      }
Shouldn't we always remove the tooltip from the previous target?
```suggestion
      this.removeTooltip(prevState.target)
      if (target !== null) {
        this.installTooltip(target)
      }
```

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/branches/branch-list-item.tsx
>        </div>
Not sure if I'm in the wrong place, but the app is not showing these specific tooltips (branch name and relative time) for me 🤔  

2021-10-19 11:45 UTC, sergiou87 commented on app/src/ui/lib/path-text.tsx
> +            interactive={true}
Not for this PR, but since this is interactive, it'd be nice to have a copy button too 😄

2021-10-19 11:45 UTC, sergiou87 commented on app/styles/_variables.scss
>     * 0-6.
This comment needs to be updated, right?

2021-10-19 11:45 UTC, sergiou87 commented on app/styles/_variables.scss
>     * but behind popups, overlays, and foldouts
Same about this one? 😆

2021-10-25 09:20 UTC, niik commented on app/src/ui/branches/branch-list-item.tsx
>        </div>
My bad: 639752c3ac200713fdc3ec12744d353d6424e7d8

2021-10-25 09:20 UTC, niik commented on app/src/ui/lib/path-text.tsx
> +            interactive={true}
Yeah, I was going back and forth on that one. The reason I didn't add one was that these tooltips only show when the path overflows and I feel like if we add a nice copy-button it could lead to confusion when users aren't able to copy that way on all paths. I'm still not convinced either way though

2021-10-25 09:20 UTC, niik commented on app/src/ui/lib/tooltip.tsx
> +// Curse you SVGSVGElement
Lol, yeah probably: bd9d939b4539361405add50424a4dfebcf9658b4

2021-10-25 09:20 UTC, niik commented on app/src/ui/lib/tooltip.tsx
> +  readonly onlyWhenOverflowed?: boolean
You bet: db5482e4eca219bd8e902066dc4fbacbf2e0cc76

2021-10-25 09:20 UTC, niik commented on app/src/ui/lib/tooltip.tsx
> +      }
Yeah, good catch!

2021-10-25 09:20 UTC, niik commented on app/src/ui/lib/tooltip.tsx
> +  for (const candidate of candidates) {
Yup! Same goes for `Map`, very surprising but super handy

2021-10-25 09:21 UTC, niik commented on app/src/ui/lib/tooltip.tsx
> +    }
It sure should, nice catch: 7e7ed3121c870ff2d6a763a13228ed693c7ecccf

2021-10-25 09:23 UTC, niik commented on app/styles/_variables.scss
>     * 0-6.
Yeah, let's fix these once and for all: https://github.com/desktop/desktop/pull/13116/commits/3199e81d23b5192a51cbecc1cd04b118414d394d

2021-10-25 10:36 UTC, sergiou87 submitted a review, later dismissed
Thanks for those changes, it looks great now in my setup!! 😍 

The only thing I noticed (but can be done in a separate PR if we think it's worth it) is that you need to move the mouse "fast enough" when moving from the tooltipable element to the (interactive) tooltip or the tooltip will be hidden.

That means I expect people to randomly get the tooltip hidden when they try to interact with interactive tooltips. You can see in the following video how the tooltip disappears if my mouse lands anywhere between the tooltipable element and the tooltip itself:

https://user-images.githubusercontent.com/1083228/138680684-76c2004b-5970-47e0-97eb-35e2d925da0d.mov

Feel free to ignore this in this PR if you want, because otherwise it's ready for :shipit: ❗

2021-10-25 11:43 UTC, niik commented
> The only thing I noticed (but can be done in a separate PR if we think it's worth it) is that you need to move the mouse "fast enough" when moving from the tooltipable element to the (interactive) tooltip or the tooltip will be hidden.

Yeah, I've been tweaking that delay a few times but I probably ended up making it too fast. I've bumped the delay by another 100ms in https://github.com/desktop/desktop/pull/13116/commits/9b45db402c47a2b1fc3d1c16c83a9203c051ab54, let me know how that feels

2021-10-25 12:09 UTC, sergiou87 approved these changes
It feels much better, thanks! ❤️ 

Although to be honest I was expecting some kind of way to extend the "hoverable" area of the tooltip to overlap/reach the area of the tooltipable element.

That said, this approach definitely works good enough with 250ms, in my experience at least, so I'm more than happy to go ahead with it!

2021-10-25 12:18 UTC, niik commented
> Although to be honest I was expecting some kind of way to extend the "hoverable" area of the tooltip to overlap/reach the area of the tooltipable element.

Yeah, it's a bit of a hack. I did play around with an extended hit area but it got tricky when using pointer position placement (i.e. when not specifying a direction) as the hitarea could end up extending over the pointer itself. By no means an unsolvable problem but let's try the hack and see how it feels before trying something else. At the very least we could try extending the hitarea to encompass the tip of the tooltip.

2021-10-25 12:18 UTC, merged

2022-02-09 22:56 UTC, jmayes41 commented on app/src/ui/branches/pull-request-list-item.tsx
> +  readonly isDragInProgress: boolean
> All of the changes related to this come from https://github.com/desktop/desktop/pull/13116/commits/0c0675843f54e9d4f897cbb034cd712141544de0 where we previously disabled all pointer events for all PR list items we only do so now when a drag operation is in progress.