Warn hidden bidi characters in diffs
desktop/desktop pull request #13343
Opened 2021-11-18 13:06 UTC by sergiou87

## Description

This PR adds a file-level warning when hidden bidi characters are found in diffs. For this, I've used the same text and style used in dotcom.

### Screenshots

https://user-images.githubusercontent.com/1083228/142419897-38148e72-0522-4908-b79e-1b0fd713e941.mov

With dark theme:
![image](https://user-images.githubusercontent.com/1083228/142420682-f611c1ac-0dab-4376-8c23-409167c7fe11.png)

## Release notes

Notes: [Improved] Warn users when files contain bidirectional Unicode text

2021-11-18 15:05 UTC, tidy-dev commented
Looking at the hidden bidi characters.. imho the warning is sort of misleading. It says “This file contains…“, but it only shows when those characters are in the current diff (which I understand is what we have access to run the regex on at the moment). But… with those words as an unknowing user, I would be expecting it to run on the whole file and when you expand/collapse it feels weird that it goes away.  Wondering if we can’t do it on the whole file, if the verbiage should change to say "This diff contains..."

2021-11-18 15:31 UTC, sergiou87 commented
Sounds good!

2021-11-19 10:25 UTC, niik requested changes
Great work @sergiou87. I'm curious though as to why we're matching on each line instead of simply running the regex on the whole diff text which we receive in the parse function? What is it that I'm missing?

2021-11-19 10:25 UTC, niik commented on app/src/lib/diff-parser.ts
> +export const HiddenBidiCharsRegex = /[\u202A-\u202E]|[\u2066-\u2069]/
Could we please add a little explanatory comment here since it's being exported?

2021-11-19 10:25 UTC, niik commented on app/src/lib/diff-parser.ts
> +        hasHiddenBidiChars,
Couldn't we just run the regex here instead?

```suggestion
        hasHiddenBidiChars: HiddenBidiCharsRegex.test(text),
```

2021-11-19 12:38 UTC, sergiou87 commented
> why we're matching on each line instead of simply running the regex on the whole diff text which we receive in the parse function? What is it that I'm missing?

I'd say lack of proper sleep, sorry 😓   It's mainly a leftover of my initial approach (that we discussed on Monday) of looking for these characters only in added lines, then after our chat on Monday I switched to show the warning whenever those chars are found anywhere in the diff, but I wanted to try and show _something_ per line too. Finally, I realized it wasn't worth the effort and started cleaning up my mess but I guess I stopped early 🤦‍♂️

I'll switch to that approach!

2021-11-19 12:57 UTC, sergiou87 commented
@niik all fixed in my latest commits. Thank you! 🙇‍♂️

2021-11-19 15:35 UTC, niik approved these changes
💖

2021-11-19 15:46 UTC, merged