Flag rerun button to non-GHE repos
desktop/desktop pull request #13460
Opened 2021-12-07 14:17 UTC by tidy-dev

## Description

Since there were api changes made to the Checks api, we cannot support the rerun function for GHE repos as those new changes are not available on GHE yet.

### Screenshots
https://user-images.githubusercontent.com/75402236/145045335-9b5c53ba-eed9-4c3d-968e-2bd510315b27.mov

## Release notes
Notes: [Fixed] Remove rerun button from GHE repositories.

2021-12-07 16:45 UTC, niik requested changes

2021-12-07 16:45 UTC, niik commented on app/src/models/github-repository.ts
> +  public get isGHE(): boolean {
So `ghe.io` is our own internal GitHub Enterprise Server (GHES) installation. For a customer the endpoint would typically be somethine like `https://github.company.com/api/v3`. So what we typically do everywhere we need to differentiate GitHub.com from non GitHub.com endpoints (which up until the advent of GHAE was only GHES) is to check if the endpoint matches .com's API endpoint and if it doesn't we'll know that it's either GHAE or GHES.

2021-12-07 16:45 UTC, niik commented on app/src/ui/check-runs/ci-check-run-popover.tsx
> +    if (this.props.repository.isGHE) {
While it'd be nice to have a more reusable approach here I'm proposing we stick with our typical way of selectively targeting GHES here and potentially consider a more generalized approach separately.

```suggestion
    // GHES doesn't support rerunning checks yet
    if (this.props.repository.endpoint !== getDotComAPIEndpoint()) {
      return null
    }
```

2021-12-10 12:24 UTC, niik approved these changes

2021-12-10 14:13 UTC, merged

2021-12-11 03:56 UTC, tylaangels commented
thx