Fix commit message dialog inherited styles
desktop/desktop pull request #13610
Opened 2021-12-29 16:06 UTC by tidy-dev

Closes #13606 

## Description
My use case is different from the bug ticket, but it is the same div, just a different warning.

### Screenshots

![image](https://user-images.githubusercontent.com/75402236/147681321-00c057b9-3edc-4d83-8981-2de8b593331e.png)

## Release notes
Notes: [Improved] Commit message dialog warning background styles congruent with dialog.

2022-01-04 13:36 UTC, niik reviewed
The fact that these are `id`s makes me uncomfortable. Could we address that in the same PR by making both `commit-message` and `commit-warning` classes instead following the typical pattern we use (i.e. `commit-message-component` and `commit-warning-component`)?

2022-01-10 13:20 UTC, tidy-dev commented
Updated to use classes:
![image](https://user-images.githubusercontent.com/75402236/148772515-0a6d35c2-96b3-46e0-8918-a7908ff1dfa8.png)

And showing main commit message area unaffected:
![image](https://user-images.githubusercontent.com/75402236/148772593-84c8e180-d7e1-439d-a365-a2869fb4fa6a.png)

(I also tested in dark mode tho I wouldn't have expected anything there)

2022-01-10 16:43 UTC, niik requested changes
Thanks a bunch for making those changes @tidy-dev, could we also remove the `id` attricute from the `CommitMessage` div wrapper now that we've turned it into a class?

2022-01-11 16:55 UTC, niik approved these changes

2022-01-11 17:55 UTC, merged

2022-03-12 20:47 UTC, Mc480 commented
> Closes #13606
> 
> ## Description
> My use case is different from the bug ticket, but it is the same div, just a different warning.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/75402236/147681321-00c057b9-3edc-4d83-8981-2de8b593331e.png)
> 
> ## Release notes
> Notes: [Improved] Commit message dialog warning background styles congruent with dialog.