Add Context Menu to Current Branch and Current Repository Buttons
desktop/desktop pull request #13664
Opened 2022-01-12 22:26 UTC by uttiya10

Closes #13148 

## Description
- Adds Context Menu To Current Branch and Current Repository Toolbar Buttons

### Screenshots

![image](https://user-images.githubusercontent.com/56562649/149232048-52f0e138-7b96-43d8-9d57-f8cc5463d785.png)

## Release notes

Notes: [ADDED] Add context menu to Current Branch and Current Repository Toolbar

2022-01-18 14:04 UTC, niik requested changes
Hey @uttiya10, thanks so much for wanting to contribute! I've made some (mostly stylistic) suggestions that I'd love for you to take a look at when you've got a moment. Looking forward to having context menus on these buttons!

2022-01-18 14:04 UTC, niik commented on app/src/ui/app.tsx
> +  private onContextMenu = () => {
Given that this method lives in the rather large `App` component I think a more suitable name for this method would be `onRepositoryToolbarButtonContextMenu`. With a generic name like this a reader would have to look for its uses to understand which context menu we're talking about.

2022-01-18 14:04 UTC, niik commented on app/src/ui/toolbar/branch-dropdown.tsx
> +  private createContextMenuItems = (
For consistency I'd like it if we named this `onBranchToolbarButtonContextMenu`

2022-01-18 14:04 UTC, niik commented on app/src/ui/app.tsx
> +    }
We try to avoid relying on truthy/falsy checks, could we make this an explicit check instead and perhaps leverage optional chaining while we're at it?
```suggestion
    const repository = this.state.selectedState?.repository
    if (repository === undefined) {
      return
    }
```

2022-01-18 14:04 UTC, niik commented on app/src/ui/app.tsx
> +      : undefined
```suggestion
    const externalEditorLabel = this.state.selectedExternalEditor ?? undefined
```

2022-01-18 14:04 UTC, niik commented on app/src/ui/branches/branch-list-item-context-menu.tsx
> +export function createBranchContextMenuItems(
I really liked the approach you took in `generateRepositoryListContextMenu` with using an interface rather than parameters. When we have multiple compatible types like this (i.e onRenameBranch and onDeleteBranch are type compatible) I'd prefer that approach.

2022-01-18 14:04 UTC, niik commented on app/src/ui/branches/branch-list-item-context-menu.tsx
> +  const items: Array<IMenuItem> = []
We typically use `new Array<T>` instead of `Array<T> = []`
```suggestion
  const items = new Array<IMenuItem>()
```

2022-01-18 14:04 UTC, niik commented on app/src/ui/repositories-list/repository-list-item-context-menu.ts
> +    config.repository instanceof Repository && config.repository.missing
I think it'd make sense to extract `repository` into a separate variable here to tidy things up a bit.

```suggestion
  const { repository } = config
  const missing =
    config.repository instanceof Repository && config.repository.missing
```

2022-01-18 14:04 UTC, niik commented on app/src/ui/repositories-list/repository-list-item-context-menu.ts
> +  return items
We could simplify this a bunch by capturing repository into a const and only doing the `Repository` type check once

```suggestion
  const { repository } = config
  if (!(repository instanceof Repository) || !enableRepositoryAliases()) {
    return []
  }

  const verb = repository.alias == null ? 'Create' : 'Change'
  const items: Array<IMenuItem> = [
    {
      label: __DARWIN__ ? `${verb} Alias` : `${verb} alias`,
      action: () => config.onRemoveRepositoryAlias(repository),
    },
  ]

  if (repository.alias !== null) {
    items.push({
      label: __DARWIN__ ? 'Remove Alias' : 'Remove alias',
      action: () => config.onChangeRepositoryAlias(repository),
    })
  }

  return items
```

2022-01-18 14:04 UTC, niik commented on app/src/ui/toolbar/dropdown.tsx
> +    }
```suggestion
    this.props.onContextMenu?.(event)
```

2022-01-18 14:04 UTC, niik commented on app/src/ui/toolbar/button.tsx
> +    }
```suggestion
    this.props.onContextMenu?.(event)
```

2022-01-18 16:16 UTC, uttiya10 commented
Thanks for the review! I pushed some changes that should hopefully resolve all your requests.

2022-06-22 14:06 UTC, niik approved these changes
My apologies for the long delay in getting you a second review here @uttiya10. I appreciate your patience!

I took care of merging with the latest changes from development and this is looking great now with your latest set of changes, thanks so much!

2022-06-22 14:06 UTC, merged