Add "Copy Relative File Path" Option to Changed Files' Context Menu
desktop/desktop pull request #13751
Opened 2022-01-27 00:21 UTC by uttiya10

Closes #12589

## Description
Add the ability to copy a changed files' relative path

### Screenshots
![image](https://user-images.githubusercontent.com/56562649/151267885-d70bc53a-8a1c-4e37-92e8-6e9391d2459c.png)

## Release notes
Notes:
- [ADDED] Copy the Relative File Path of a Changed File

2022-02-04 17:03 UTC, tidy-dev requested changes
@uttiya10 Thank you for wanting to add this context menu!

This is looking great and tested it out great.

One request tho is that we also have the "Copy File Path" on the files in the history view. We would like to be consistent and have this "Copy Relative File Path", there as well. Should be simply adding the same thing to `selected-commit.tsx` file.

2022-02-07 14:03 UTC, tidy-dev requested changes
Thanks for adding that additional context menu @uttiya10!  It works great!

I have one super small request, bit of a nit, and then I think it should be good to go! Seeing as the "View on GitHub" menu item is not conditional, I think it makes senes to leave that logic separate and put the `{ type: 'separator' }` added in line 384 of `selected-commit.tsx` beneath the new context menu at line 370.

2022-02-07 16:08 UTC, uttiya10 commented
Ahh, I misunderstood the code 🤦‍♂️. I thought the `View on Github` menu item wasn’t always shown, so a separator is optional. However, its actually always shown but *not always enabled*. Will push an update soon.

2022-02-08 13:42 UTC, tidy-dev approved these changes
✨  Thank you so much for those changes and wanting to contribute to GitHub Desktop!

2022-02-08 13:44 UTC, merged

2022-02-14 14:22 UTC, ZmoraKaBeKa commented on app/src/ui/changes/changes-list.tsx
>  } from '../lib/context-menu'
```suggestion
 } from '../lib/context-menu'haha
```