Release 2.9.7-beta1
desktop/desktop pull request #13796
Opened 2022-01-31 16:43 UTC by tidy-dev

## Description

Looking for the PR for the upcoming first beta of the v2.9.7 series? Well, you've just found it, congratulations!

## Release checklist

- [x] Check to see if there are any errors in Sentry that have only occurred since the last production release
- [x] Verify that all feature flags are flipped appropriately
- Pull request quick view is set to dev
- Notifications beta enabled or macOs
![image](https://user-images.githubusercontent.com/75402236/151835245-0d3e0895-9f1c-4852-ab70-a99b44755b69.png)
- [ ] If there are any new metrics, ensure that central and desktop.github.com have been updated
-- Metrics added for notifications
-- desktop.github.com not merged

2022-01-31 16:50 UTC, billygriffin requested changes
Minor changes, but overall looking good!

2022-01-31 16:50 UTC, billygriffin commented on changelog.json
> +      "[Added] Initial support for high-signal notifications in macOS - #13655",
```suggestion
      "[New] Initial support for high-signal notifications in macOS - #13655",
```

2022-01-31 16:50 UTC, billygriffin commented on changelog.json
> +      "[Fixed] Job steps on pull-request check run list are no longer intermittently missing - #13531",
```suggestion
      "[Fixed] Ensure job steps on pull request check run list are always present - #13531",
```

2022-01-31 16:50 UTC, billygriffin commented on changelog.json
> +      "[Fixed] Take alias into account when sorting repositories - #13429",
```suggestion
      "[Improved] Take alias into account when sorting repositories - #13429",
```

2022-01-31 16:50 UTC, billygriffin commented on changelog.json
> +      "[Improved] Removed unnecessary punctuation in appearance settings- #13715. Thanks @Pinzauti!"
```suggestion
      "[Improved] Remove unnecessary punctuation in appearance settings- #13715. Thanks @Pinzauti!"
```

2022-01-31 16:55 UTC, billygriffin commented on changelog.json
> +      "[New] Initial support for high-signal notifications in macOS - #13655",
```suggestion
      "[New] Initial support for system notifications when checks fail in macOS - #13655",
```

2022-01-31 16:56 UTC, billygriffin approved these changes, later dismissed
Wooooo!

2022-01-31 19:27 UTC, tidy-dev commented on changelog.json
> +      "[Improved] Add \"View on GitHub\" context menu option - #13227. Thanks @lhvy!",
```suggestion
      "[Improved] Add \"View on GitHub\" context menu option to repository list items - #13227. Thanks @lhvy!",
```

2022-02-01 13:21 UTC, tidy-dev commented on changelog.json
> +      "[Improved] Add \"View on GitHub\" context menu option - #13227. Thanks @lhvy!",
Realized when testing this.. that I had to go to the pr to remember where that was added. :P

2022-02-02 09:02 UTC, sergiou87 approved these changes

2022-02-02 09:02 UTC, merged