Make dark scrollbar in dark theme
desktop/desktop pull request #14142
Opened 2022-03-10 17:56 UTC by rakleed

Closes #11174

## Description

- Make a dark scrollbar in a dark theme. Although the implementation method is not the best, since the https://github.com/desktop/desktop/blob/development/app/styles/themes/_dark.scss file contains CSS variables, judging by its description.

### Screenshots

<details><summary>Before</summary>

![Screenshot 2022-03-10 at 20 51 45](https://user-images.githubusercontent.com/19418601/157724710-61f4322b-19f3-401b-9c69-736a5c89c14a.png)

</details>

<details><summary>After</summary>

![Screenshot 2022-03-10 at 20 51 02](https://user-images.githubusercontent.com/19418601/157724611-c53ce518-10b6-4fca-bc3c-7357ce3a7bc6.png)

</details>

## Release notes

Notes:

2022-03-11 08:45 UTC, niik requested changes, later dismissed
Thanks so much for this @rakleed, today I learned about color-scheme! I could have sworn I looked for something like this when I did the dark theme but I see that support for it was added to Chromium very recently so maybe that's why.

Could you add the same approach to our `_high-contrast.scss` theme please? That theme is still in beta but it's based on the dark theme.

2022-03-11 09:14 UTC, rakleed commented
> Could you add the same approach to our `_high-contrast.scss` theme please? That theme is still in beta but it's based on the dark theme.

Done. But I was unable to enable the high contrast theme in GitHub Desktop on macOS to test the change.

2022-03-14 13:31 UTC, niik commented
Thanks so much for this @rakleed, this is exactly what we need. I did realize that we can't set color scheme on the root element in the theme CSS directly since the dark stylesheet is always loaded. Doing so would mean that we'd render dark scrollbars, checkboxes, etc even in light mode.

I took the liberty of updating your PR to set the `color-scheme` property dynamically as part of the app's theme update logic. I'll ask one of my colleagues to take another look here now that I've made changes but I'm really excited about gettitng this in.

@tidy-dev @sergiou87 Removing myself from this PR since I've meddled with it. This PR will ensure that we render not only scrollbars properly according to the theme but also elements that we haven't styled specifically such as checkboxes, radiobuttons, etc.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/634063/158182053-37ebc765-59b5-4019-a30c-67272ec22c7f.png">

<img width="362" alt="image" src="https://user-images.githubusercontent.com/634063/158182078-a0b6968d-64ed-428b-a17a-f4506a47c045.png">

2022-03-15 11:36 UTC, tidy-dev approved these changes
✨  Makes sense and tested out well!

2022-03-15 11:38 UTC, merged

2022-10-05 19:04 UTC, rakleed commented
@tidy-dev @niik I did not find the source code of the https://desktop.github.com site in the public domain. Can you also add the same property on this site as in my PR, or send such a request to the site developers?