Custom Video Markdown filters
desktop/desktop pull request #14168
Opened 2022-03-14 17:02 UTC by tidy-dev

## Description
This pr adds two markdown filters for managing video tags. 
1) The video tag filter looks for video tags and, if their src does not look like a GitHub user asset video url, then we remove the video tag.
2) The video link tag looks for where a user may have pasted a GitHub user asset url into markdown. In this case, the markdown parser will autotag the link and put it in a paragraph tag. This filter searches for that pattern and replaces it with a video tag.

Additionally, this pr added a css style to max-width a video element so it doesn't extend out of view of scrollable area.

This filter deviates from dotcom in that dotcom verifies the GitHub user asset url actually has an asset. For performance (not having to hit api), this filter looks for things that start with "https://user-images.githubusercontent.com" and end with a video extension. This means we could have a false positive which will result in a video tag that does not render anything, where dotcom would simply show the invalid video link. This would be unlikely (probably from user copy/paste error) and still must have a the safe github cdn host so users could not use this to view externally hosted videos.

## Release notes
Notes: [Improved] Sandbox markdown parser parses video tag to remove externally linked videos and video url links to display valid uploaded videos.

2022-03-14 17:18 UTC, sihamitas40 commented on app/src/lib/markdown-filters/node-filter.ts
> +import { VideoLinkFilter } from './video-link-filter'
استيراد  {  VideoLinkFilter  }  من  "./video-link-filter"

2022-03-16 09:33 UTC, niik requested changes
Just a few requests here @tidy-dev

2022-03-16 09:33 UTC, niik commented on app/src/lib/markdown-filters/video-link-filter.ts
> +    })
I'd prefer if we used a bound method here instead of disabling the eslint rule. We try to avoid capturing `this` if possible

```suggestion
    return doc.createTreeWalker(doc, NodeFilter.SHOW_ELEMENT, {
      acceptNode: (el: Element) =>
        this.getGithubVideoLink(el) === null
          ? NodeFilter.FILTER_SKIP
          : NodeFilter.FILTER_ACCEPT,
    })
```

2022-03-16 09:33 UTC, niik commented on app/src/lib/markdown-filters/video-link-filter.ts
> +   * <videosrc="https://user-images.githubusercontent.com/7559041/1234.mp4"></video>
```suggestion
   * <video src="https://user-images.githubusercontent.com/7559041/1234.mp4"></video>
```

2022-03-16 09:33 UTC, niik commented on app/src/lib/markdown-filters/video-tag-filter.ts
> +    // eslint-disable-next-line @typescript-eslint/no-this-alias
Doesn't seem to be necessary here?

```suggestion
```

2022-03-16 09:33 UTC, niik commented on app/src/lib/markdown-filters/video-tag-filter.ts
> +      // This is different then dotcom that regenerates a video tag because it
```suggestion
      // This is different than dotcom which regenerates a video tag because it
```

2022-03-16 09:33 UTC, niik commented on app/src/lib/markdown-filters/video-url-regex.ts
> +  escapeRegExp(user_images_cdn_url) + '.+' + videoExtensionRegex.source,
This needs to be anchored to the start or else a malicious user could craft a url like `https://evil.com/https://user-images.githubusercontent.com/evil.mp4`

```suggestion
  '^' + escapeRegExp(user_images_cdn_url) + '.+' + videoExtensionRegex.source,
```

2022-03-16 11:21 UTC, tidy-dev commented on app/src/lib/markdown-filters/video-url-regex.ts
> +  escapeRegExp(user_images_cdn_url) + '.+' + videoExtensionRegex.source,
🤦  Thank you!

2022-03-22 13:56 UTC, niik requested changes
Just a tiny tiny nit here @tidy-dev

2022-03-22 13:56 UTC, niik commented on app/src/lib/markdown-filters/video-url-regex.ts
> +import { escapeRegExp } from 'lodash'
Can we use the `escapeRegExp` function from `regex.ts` instead? I'd rather we made a conscious decision to move over to lodash's method across the code base than to mix

```suggestion
import { escapeRegExp } from '../helpers/regex'
```

2022-03-22 13:58 UTC, niik approved these changes

2022-03-22 14:23 UTC, merged