Number formatting using Intl.* APIs
desktop/desktop pull request #14174
Opened 2022-03-15 12:39 UTC by niik

Closes #1245

## Description

~~Back in 2017 I wrote *"I'm leaning towards trying to solve this properly."* in response to our first attempt  at fixing #1245 (https://github.com/desktop/desktop/pull/1257). Now, 5-ish years later technology has finally caught up to where we're able to do this with a relatively small amount of support logic :tada:~~

**Turns out ☝️ was a little bit premature, see https://github.com/desktop/desktop/pull/14173#issuecomment-1072293321**

This builds upon #14173 and adds region-aware formatting of numbers.

I also took this opportunity to render the number of commits ahead/behind in a compact format (i.e number > 1000 will render as 1K). Hovering will get you the exact number but if you're behind by 1000 or more you likely don't care about the exact number.

There's a good chance I've missed a number of (pun intended) places where we present numbers to the user but that's okay, we can fix that incrementally.

### Screenshots

| Before | en-US | en-SE |
|--------|-------|-------|
|  <img width="239" alt="image" src="https://user-images.githubusercontent.com/634063/158374912-6c26db3b-c0f0-4e7e-9fc7-3a5b6815804c.png"> | <img width="248" alt="image" src="https://user-images.githubusercontent.com/634063/158375549-41b264e1-78a9-4d4a-bf18-238b6ef3d7da.png"> | <img width="244" alt="image" src="https://user-images.githubusercontent.com/634063/158374976-0a717bad-276f-43aa-8c13-e627fd206264.png"> |
| <img width="211" alt="image" src="https://user-images.githubusercontent.com/634063/158375173-449f0cdb-96b0-4b1b-a56b-28750c03e75b.png"> | <img width="216" alt="image" src="https://user-images.githubusercontent.com/634063/158375616-eaba13c0-149a-4457-8e0e-604d054af3ad.png"> | <img width="217" alt="image" src="https://user-images.githubusercontent.com/634063/158375250-72be325d-ce7a-4d93-b04a-6f2fee1e10fd.png"> |

## Release notes

Notes: no-notes

2022-03-16 12:19 UTC, tidy-dev requested changes
Just a little spelling nit. But, also one of the places you missed is line 654 of `compare.tsx` for squashing dialog. 

As for it working, I switched my region to Sweden, Spain, and France. It worked as expected for Sweden, but not for Spain or France. But, I figure the is the same issue that Sergio mentioned in slack so I am assuming not something for this PR.

2022-03-16 12:19 UTC, tidy-dev commented on app/src/lib/format-number.ts
> +// Initializing a nuumber formatter is expensive but formatting is relatively
```suggestion
// Initializing a number formatter is expensive but formatting is relatively
```

2022-03-18 10:57 UTC, niik commented
So this will also be affected by https://github.com/desktop/desktop/pull/14173#issuecomment-1072293321.

Given that we're switching to `en-US-POSIX` by default there will be no number grouping for now.

@sergiou87 @tidy-dev One thing that will change with this PR though is the compact format of commits > 1000. I think that's okay though even though that'll use `.` as the decimal separator. Our plan is definitely to try and support non-US region formats soon and the number of users pushing/pulling more than 1000 commits should be relatively low.

2022-03-18 16:15 UTC, tidy-dev approved these changes
:sparkles: Makes sense. :)

2022-12-27 14:28 UTC, Eminealtug commented
.

2023-04-13 08:10 UTC, merged