Add default option for pulling divergent paths
desktop/desktop pull request #14439
Opened 2022-04-22 15:17 UTC by tidy-dev

Closes #14431, Closes #14423

## Description
We have had a few reports since upgraded git about running to the following error:
![image](https://user-images.githubusercontent.com/75402236/164743560-a5645c22-c97f-4db0-a00b-16864ffdb6dd.png)

For users unfamiliar with using the command line, this error is not terribly helpful.

This PR proposes to check to see if the user has a configuration set for pulling divergent paths and, if not, default to using the [`-ff` flag](https://git-scm.com/docs/git-pull#Documentation/git-pull.txt---ff). When possible, it will attempt to fast forward the current branch and if not will perform a merge to reconcile the divergent paths.

## Release notes
Notes: [Fixed] Allow users to pull divergent paths without specifying a pull config

2022-04-25 16:14 UTC, niik requested changes
Thanks for putting this together @tidy-dev! I'll be back after dinner to re-review!

2022-04-25 16:14 UTC, niik commented on app/src/lib/git/pull.ts
> +  const pullRebase = await getConfigValue(repository, 'pull.rebase')
Based on my reading of https://github.com/git/git/blob/d516b2db0af2221bd6b13e7347abdcb5830b2829/builtin/pull.c#L1011-L1040 we shouldn't have to consider `pull.rebase` here since that takes precedence over `pull.ff`. We only need to make sure that `pull.ff` is set somehow.

I verified this on my Windows VM using 2.35:

```
C:\Users\markus\Documents\GitHub\desktop>git pull
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

C:\Users\markus\Documents\GitHub\desktop>git -c pull.ff pull
Merge made by the 'ort' strategy.
 app/package.json            | 2 +-
 app/src/lib/feature-flag.ts | 2 +-
 changelog.json              | 3 +++
 3 files changed, 5 insertions(+), 2 deletions(-)

C:\Users\markus\Documents\GitHub\desktop>git reset --hard "origin/development^" && git commit --allow-empty -m 'empty'
HEAD is now at 2ef68123f Revert "More useful test pull request checks failed"
[development e0320904a] 'empty'

C:\Users\markus\Documents\GitHub\desktop>git -c pull.rebase pull
Successfully rebased and updated refs/heads/development.

C:\Users\markus\Documents\GitHub\desktop>git reset --hard "origin/development^" && git commit --allow-empty -m 'empty'
HEAD is now at 2ef68123f Revert "More useful test pull request checks failed"
[development b60d0c82b] 'empty'

C:\Users\markus\Documents\GitHub\desktop>git -c pull.ff=only -c pull.rebase pull
fatal: Not possible to fast-forward, aborting.

C:\Users\markus\Documents\GitHub\desktop>git -c pull.ff -c pull.rebase pull
Successfully rebased and updated refs/heads/development.
```

2022-04-25 16:14 UTC, niik commented on app/src/lib/git/pull.ts
> +  const pullFF = await getConfigValue(repository, 'pull.ff')
Given that this is in such a critical path of the app (pulling) and given that we're doing a major release tomorrow I think it's prudent to be a bit conservative here and guard against this lookup failing. If it does we can assume it's set (which will cause the error described in the PR which isn't great but it's better than failing completely)

```suggestion
  const pullFF = await getConfigValue(repository, 'pull.ff').catch(e => {
    log.error("Couldn't read 'pull.ff' config", e)
    return null
  })
```

2022-04-25 16:41 UTC, tidy-dev commented on app/src/lib/git/pull.ts
> +  const pullRebase = await getConfigValue(repository, 'pull.rebase')
Done and did my own little smoke screen test. With pull.rebase true set and the code providing the -ff flag, it did the rebase.

2022-04-25 16:49 UTC, tidy-dev commented on app/src/lib/git/pull.ts
> +  const pullFF = await getConfigValue(repository, 'pull.ff')
Not sure if you have a strong preference to the `.catch` vs in a `try/catch`. But, the logic we need would require return a faux response such as "true" (really just not null)... just a personal preference of mine not to introduce fake responses and just acknowledge the failure in the try/catch. But, not terribly strong willed on this if you really refer the `.catch` syntax (or there is a functionally compelling reason to prefer it).

2022-04-25 18:38 UTC, niik approved these changes

2022-04-25 18:44 UTC, niik commented on app/src/lib/git/pull.ts
> +  const pullFF = await getConfigValue(repository, 'pull.ff')
I don't have a strong preference no. In this case I like having catch return a value that the subsequent logic can then handle as if it was a default value. That way there's only one source of truth for what the "no value" case should return. But this is very much on a case-by-case basis and could just as easily have been accomplished with a variable.

All that said this is likely how I would have written that method had the stylistic choice been entirely up to me 😄 

```ts
const getDefaultPullDivergentBranchArguments = (repository: Repository) =>
  getConfigValue(repository, 'pull.ff')
    .catch(e => {
      log.error("Couldn't read 'pull.ff' config", e)
      return null
    })
    .then(ff => (ff === null ? ['ff'] : []))
```

2022-04-25 19:15 UTC, merged

2024-05-05 02:45 UTC, yuHXmi reviewed
ok