Add copy paths when multiple files are selected
desktop/desktop pull request #14667
Opened 2022-05-23 16:11 UTC by tsvetilian-ty

Closes #14638

## Description
- Add "Copy Paths" and "Copy Relative Paths" when multiple files are selected

The paths are copied with space-delimited as suggested in the feature request!

### Screenshots
![multiple-path-copy](https://user-images.githubusercontent.com/9341546/169862112-4c5a9f86-e567-4545-a647-56c5c9cba911.gif)

2022-05-26 11:29 UTC, sergiou87 commented
I like this! @tfsJoe is there a reason why you suggested those paths to be separated by spaces instead of new lines?

I see VS Code separates them in lines, so I'd rather stick to some behavior that is considered standard.

2022-05-26 12:05 UTC, tfsJoe commented
From the issue:

 > the user may want to do something like `git some-command -- file1 file2 file3`

This is the use case that led me to write the ticket. So I'm trying to avoid an extra step to put those on one line.

2022-05-27 11:38 UTC, sergiou87 commented
Thank you! I'll discuss it with the team and let you know 😄

2022-06-07 14:25 UTC, sergiou87 commented
Hey! Sorry for the late response. We just discussed about this, and we think it's better to go with the standard approach of using new lines.

While we agree it might seem very convenient to use spaces for the use case mentioned above, it's also true that in order to make those paths "command line ready" we could need more than just separating them by spaces. For example, if the paths being copied have spaces, those must be escaped or the whole path quoted. That might also vary depending on the specific shell you use.

Using new lines is 1) a broadly adopted convention and 2) forces users to do proper treatment of the copied text before pasting it in a command line, depending on that terminal needs.

2022-06-07 17:02 UTC, tsvetilian-ty commented
@sergiou87 the separator is updated to a new line

2022-06-10 09:32 UTC, sergiou87 requested changes

2022-06-10 09:32 UTC, sergiou87 commented on app/src/ui/changes/changes-list.tsx
> +        clipboard.writeText(fullPaths.join('\r\n'))
Instead of hardcoding `\r\n`, you can [`import { EOL } from 'os'` instead which will change depending on the platform](https://nodejs.org/api/os.html#oseol)

2022-06-10 09:32 UTC, sergiou87 commented on app/src/ui/changes/changes-list.tsx
> +        clipboard.writeText(paths.join('\r\n'))
Same!

2022-06-10 13:37 UTC, sergiou87 approved these changes
Looks great now, thank you! ❤️

2022-06-10 13:37 UTC, merged