Use diff not log for diffing
desktop/desktop pull request #14668
Opened 2022-05-23 16:12 UTC by tidy-dev

## Description
This is first step in the direction to support multi commit diffing for that we need to use 'git diff'. This PR is to switch our diffing git call to use 'git diff' as opposed to log. 

Scenarios considered/tested: 
- adding
- changing
- renaming
- images
- initial commit
- squashing onto initial commit

## Release notes
Notes: no-notes

2022-05-23 16:18 UTC, tidy-dev commented on app/src/lib/git/diff.ts
> +  const oldestCommit = `${commitsToUse.at(-1)}`
This bit is the major downside to `git diff` over `git log`. Thoughts? 
1) Could leave as is and use this constant.. some googling says it has always been not likely to change.
2) Use `git hash-object -t tree /dev/null` (save the result after first call).. a little future proofing in case this were to ever change.

2022-05-24 11:16 UTC, niik requested changes
This is a tricky one @tidy-dev but I'm wondering if, given how rare it is to diff the initial commit, we should optimize for the case where the initial commit is not part of the selection and get rid of the `selectionContainsInitialCommit` state keeping entirely.

Instead we could attempt to run the diff and detect if it fails due to an invalid revision and in that case diff against the null tree instead.

> ⚠️ Warning. This is a very impactful change if there are regressions as diff generation is core to the app. 😟 Thus, open for any suggestions for different scenarios to test. (Also, is feature flagged)

We could keep using the `log` approach for single-commit diffs for the foreseeable future and only switch to the diff based approach once we've gained enough confidence in it. This has the added benefit of us not having to solve the problem with `selectionContainsInitialCommit` at all for the time being. The more I think about it the more I like this approach, we avoid a lot of edge cases and get two specialized methods, one for single commit diffs, and one for commit ranges (endpoints really).

2022-05-24 11:16 UTC, niik commented on app/src/lib/git/diff.ts
> +  const emptyTreeHash = '4b825dc642cb6eb9a060e54bf8d69288fbee4904'
Using the null tree is fine, in fact we've already defined this as a constant in `diff-index.ts` (NullTreeSHA). Might as well pull it out of there and into this file and export it along with a little blurb of documentation.

2022-05-24 11:16 UTC, niik commented on app/src/ui/dispatcher/dispatcher.ts
> +                )) === 1
Counting commits in a repository can be very expensive for large repositories. Instead of using `rev-list --count` here we should look at the commit in question and see if it has any parents. If we have to know whether this commit is the first commit here a specialized method to run `git log -1 --format=%P SHA --` would be my preference

2022-05-24 11:16 UTC, niik commented on app/src/ui/history/commit-list.tsx
> +      this.getLastRetainedCommitRef(indexes) === null
Is this really doing what we expect it to? Looking at the `getLastRetainedCommitRef` it seems to look at the last commit in the `commitSHAs` list is among the selected ones. That doesn't _necessary_ mean that the first commit of the branch is selected since `commitSHAs` is loaded incrementally.

So if you go to the history tab and hit <kbd>Cmd</kbd>+<kbd>A</kbd> to select all commits the `selectionContainsInitialCommit` will be true and we will diff against the null tree without having selected the initial commit.

I think what we'd want to do here is something like

```suggestion
    const selectionContainsInitialCommit =
      selectedCommits.at(-1)?.parentSHAs.length === 0

2022-05-24 13:53 UTC, tidy-dev commented on app/src/ui/dispatcher/dispatcher.ts
> +                )) === 1
:D One of the reasons I split this off into its own PR so early is I wanted to get your all feedback about stuff like this! That makes total sense

2022-05-24 17:54 UTC, tidy-dev commented on app/src/ui/history/commit-list.tsx
> +      this.getLastRetainedCommitRef(indexes) === null
Rendered moot since changed approach to try, check for bad revision, and then retry with null tree sha.

2022-05-24 18:00 UTC, tidy-dev commented
After some discussion, I have updated this PR to not keep track of a state variable to determine if the range is over an initial commit. Switched to @niik suggested approach of trying it and if it fails with a bad revision to retry it with the null tree sha. 

Additionally, added a clause to only use this new diff code if there is more than one sha being diffed (which at this point is not programmatically possible). **Thus, just pulling this PR to test is not enough to run this logic, you must remove the shas.length > 1 ( add in https://github.com/desktop/desktop/pull/14668/commits/772cbfc80d3f45cfaaed5988c0c7cc30231c3ccd) clause after the feature flag check, if you want to try using it to see diffs for a single commit**

2022-05-24 18:00 UTC, tidy-dev commented on app/src/ui/dispatcher/dispatcher.ts
> +                )) === 1
Moot since don't need to track this state

2022-05-24 18:10 UTC, tidy-dev commented on app/src/lib/git/diff.ts
> +    const useNullTreeSHA = true
@niik We discussed adding another git call here to verify that the bad revision was caused by the oldest sha not having a parent and doing a non fatal error to track and make sure this isn't a thing, then removing the check in a month or so if we don't get any reports of it. 

I am leaning to this not being worth the effort since it "shouldn't" happen as Desktop is getting the sha's from the `git log` call and therefore they should exist and we shouldn't be get bad revisions (except in this case)

For anyone else following along, the negative consequence of not doing this would be that we could unintentionally attempt a diff for a commit range using the null tree sha that would be very large if the bad revision was due to the oldest commit reference being corrupted. (imagine going from desktop's latest commit in development to the initial commit :D)

2022-06-01 12:45 UTC, niik requested changes

2022-06-01 12:45 UTC, niik commented on app/src/lib/git/diff.ts
> +    const useNullTreeSHA = true
That all sounds great. One comment on the line itself though, this is shadowing the original parameter by defining a new const over it. I'd rather we didn't do that as it's easily overlooked and can make it difficult to debug down the line once this is refactored enough. My preference would be to just pass `true` as the last argument to the `getCommitRangeDiff` call below. The comment above is clear enough about what's happening that we don't need the variable.

2022-06-01 12:45 UTC, niik commented on app/src/lib/git/diff.ts
> +import { git } from '.'
Let's import it straight from the file rather than the index to stay consistent with other imports. The index file is poorly maintained and I wonder if we shouldn't just get rid of it tbh.

```suggestion
import { git } from './core'
```

2022-06-01 12:54 UTC, niik approved these changes

2022-06-01 13:07 UTC, merged