Non contiguous multi commit selections
desktop/desktop pull request #14702
Opened 2022-05-31 18:40 UTC by tidy-dev

Builds on #14687

## Description
The underlying git command to do a multi-commit diff does so by comparing the last commit in a range to the parent of the first. Thus, a selection multiple commits that is not contiguous does not make sense in this context. This PR provides an updated multiple commit blank slate for that scenario. 

Also, I noticed that our blank screen doesn't mention the squashing/reordering but does cherry-picking. Seems like we should have that hint here too, but I will remove it if others disagree.

Other notes: From what I can tell, you may be able to finagle a "cherry-picked" diff view of non-contiguous commits by finding the files in the diffs of the individual commits and then doing the diff and limiting it to those files, but this would not be equivalent to one git command and may have other pitfalls (merged commits come to mind). Not worth exploring at this point.

### Screenshots
Before:
![Screen Shot 2022-05-31 at 2 32 40 PM](https://user-images.githubusercontent.com/75402236/171259667-27640853-db49-404e-88fd-66fddd1036c2.png)

After:
![Screen Shot 2022-05-31 at 2 28 11 PM](https://user-images.githubusercontent.com/75402236/171259187-20d1effa-37d5-411a-af65-8a63974a41b1.png)

## Release notes
Notes: no-notes

2022-05-31 18:42 UTC, tidy-dev commented on app/src/ui/history/selected-commit.tsx
> +              {enableMultiCommitDiffs() ? 'non-adjacent ' : ' '}commits are
This wording felt more common than `non-contiguous`; but completely open to feedback if there is a clearer way to communicate this. :)

2022-06-06 14:24 UTC, sergiou87 commented on app/src/ui/history/selected-commit.tsx
> +              {enableMultiCommitDiffs() ? 'non-adjacent ' : ' '}commits are
`non-adjacent` works for me, but `non-consecutive` feels more natural maybe (said the non-English speaker 😂 )

2022-06-06 14:26 UTC, tidy-dev commented on app/src/ui/history/selected-commit.tsx
> +              {enableMultiCommitDiffs() ? 'non-adjacent ' : ' '}commits are
I like that better!

2022-06-06 14:36 UTC, sergiou87 requested changes

2022-06-06 14:36 UTC, sergiou87 commented on app/src/ui/history/selected-commit.tsx
> +                {enableMultiCommitDiffs() ? 'or a range of commits ' : ' '}to
Should we mention the commits should be consecutive here?
```suggestion
                {enableMultiCommitDiffs() ? 'or a range of consecutive commits ' : ' '}to
```

2022-06-06 14:36 UTC, sergiou87 commented on app/src/ui/history/selected-commit.tsx
> +      return this.renderMultipleCommitsBlankSlate()
With that new condition, the new wording is gonna show up for users who make non-contiguous selection **even when the multi-commit diff feature flag is disabled**, right? 🤔 

We should probably make sure the feature flag is enabled inside of `renderMultipleCommitsBlankSlate` before showing the multi-commit stuff.

2022-06-06 14:39 UTC, tidy-dev commented on app/src/ui/history/selected-commit.tsx
> +      return this.renderMultipleCommitsBlankSlate()
Hmm.. I thought for sure I tested the dev flag on false..

2022-06-06 14:41 UTC, tidy-dev commented on app/src/ui/history/selected-commit.tsx
> +      return this.renderMultipleCommitsBlankSlate()
Feature flag false: 
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/75402236/172183645-792cb3b4-d2e6-4c25-be13-3641730de656.png">

2022-06-06 14:54 UTC, tidy-dev commented on app/src/ui/history/selected-commit.tsx
> +      return this.renderMultipleCommitsBlankSlate()
I think the logic is just confusing, 

It says, when feature flag is false, always render blank slate for multiple commits. But, only show non-contigous msg when feature flag is true.. because multiple commit blank slate only shows when feature flag is true if there are non-contiguous commits.

Or inversely, if feature flag is true, render blank slate only when selection is not contiguous.

2022-06-07 10:29 UTC, sergiou87 commented on app/src/ui/history/selected-commit.tsx
> +      return this.renderMultipleCommitsBlankSlate()
Ohhh you're right, my bad!

2022-06-07 10:32 UTC, sergiou87 approved these changes
Changes look good and works as expected! :shipit:

2022-06-07 12:25 UTC, merged

2026-09-09 05:03 UTC, q2wrr2dfmt-maker commented on app/src/ui/history/selected-commit.tsx
> -    const { selectedCommits } = this.props
ivy