Prevent virtualization of diff rows that are part of document selection
desktop/desktop pull request #15128
Opened 2022-08-17 12:45 UTC by niik

Closes #13701

## Description

The biggest reason why we haven't started experimenting with using the new diff engine (which powers side-by-side diffs) for unified diffs as well is that it doesn't play well with text selection.

The side-by-side diff component is built on a react-virtualized List which will only render into the DOM the lines that are currently visible plus a few extra to make scrolling feel smooth (this is called overscan, we'll get back to that in a bit). The problem with this is if you select outside of those visible lines the DOM rows get removed and the selection collapses to contain the visible nodes.

![Aug-17-2022 14-35-59](https://user-images.githubusercontent.com/634063/185126081-5a72376d-97c8-4763-aeb8-5ca056cf3581.gif)

Previously our thought on how to solve this was by virtualizing the selection as well so that any time the list was scrolled we would update the Selection API and have it appear as if the selection was there all along. Unfortunately that approach proved complex and produced odd artefacts when attempting to modify an active selection (i.e. modify the selection while the user is still dragging).

This PR instead takes a different, hackier, but less complex approach. When we detect that the whole, or parts of the diff is contained within the document selection we keep track of which row the selection "started" from and which row it "ends" on. When we know this we can increase the List overscan to not recycle those rows while scrolling. Effectively killing virtualization for the part of the diff which is selected. For small-ish files this is no biggie but it has performance impacts when for example attempting to select all text in a huge diff.

Judging by the issues we've received about this and my own gut feeling I suspect that the majority use-case here is selecting parts of a diff (or copying all of a smaller sized diff perhaps) that extend past the bounds of the window. Not copying multi-megabyte diffs.

## Release notes

Notes: [Fixed] Text selection is preserved while scrolling diffs in split mode

2022-08-19 14:09 UTC, sergiou87 requested changes
Looks good overall! I think it all makes sense, however when testing it, I found that `overscanIndicesGetter` wasn't being called on macOS when I pressed Cmd+A to select all (the `forceUpdate` method is called on the list, though 🤔 )

2022-08-19 14:09 UTC, sergiou87 commented on app/src/ui/diff/side-by-side-diff.tsx
> +    this.virtualListRef.current?.forceUpdate(() => {
Not sure why (I spent some time debugging but didn't find the cause), but this `forceUpdate` doesn't result in `overscanIndicesGetter` being invoked, so it doesn't overscan the remaining cells and therefore not all the content is copied 😕

2022-08-26 07:12 UTC, niik commented on app/src/ui/diff/side-by-side-diff.tsx
> +    this.virtualListRef.current?.forceUpdate(() => {
Fascinating. So the way I tested this was to hit Cmd+A and then scroll to verify that the selection extended to the end. I now see that it's the scrolling which forces the re-render and therefore the selection. So I'm guessing that the browser auto-extends the selection as we add in lines in-between the focus and anchor points. I'll take a look and see if we can trick it somehow.

2022-08-31 09:20 UTC, niik commented
@sergiou87 This is ready for another look. I tossed the idea of overscanning when selecting all as it just destroyed the performance. Instead I try to keep track of whether or not the entire diff is selected and hijack the copy event to fill it with the entire diff instead.

This got a little wonky when hitting Ctrl/Cmd+A outside of the diff since the selection API doesn't let us (easily) figure out what's copy-able and not so I made it such that text selection in the diff is disabled until it (or its descendants) are focused.

2022-08-31 11:31 UTC, sergiou87 approved these changes, later dismissed
The described changes make sense! I've tested it as thoroughly as I could and couldn't break it. It's nice to see that even when all text is selected, if you scroll, you see the virtualization going on but keeping every new row still selected! 👏 

Awesome work! :shipit:

2022-09-02 06:29 UTC, niik commented
@sergiou87 Can I bother you for a re-review after that merge conflict resolution?

2022-09-02 06:49 UTC, sergiou87 approved these changes
✨

2022-09-02 06:52 UTC, merged

2022-10-14 02:31 UTC, Gdub662 commented on app/src/ui/diff/side-by-side-diff.tsx
>    readonly repository: Repository
readonly repository: Repository