external editor applications for macOS: Add Emacs
desktop/desktop pull request #15130
Opened 2022-08-17 19:22 UTC by zipperer

This commit follows the steps to add an external editor for macOS (please see: https://github.com/desktop/desktop/blob/1b30bfb027aa0c522bf2d2c48122ce0d9c11e2e2/docs/technical/editor-integration.md).

```
machine:~ $ defaults read /Applications/Emacs.app/Contents/Info CFBundleIdentifier
org.gnu.Emacs
machine:~ $
```
I intend this addresses #4785 (https://github.com/desktop/desktop/issues/4785).

## Description
- add Emacs to list of external editor applications for macOS

2022-08-17 22:24 UTC, tsvetilian-ty requested changes

2022-08-17 22:24 UTC, tsvetilian-ty commented on docs/technical/editor-integration.md
> + - [Emacs] (https://www.gnu.org/software/emacs/)
@zipperer thanks for the PR. I tested it with the latest Emacs universal binary, and it works as expected 💯 
Just a small request to remove the space between the text and the link

```suggestion
 - [Emacs](https://www.gnu.org/software/emacs/)
```

2022-08-18 14:29 UTC, zipperer commented
> I intend this addresses https://github.com/desktop/desktop/issues/4785 (https://github.com/desktop/desktop/issues/4785).

It addresses the issue only for macOS. It does not address the issue for Windows or Linux.

2022-08-19 07:19 UTC, tsvetilian-ty approved these changes

2022-08-24 14:29 UTC, sergiou87 approved these changes
Looks good! Thank you 😄

2022-08-24 14:30 UTC, merged