Include renamed files in the commit summary changed files tooltip
desktop/desktop pull request #15165
Opened 2022-08-25 03:19 UTC by haykam821

Fixes #15155

### Screenshots

<img width="195" alt="Commit summary '61 changed files' text with tooltip listing three lines: '6 added', '54 modified', and '1 renamed'" src="https://user-images.githubusercontent.com/24855774/186566636-ada44ddb-e029-4e6b-b839-356c93563208.png">

### Release notes

Notes:

[Fixed] Include renamed files in the commit summary changed files tooltip

2022-08-25 03:41 UTC, Cervantes12 commented
Update to administration main management CEO owner

On Wed, Aug 24, 2022, 8:19 PM haykam821 ***@***.***> wrote:

> Fixes #15155 <https://github.com/desktop/desktop/issues/15155>
> Screenshots
>
> [image: Commit summary '61 changed files' text with tooltip listing three
> lines: '6 added', '54 modified', and '1 renamed']
> <https://user-images.githubusercontent.com/24855774/186566636-ada44ddb-e029-4e6b-b839-356c93563208.png>
> Release notes
>
> Notes:
>
> [Fixed] Include renamed files in the commit summary changed files tooltip
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/desktop/desktop/pull/15165
> Commit Summary
>
>    - cf3dab1
>    <https://github.com/desktop/desktop/pull/15165/commits/cf3dab13ad673cdebc61770c32376f2ac8e9a14d>
>    Include renamed files in the commit summary changed files tooltip
>
> File Changes
>
> (2 files <https://github.com/desktop/desktop/pull/15165/files>)
>
>    - *M* app/src/ui/history/commit-summary.tsx
>    <https://github.com/desktop/desktop/pull/15165/files#diff-861a5cca5e2af8df63c78ffe9b61ee7e11504d8d351b99e0014c812b4fc164a8>
>    (12)
>    - *M* app/styles/ui/window/_tooltips.scss
>    <https://github.com/desktop/desktop/pull/15165/files#diff-cfc9fcca4cb014018ab7c49c4f4a2ffea00fdb7841b2a6edad44fced443a7c0b>
>    (4)
>
> Patch Links:
>
>    - https://github.com/desktop/desktop/pull/15165.patch
>    - https://github.com/desktop/desktop/pull/15165.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/desktop/desktop/pull/15165>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2K7PTERA7IIZSLXV3PQBPLV23Q4VANCNFSM57RPGWRQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-08-29 12:58 UTC, tidy-dev submitted a review, later dismissed
@haykam821 This works great! I have one small ask in light of the ticket that originated this PR. Could you add a boolean that simply checks if any of the file kinds we are looking to describe exist? 

Something like:
```
const hasTooltip = check each type count > 0
const filesLongDescription = fileCount > 0 && hasToltip ? make content : undefined
(just pass filesLongDescription as the tooltip property)
```
I am pretty sure adding the rename will make it so we don't have the issue, but it would be nice to safe guard against unknown other scenarios and only show the tooltip if we know we have content to show.

2023-01-24 14:06 UTC, tidy-dev commented
@haykam821 Just checking back on this - would love to get it merged. Are you planning on addressing the requested change?

2023-01-27 15:45 UTC, sergiou87 requested changes

2023-01-27 15:45 UTC, sergiou87 commented on app/src/ui/history/commit-summary.tsx
> +      filesAdded + filesModified + filesRemoved + filesRemoved > 0
I think this should be…
```suggestion
      filesAdded + filesModified + filesRemoved + filesRenamed > 0
```

2023-01-27 16:05 UTC, sergiou87 approved these changes
Code LGTM and it works like a charm!

2023-01-27 16:15 UTC, merged