Option to disable discard stash popup
desktop/desktop pull request #15379
Opened 2022-09-28 14:51 UTC by tsvetilian-ty

Closes #15376

## Description
-  Add an option to the `Prompts` menu that lets the user pick if conformation before discarding stash is required 

### Screenshots
![discard-stash](https://user-images.githubusercontent.com/9341546/192811281-f90fc245-635c-46af-bb90-21536b8be981.gif)

2022-09-30 09:06 UTC, sergiou87 requested changes
Thank you for this @tsvetilian-ty !! However as other prompts, we'd like this one to have the usual "don't show this again" kind of checkbox, in addition to the setting you added.

2022-09-30 10:09 UTC, tsvetilian-ty commented
@sergiou87 I did the changes... somehow I forgot about that checkbox 😮

2022-10-04 16:47 UTC, sergiou87 requested changes
It works great! Only found a small typo (sorry about that nit 😅 ) but just correct that and I'll merge it right away 🚀 

Thanks again for your contribution! 🙇‍♂️

2022-10-04 16:47 UTC, sergiou87 commented on app/src/lib/app-state.ts
> +  /** Should the app propt the user to confirm a discard stash */
Nit:
```suggestion
  /** Should the app prompt the user to confirm a discard stash */
```

2022-10-05 07:15 UTC, sergiou87 approved these changes

2022-10-05 07:15 UTC, merged