Adding new levels in zooming
desktop/desktop pull request #15401
Opened 2022-10-02 11:14 UTC by sathvikrijo

Closes https://github.com/desktop/desktop/issues/4967
Closes https://github.com/desktop/desktop/issues/15380

## Description

- Github Desktop supported only zoom levels of 100%, 110%, 125%, 150%, 175% and 200%.
- And our loveable community requested for zoom levels below 100%. So I added some zoom out levels below 100%.
- Added new levels to get sync with **standard browser zoom levels, 25%, 33%, 50%, 75%, 80% and 90%**

### Screeenshots

![GithubDesktopZoomDemo (1)](https://user-images.githubusercontent.com/30945817/193450821-6bfc7423-c83b-4236-b317-064a7a7b2a12.gif)

## Release notes

Notes:
Added support for the 25%, 33%, 50%, 75%, 80% and 90% zoom levels.

2022-10-03 16:37 UTC, tidy-dev requested changes
@sathvikrijo Thanks you for submitting this improvement on zoom levels. It is looking great. 

However, one of the main reasons we chose not have zoom out originally was because not all are users use keyboard shortcuts and some navigate through the main menu items. If you zoom out too far, those menu items become practically illegible.

I did some testing and the menu seems to get hard to read around 50% with 67% still being pretty legible.  Could you remove the zoom factors below 67%?

67%
![image](https://user-images.githubusercontent.com/75402236/193631454-5f08997e-3360-4f5c-b5ac-af71710bfb29.png)


Also looks like the linter got you - probably line length and will clear up with removing those percentages. :)

2022-10-06 03:14 UTC, sathvikrijo commented
Yeah got it @tidy-dev. That makes sense 🙌 Will do it

2022-10-06 05:40 UTC, sathvikrijo commented
@tidy-dev Made the requested changes. Can you check now?

2022-10-06 14:08 UTC, tidy-dev approved these changes
✨  Looks good! Thanks for those changes!

2022-10-06 14:08 UTC, tidy-dev commented on app/src/main-process/menu/build-default-menu.ts
> +const ZoomInFactors = [0.25, 0.33, 0.5, 0.67, 0.75, 0.8, 0.9, 1, 1.1, 1.25, 1.5, 1.75, 2]
```suggestion
const ZoomInFactors = [0.67, 0.75, 0.8, 0.9, 1, 1.1, 1.25, 1.5, 1.75, 2]
```

2022-10-06 14:32 UTC, merged