Spyder support
desktop/desktop pull request #15542
Opened 2022-10-30 21:59 UTC by davidlloyduk

Closes #15492

## Description

 - added windows support via additional shellArgs passing to spawn function
 - added mac support via https://github.com/desktop/desktop/pull/15505

### Screenshots

## Release notes

Notes: Adds support for Spyder IDE integration

2022-10-30 22:22 UTC, davidlloyduk commented on app/src/lib/editors/launch.ts
> +    const args = editor.shellArgs ? editor.shellArgs?.map(arg => `"${arg}"`) : []
have assumed here that all arguments are paths, will need to rethink this as arguments maybe other things e.g integer - might have to wrap them when they are defined.

2022-10-30 22:29 UTC, davidlloyduk commented on app/src/lib/editors/darwin.ts
> +    name: 'Spyder',
happy to remove this if you wish to use [PR 15505](https://github.com/desktop/desktop/pull/15505)

2022-11-07 06:27 UTC, sergiou87 requested changes
Thank you for your contribution! This makes total sense to me 😄 

Only found one thing that could be simplified, once that's fixed I'll try it out and merge it if all goes well.

2022-11-07 06:27 UTC, sergiou87 commented on app/src/lib/editors/launch.ts
> +    const args = editor.shellArgs ? editor.shellArgs : []
This can be simplified as:
```suggestion
    const args = editor.shellArgs ?? []
```

2022-11-07 07:12 UTC, sergiou87 commented
@davidlloyduk seems like you need to fix linting. I think you can use `yarn lint:fix` from the terminal and it will fix the source files affected.

2022-11-07 08:21 UTC, davidlloyduk commented
Will sort out the linting! Thanks

2022-11-07 08:31 UTC, ChadMichaelSheda commented
Thanks go for it

2022-11-07 08:43 UTC, davidlloyduk commented on app/src/lib/editors/launch.ts
> +    const args = editor.shellArgs ? editor.shellArgs : []
sorted in last commit

2022-11-08 12:50 UTC, sergiou87 requested changes
On Windows at least, this seems to work for individual files, but not to open the whole repository, where I get this error:

![image](https://user-images.githubusercontent.com/1083228/200568001-11283616-d9bf-498f-bdf1-843c905e6b8c.png)

Also, I wasn't able to run it on macOS at all. I cannot open Spyder independently either 😞  Could you maybe record a video of it working? (Opening both individual files and a whole repository)

Thanks!

2022-11-08 13:16 UTC, davidlloyduk commented
> On Windows at least, this seems to work for individual files, but not to open the whole repository, where I get this error:
> 
> ![image](https://user-images.githubusercontent.com/1083228/200568001-11283616-d9bf-498f-bdf1-843c905e6b8c.png)
> 
> Also, I wasn't able to run it on macOS at all. I cannot open Spyder independently either 😞 Could you maybe record a video of it working? (Opening both individual files and a whole repository)
> 
> Thanks!

will investigate and sort out the directory thing, bah to the mac thing - copied it from that other guys PR - will fire up a vm and test the mac

2023-04-13 06:58 UTC, niik commented
Hey @davidlloyduk, since we haven't heard from you in a while and since this PR has gone stale with conflicts I'm going to close this out to keep our PR list somewhat manageable. If you get back to this feel free to open a new PR!

2023-04-13 06:58 UTC, closed without merging

2024-10-02 16:49 UTC, TessaNM commented
![200568001-11283616-d9bf-498f-bdf1-843c905e6b8c](https://github.com/user-attachments/assets/f5892ec4-56de-42c4-9d56-afa3cc17a570)
In Github desktop you have to include spyder -p in the arguments box (before %TARGET_PATH%) after specifying the path to Spyder IDE - I was able to open the repository in Spyder IDE when I did that.