Update RStudio publisher to fix integration
desktop/desktop pull request #15813
Opened 2022-12-21 21:47 UTC by steveward

Closes #15810 

## Description

- Update publisher from 'RStudio' to 'Posit Software' to fix the RStudio integration
- Tested this in a dev build on Windows and confirmed it fixed the integration

### Screenshots

## Release notes
No notes

2022-12-21 22:17 UTC, Mar181-arc reviewed
Leave a rewiev

2022-12-26 21:39 UTC, tidy-dev approved these changes, later dismissed

2023-01-04 13:06 UTC, sergiou87 commented
Won't this change break compatibility with older versions? Maybe we need a new whole entry that duplicates everything and only changes the publisher (either that or allowing multiple publishers per entry 🤔 )

2023-01-20 12:37 UTC, sergiou87 requested changes

2023-01-20 12:37 UTC, sergiou87 commented on app/src/lib/editors/win32.ts
> +    publisher: 'Posit Software',
After @voidei 's work in #15585 we can just have multiple publishers, which should solve this problem! 🎉  😄 

```suggestion
    publishers: ['RStudio', 'Posit Software'],
```

2023-01-24 15:13 UTC, steveward commented
Thanks @sergiou87, I should've thought of that! 😅

2023-01-26 06:10 UTC, Mortezaegoe commented
> ssaaa[]() 

> ``

2023-01-26 06:10 UTC, Mortezaegoe commented
R

2023-01-26 09:23 UTC, sergiou87 approved these changes
Thanks for that change! It works like a charm with both new and old versions 🙌

2023-01-26 09:23 UTC, merged

2023-02-16 15:32 UTC, ars17psu commented
I have R Studio 2022.12.0+353 and R 4.2.2 GUI 1.79 High Sierra build running on a Mac with MacOS Ventura. An option to open RStudio or Posit Software is not available in GitHub Desktop Version 3.1.6 (x64) or Version 3.1.7 (x64). Any assistance you can provide would be much appreciated.