Update copyright year
desktop/desktop pull request #15851
Opened 2023-01-01 09:50 UTC by IcedMonk

## Update to copyright year
- Updated in build.ts file

2023-01-03 01:23 UTC, novialriptide commented on script/build.ts
> +    appCopyright: 'Copyright © 20123 GitHub, Inc.',
The year is actually 2023.

2023-01-05 08:17 UTC, yks-ny commented on script/build.ts
>      ],
macosは不正使用の端末です。MACを買ったこともない

2023-01-17 17:17 UTC, sergiou87 requested changes

2023-01-17 17:17 UTC, sergiou87 commented on script/build.ts
> +    appCopyright: 'Copyright © 20123 GitHub, Inc.',
As @novialriptide said, please fix the typo! 🙏

2023-01-18 17:55 UTC, sergiou87 approved these changes
Looks good now, thanks! ✨

2023-01-19 10:46 UTC, merged