Add some IDEs from JetBrains Toolbox to Linux
desktop/desktop pull request #16029
Opened 2023-01-29 20:28 UTC by adil192

## Description

I've added the non-snap locations of PhpStorm and WebStorm, and I've also added IntelliJ IDEA, PyCharm and Android Studio.

I'm not sure about the snap locations but I've added them in for completeness. If I should remove them, let me know :)

## Release notes

Notes: Added editors installed with JetBrains Toolbox on Linux

2023-02-02 11:44 UTC, sergiou87 approved these changes
Thanks for your contribution!

2023-02-02 11:58 UTC, sergiou87 requested changes
There are linter issues :( Please fix them (`yarn lint:fix` should do it for you) and I'll trigger the CI jobs again

2023-02-08 09:03 UTC, sergiou87 approved these changes

2023-02-08 09:03 UTC, merged

2023-04-27 22:35 UTC, jordan4ibanez commented
I've read through this, and I still cannot get IntelliJ to show up. I've installed a desktop entry as both privileged and unprivileged and it still does not show up as an option. :(