JetBrains DataSpell support on Windows
desktop/desktop pull request #16031
Opened 2023-01-29 22:52 UTC by tsvetilian-ty

Closes #16020

## Description
- Support for JetBrains DataSpell on Windows

2023-02-08 17:28 UTC, tidy-dev commented on docs/technical/editor-integration.md
> + - [JetBrains DataSpell](https://www.jetbrains.com/dataspell/)
```suggestion
```

This is not supported on macOS yet.

2023-02-08 17:30 UTC, tidy-dev requested changes
@tsvetilian-ty Thanks for the integration PR!

I tested on windows and it worked great!

I wasn't going to test on macOS since the PR title indicates this is just for Windows. However, then saw the add to the macOS list in the readme and reviewed macOs integrations and didn't see it. Also tested and it is not added. 

Thus, please either remove the macOS list add or add macOS integration. :)

2023-02-09 10:49 UTC, tsvetilian-ty commented
@tidy-dev my bad I had to link to the macOS implementation and give more information in my PR. There is a PR with macOS implementation: https://github.com/desktop/desktop/pull/16021, the PR doesn't contain an update to the list, so when I added the Windows integration, I also updated the list for both platforms.

Maybe you could check https://github.com/desktop/desktop/pull/16021 firsts and then merge my PR?

2023-02-09 14:33 UTC, tidy-dev commented
Ah! I didn't see that. Thank you for pointing it out, I will test it and leave this one be. :)

2023-02-09 15:15 UTC, tidy-dev approved these changes
Looks great! Thanks for pointing out the other PR - Tested and merged so this ready. :)

2023-02-09 15:16 UTC, merged