Invoking Context Menu from ListRow component
desktop/desktop pull request #16114
Opened 2023-02-10 19:25 UTC by tidy-dev

## Description
This PR refactor the callback of `onContextMenu` to be on the focus div element of each row of the changes list. That is the div in the `<ListRow>` component. The reason being is that the keyboard shortcuts (i.e. Shift + F10 on Windows and VO "VoiceOver" + Shift + M on MacOS) to invoke a context menu will only do so for the focused div which for a selectable list item is the one with the role of `option`

### Screenshots

## Release notes
Notes: [Improved] The context menu for a file in changed files list can be invoked by keyboard shortcuts.

2023-02-16 20:07 UTC, tidy-dev commented
After much trial by error.. I stumbled upon the fact that @niik changes in https://github.com/desktop/desktop/pull/16108 solved the problem when I went to start simplying the Grid rendering to see what thing could be impacting it and I applied some of @niik's changes and it just worked! I can't really explain why.. I am assuming something about roles where impacting this. :/

2023-02-17 12:13 UTC, niik requested changes
One tiny request

2023-02-17 12:13 UTC, niik commented on app/src/ui/lib/list/list-row.tsx
> +    console.log(e.currentTarget)
Can we get rid of these please?
```suggestion
```

2023-02-17 12:13 UTC, tidy-dev commented on app/src/ui/lib/list/list-row.tsx
> +    console.log(e.currentTarget)
Woops.. Absolutely..

2023-02-17 12:14 UTC, niik approved these changes

2023-02-17 12:37 UTC, merged