Improved display of Keyboard shortcuts
desktop/desktop pull request #16570
Opened 2023-04-20 16:05 UTC by yasuking0304

- Put a "+" between keyboard shortcuts on the No local Changes page for Windows
- Put a "+" between keyboard shortcuts on the Tutorial page for Windows
- Exclude a "+" between keyboard shortcuts on the No changes page for Mac OS

Closes #16549

## Description

- MacOS,
  Exclude '+' between keys
- Else OS,
  Add '+' between keys

### Screenshots
Mac OS
![スクリーンショット 2023-04-19 22 50 44](https://user-images.githubusercontent.com/111163564/233098069-7a34fa8d-cc65-460d-bada-337a77c6471a.png)

Windows
![WS000004](https://user-images.githubusercontent.com/111163564/233419695-cac3736d-8062-4b5b-a60e-501c799ae3dc.JPG)

## Release notes

Notes:

2023-04-21 07:59 UTC, sergiou87 reviewed
Thank you for your contribution!!

I think it'd be nice to have custom component for shortcuts that already took care of all that for us, so we don't make those mistakes. I'm thinking something like this:

```tsx
<KeyboardShortcut darwinKeys={['⌘', '⇧', 'N']} windowsKeys={['Control', 'Shift', 'N']} />
```

That will generate the necessary `<kbd>...</kbd>` elements and add (or not) a `+` in between depending on the platform.

What do you think? 😄

2023-04-23 05:40 UTC, yasuking0304 commented
I fixed. (Add KeyboardShortcut custom component)

2023-04-24 08:58 UTC, sergiou87 requested changes
This is so good!! Thank you @yasuking0304 ❤️ 

Only found a few things we'd like to change before merging it.

2023-04-24 08:58 UTC, sergiou87 commented on app/src/ui/changes/no-changes.tsx
> -
I think it'd be less changes and more reused code if you kept this function around with this implementation:
```tsx
  private renderDiscoverabilityKeyboardShortcut(menuItem: IMenuItemInfo) {
    return <KeyboardShortcut
             darwinKeys={menuItemInfo.acceleratorKeys}
             keys={menuItemInfo.acceleratorKeys}
           />
  }
```

Then you can get rid of `getMenuShortcut` and revert the rest of changes in this file.

2023-04-24 08:58 UTC, sergiou87 commented on app/src/ui/window/full-screen-info.tsx
> +          exit fullscreen
One key is missing for macOS:

```suggestion
          Press <KeyboardShortcut darwinKeys={['^', '⌘', 'F']} keys={['F11']} />{' '}
          to exit fullscreen
```

2023-04-24 08:58 UTC, sergiou87 commented on app/src/ui/keyboard-shortcut/keyboard-shortcut.tsx
> +    }
I think this is a bit cleaner, and I also added spaces around the + as we had before this PR:
```suggestion
    const keys = __DARWIN__ ? this.props.darwinKeys : this.props.keys

    return keys.map((k, i) => {
      return (
        <>
          <kbd key={k + i}>{k}</kbd>
          {!__DARWIN__ && i < keys.length - 1 ? <> + </> : null}
        </>
      )
    })
```

2023-04-24 17:30 UTC, yasuking0304 commented on app/src/ui/changes/no-changes.tsx
> -
I fixed.

2023-04-26 17:30 UTC, sergiou87 commented on app/src/ui/keyboard-shortcut/keyboard-shortcut.tsx
> +          {!__DARWIN__ && i < keys.length - 1 ? <> + </> : null}
Sorry, my bad, I discussed it with the team and prefer it without the spaces around. Other than that is looking great!!!
```suggestion
          {!__DARWIN__ && i < keys.length - 1 ? <>+</> : null}
```

2023-04-26 17:31 UTC, sergiou87 commented on app/src/ui/keyboard-shortcut/keyboard-shortcut.tsx
> +          {!__DARWIN__ && i < keys.length - 1 ? <> + </> : null}
I made the change myself from the suggestion. I will test this tomorrow and if everything is ok I will go ahead and merge it 😄

2023-04-27 07:09 UTC, sergiou87 approved these changes
I had to make a [small change](https://github.com/desktop/desktop/pull/16570/commits/77fe50458b4e24a8ecdbe8b863a80aa98eb16c8b) to make it look Good™ on Windows/Linux but other than that works like a charm! Thanks for your contribution 😄 💖

2023-04-27 07:13 UTC, merged