Remove custom message when loading pull requests
desktop/desktop pull request #16580
Opened 2023-04-22 04:40 UTC by samuelko123

Closes #7492

## Description
- The issue is caused by rendering a custom message "Loading pull requests as fast as I can!" for empty result list.
- No custom message is rendered for non-empty result list is.
- Therefore, the fix is to remove the custom message.
- The existing spinning "refresh" icon has provided sufficient visual indicator.

### Screenshots

Before:
![before](https://user-images.githubusercontent.com/91960206/233762840-18ccb05a-7ef9-4faa-ac32-944d78d17a92.gif)

After:
![after](https://user-images.githubusercontent.com/91960206/233762845-a2e22aa3-a817-4a99-9235-25c422abf142.gif)

## Release notes

Notes: no-notes

2023-04-22 09:02 UTC, battsteam commented on app/src/ui/branches/no-pull-requests.tsx
>        return (
Batts sign

2023-04-24 09:28 UTC, sergiou87 requested changes
Hey @samuelko123 👋 

Thank you for this PR, but I'm not sure this approach is the best: it also removes the loading text in other situations where it makes more sense.

I think we should either:
1. Delay when that text is shown (i.e. only show it if the request takes longer than X milliseconds)
2. Set a minimum time to show the message (i.e. keep the loading message visible for at least X milliseconds)
3. Consider this not an issue or just "won't fix"

Personally I'm inclined to go with (3) as:
- (1) could still reproduce the problem if we make the loading message wait for, let's say, 250ms and the request takes 255ms to complete.
- (2) would make users wait for nothing in some cases
- Both (1) and (2) introduce some (small, but still some) complexity
- In general this is not a big issue so I don't think it deserves our time 😄 

I hope you agree, so I'm gonna close both the PR and the issue. Sorry about that and thank you anyway 🙇‍♂️

2023-04-24 09:29 UTC, closed without merging

2023-04-24 10:26 UTC, samuelko123 commented
Although I don't believe there are "other situations" involved in this case, I respect your decision of closing it.
Thank you for spending the time to explain your thoughts. 😄

2023-05-04 16:25 UTC, angusdev commented
I think it shouldn't show the "Sorry, I can't find the pull request!" when loading