Warn before deleting branch with unmerged/unpushed commits
desktop/desktop pull request #16596
Opened 2023-04-25 01:52 UTC by samuelko123

Closes #4214

## Description
- It addresses the 3 cases [here](https://github.com/desktop/desktop/pull/4217#issuecomment-372131743).
- It shows a `Loader` and runs `git fetch` if remote branch exists, because we want the latest data.
- The `Loader` deliberately blocks the action buttons, because we don't want users to make uninformed decision.

## Discussion
- One potential improvement is to create "Don't show delete branch warning" setting, so user can choose not to run `git fetch`.
- Another potential improvement is the "Unmerged commits" warning message
  - It refers to the number of commits ahead of the default branch, but the branch could've been merged to another branch.
  - It's too expensive to check every commit against every branch.
  - Maybe a better message could help, something like "Warning: `origin/test_branch` has 1 commit that does not exist in `origin/main`". But I feel it's a bit too verbose.

## Test steps
1. Create new branch
2. Try to delete branch, get screenshot No. 1
3. Create changes without committing
4. Try to delete branch, get screenshot No. 1
5. Commit the changes
6. Try to delete branch, get screenshot No. 2
7. Push changes (implicitly create remote branch)
8. Try to delete branch, get screenshot No. 3
9. Create another commit locally
10. Try to delete branch, get screenshot No. 4
11. Merge the remote changes
12. Try to delete branch, get screenshot No. 5

### Screenshots

1.
![image](https://user-images.githubusercontent.com/91960206/234149619-d8ef9fdb-cdd7-463f-8f76-bdef2586cfcf.png)

2.
![image](https://user-images.githubusercontent.com/91960206/234149664-667a4866-97a3-4b5c-bbf6-f4f53badb0ca.png)

3.
![image](https://user-images.githubusercontent.com/91960206/234149819-57e88071-2b38-4218-92a8-5219c7ae0a32.png)

4.
![image](https://user-images.githubusercontent.com/91960206/234149873-6c8572c7-105d-43e5-a21b-d57c82e43f63.png)

5.
![image](https://user-images.githubusercontent.com/91960206/234149905-c91b2162-c294-4c24-a057-5d76d0022297.png)

6. `git fetch` loading
![image](https://user-images.githubusercontent.com/91960206/234149705-bc8dc553-83b6-421e-b925-b80a0476b017.png)

## Release notes

Notes: [Improved] Warn before deleting branch with unmerged/unpushed commits

2023-08-07 11:41 UTC, iStoreJaber reviewed
Test

2023-08-07 19:11 UTC, tidy-dev requested changes
@samuelko123 I apologize for the long wait on a reply. We briefly discussed this today and we are concerned about the use of fetch. We like the feature, however, fetch, unfortunately, can be an expensive operation for some users and triggers the authentication flow thus could cause authentication requirements for users with shorter authentication cycles. Thus, making the delete branch dialog confirmation really heavy for what we do not view as worth the cost. Because of this, we do not want to move forward with this PR as is. However, if you would like to remove the portion that relies on fetch call. We could take another look. Thank you for making GitHub Desktop better. :) 

Note: If we don't hear back from you soon, we will close it out.

2023-08-07 23:17 UTC, samuelko123-bunnings commented
Hi @tidy-dev , thanks for replying.

In this PR, under the "Discussion" section, there is a suggestion of creating a setting for users to decide whether to fetch or not, and I assume you have read and decided it is not a good idea.

Anyway, I have removed the `git fetch` portion from this PR. Hope it can eventually be merged and benefit users to a certain extent.

Thanks for reviewing.

2023-08-07 23:21 UTC, samuelko123 commented
Hi @tidy-dev  , thanks for replying.

In this PR, under the "Discussion" section, there is a suggestion of creating a setting for users to decide whether to fetch or not, and I assume you have read and decided it is not a good idea.

Anyway, I have removed the `git fetch` portion from this PR. Hope it can eventually be merged and benefit users to a certain extent.

Thanks for reviewing.

2023-08-07 23:30 UTC, samuelko123 commented on app/src/lib/remote-parsing.ts
> +    regex: new RegExp('^(?:.+)@(.+.ghe.com):([^/]+)/([^/]+?)(?:/|.git)?$'),
I accidentally pushed a merge commit, which caused this warning.
I've force-pushed to remove this merge commit.

2023-09-20 13:01 UTC, tidy-dev requested changes
@samuelko123 Sorry for taking so long to circle back. Thank you for removing the fetch logic and you are correct at this time, we do not want to consider adding adding a setting to allow fetching here. 

Some concerns:
- For accessibility, particularly screen reader users, this dialog is an `alertdialog` and any content in it needs to be referenced in the `ariaDescribedBy` of the dialog. Currently, all the warnings added are not included. You could rectify this by placing them all inside a div and adding the `id` of that div to the `ariaDescribedBy` making sure the order of the id's reflects the order they are rendered. Similarly, the 'delete-branch-confirmation-message-remote` id is being removed and we would like to keep it.
- The warnings that say "This branch has x unmerged commits" does not reference to what it is comparing to. We do have users that create branches off of branches other than the default. Suggest that we add make it "This branch has x unmerged commits when compared to `{defaultBranch.name}`" . Similarly for remove ahead but use defaultBranch.upstream.

2023-09-20 13:03 UTC, tidy-dev commented on app/src/ui/delete-branch/delete-branch-dialog.tsx
> +          {unmergedCommits === 1 ? 'commit' : 'commits'}.
```suggestion
          {unmergedCommits === 1 ? 'commit' : 'commits'} when compared to <Ref>{this.props.defaultBranch.name}</Ref>.
```

^ May cause linting error.. this is just a suggestion to communicate requested change.. needed tested. :)

2023-09-20 13:04 UTC, tidy-dev commented on app/src/ui/delete-branch/delete-branch-dialog.tsx
> +          unmerged {unmergedCommits === 1 ? 'commit' : 'commits'}.
```suggestion
          unmerged {unmergedCommits === 1 ? 'commit' : 'commits'}  when compared to <Ref>{this.props.defaultBranch.upstream}</Ref>.
```

^ May cause linting error.. this is just a suggestion to communicate requested change.. needed tested. :)

2023-09-20 13:05 UTC, tidy-dev commented on app/src/ui/delete-branch/delete-branch-dialog.tsx
> +          <p>
```suggestion
          <p id="delete-branch-confirmation-message-remote">
```
Need to keep for the alert dialog to announce this.

2023-09-24 00:55 UTC, samuelko123 commented
@tidy-dev Thanks for commenting on this PR. The comments are implemented and tested.
My apology for force-pushing because I accidentally used my work email in VS Code.
(It'll be great if Github Desktop can allow multiple email accounts. 😃 )

2024-04-18 12:05 UTC, sergiou87 requested changes
Sorry @samuelko123 it took us this long to get back to you. After our recent accessibility work, I see some extra changes needed in this PR:
- First I'd recommend to update your branch with the latest `development` commit.
- Second, we have removed `br` elements (as you can see in #18444 and #18436)
- Finally, the new added chunks of text should have an `id` in their `div` element, and then that `id` should be added to the `ariaDescribedBy` attribute of the dialog (there is an example of this in the file already)

Thank you for your patience!

2024-04-19 13:26 UTC, samuelko123 commented
@sergiou87 @tidy-dev 

Thank you for your detailed PR reviews.

I use Github Desktop everyday at work. It’s an awesome software and I wished to help make it better. Unfortunately, my passion and patience on this repo have been eroded over the year.

I fully understand the constraints of resources and prioritisation. There’s nothing personal.

I’ll close this PR for now. Anyone who’s interested could freely use any code within this PR to continue the journey.

Stay safe. 😄

2024-04-19 13:26 UTC, closed without merging