More Autocomplete accessibility improvements
desktop/desktop pull request #16608
Opened 2023-04-27 11:36 UTC by sergiou87

xref. https://github.com/github/accessibility-audits/issues/3249

## Description
This PR has these 3 changes:
- Make sure autocomplete containers from all the `AutocompletingTextInput` components present simultaneously in the DOM have different IDs.
- Set `role="combobox"` to all `AutocompletingTextInput` components
- Add an invisible screen reader-only `label` to `AutocompletingTextInput`.

## Release notes

Notes: no-notes

2023-05-01 15:15 UTC, tidy-dev requested changes
This all make sense. However, we have and method `createUniqueId` in the `id-pool.ts` for creating unique ids for html elements that has some built in sanitization and ensuring uniquess.  Using this does require also using the `releaseUniqueId` method to be able to maintain uniqueness checking. The dialog components `titleId` is a good example of it.  I believe we use it in most places we generate ids for html elements so seems like it would make sense here.

2023-05-03 16:02 UTC, sergiou87 commented
Ohhhh that's awesome, I was looking for something like that. I will make the change, thank you! :_D

2023-05-03 16:24 UTC, sergiou87 commented
I think that should be it, so far it works as expected 🤞

2023-05-04 10:49 UTC, tidy-dev approved these changes
✨ Great. Works as expected.

2023-05-04 11:57 UTC, merged