Improve accessibility of refreshing pull requests
desktop/desktop pull request #17031
Opened 2023-07-05 15:24 UTC by sergiou87

xref. https://github.com/github/accessibility-audits/issues/4342
xref. https://github.com/github/accessibility-audits/issues/4065

## Description

This PR helps assistive technologies to give users feedback about the state of refreshing pull requests when users click on the refresh button in the PR list.

I took the chance to give the refresh button an `aria-label` (VoiceOver would read just `button` when it was focused) and the same to the refresh button in the "Clone repo" dialog.

## Release notes

Notes: [Improved] Screen readers announce number of pull requests found after refreshing the list

2023-07-07 18:57 UTC, tidy-dev requested changes
When testing it out, if I clicked on it more than once it often didn't announce the results again. Since the `AriaLiveContainer` only appends the suffix when the tracked user input changes, it will not toggle that for every render.

However, I think there is a better way than trying to force the `AriaLiveContainer` to work here and that is to provide a loading message so that it is naturally toggled between loading and results. I think this is particularly important in the case of no pull requests where a visual user even gets  the message of "Hang tight. Loading pull requests as fast as I can!".

I tested replicating the logic from the `componentDidUpdate` in the `push-pull-button.tsx` really quick (tho inverted since we are using the componentWillReceive Props) and it made it so it did announce the results every time.

I personally like reusing the same loading message so that the screen reader user gets the same experience as the visual user. However.. in a case where there are existing pull requests (which is probably more than not?), it seems a little verbose. Thus, I will leave it up to you as to whether you think it should just say "Loading pull requests" instead. 

```
const loadingStarted =
      !this.props.isLoadingPullRequests && nextProps.isLoadingPullRequests
    const loadingComplete =
      this.props.isLoadingPullRequests && !nextProps.isLoadingPullRequests
    const numPullRequests = this.props.pullRequests.length
    const plural = numPullRequests === 1 ? '' : 's'
    const screenReaderStateMessage = loadingStarted
      ? 'Hang Tight. Loading pull requests as fast as I can!'
      : loadingComplete
      ? `${numPullRequests} pull request${plural} found`
      : null
```

2023-07-10 14:45 UTC, sergiou87 commented
I love that approach and it works great! Thanks 🙇‍♂️

2023-07-10 18:02 UTC, Miniiii1989 commented
> xref. https://github.com/github/accessibility-audits/issues/4342
> xref. https://github.com/github/accessibility-audits/issues/4065
> 
> ## Description
> 
> This PR helps assistive technologies to give users feedback about the state of refreshing pull requests when users click on the refresh button in the PR list.
> 
> I took the chance to give the refresh button an `aria-label` (VoiceOver would read just `button` when it was focused) and the same to the refresh button in the "Clone repo" dialog.
> 
> ## Release notes
> 
> Notes: [Improved] Screen readers announce number of pull requests found after refreshing the list
>

2023-07-10 18:10 UTC, minimayki6232 commented
در تاریخ جمعه ۷ ژوئیهٔ ۲۰۲۳،‏ ۲۲:۲۸ tidy-dev ***@***.***>
نوشت:

> ***@***.**** requested changes on this pull request.
>
> When testing it out, if I clicked on it more than once it often didn't
> announce the results again. Since the AriaLiveContainer only appends the
> suffix when the tracked user input changes, it will not toggle that for
> every render.
>
> However, I think there is a better way than trying to force the
> AriaLiveContainer to work here and that is to provide a loading message
> so that it is naturally toggled between loading and results. I think this
> is particularly important in the case of no pull requests where a visual
> user even gets the message of "Hang tight. Loading pull requests as fast as
> I can!".
>
> I tested replicating the logic from the componentDidUpdate in the
> push-pull-button.tsx really quick (tho inverted since we are using the
> componentWillReceive Props) and it made it so it did announce the results
> every time.
>
> I personally like reusing the same loading message so that the screen
> reader user gets the same experience as the visual user. However.. in a
> case where there are existing pull requests (which is probably more than
> not?), it seems a little verbose. Thus, I will leave it up to you as to
> whether you think it should just say "Loading pull requests" instead.
>
> const loadingStarted =
>       !this.props.isLoadingPullRequests && nextProps.isLoadingPullRequests
>     const loadingComplete =
>       this.props.isLoadingPullRequests && !nextProps.isLoadingPullRequests
>     const numPullRequests = this.props.pullRequests.length
>     const plural = numPullRequests === 1 ? '' : 's'
>     const screenReaderStateMessage = loadingStarted
>       ? 'Hang Tight. Loading pull requests as fast as I can!'
>       : loadingComplete
>       ? `${numPullRequests} pull request${plural} found`
>       : null
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/desktop/desktop/pull/17031#pullrequestreview-1519596992>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7RUZ2PTNV2TG42WSLUT6XLXPBL3ZANCNFSM6AAAAAAZ7DYTXE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-07-19 18:43 UTC, tidy-dev approved these changes
✨  Thank you for those changes!

2023-07-19 18:43 UTC, merged