Update win32.ts
desktop/desktop pull request #17078
Opened 2023-07-16 05:03 UTC by voidei

## Description

- Swap `displayNamePrefix` from `string `to `string[]`
- Create function to test `string.startswith `against strings array
- Change `editor.displayNamePrefix.startswith(display)` to aforementioned new function

## Release notes

Notes: Minor changes to editor detection and fixed detection of VSCodium Insiders for Windows

2023-07-30 07:58 UTC, sergiou87 requested changes
Thanks for your contribution! 💖 

Would you mind explaining in the PR description what changed in VSCodium Insiders display name to require/justify these changes?

2023-07-30 07:58 UTC, sergiou87 commented on app/src/lib/editors/win32.ts
> +  readonly displayNamePrefix: string[]
This should be `displayNamePrefixes` now

2023-07-30 08:40 UTC, voidei commented
@sergiou87 Changes made were so that both the new and old VSCodium Insiders could be detected, as despite fixing most issues in #15585 the user install of insiders had a different display name; as for the new funtion added, I did it so `displayNamePrefixes` could remain as a prefix, rather than matching the entire string - largely due to VSCodium Insiders' display name having "Insiders" in parenthesis on the old version, and without them in the new.

2023-08-03 07:55 UTC, sergiou87 approved these changes
Looks good and works as expected, thank you!

2023-08-03 07:55 UTC, merged