Improve dark theme link color contrast
desktop/desktop pull request #17092
Opened 2023-07-19 16:07 UTC by jacortinas

Issues:
- https://github.com/github/accessibility-audits/issues/4338

## Description
This PR changes the color of all links from the existing `$blue-400`(`#2188ff`) to `$blue-300`(`#79b8ff`). Given that most links in the Desktop app are on the same background color, they most likely all suffer from contrast ratio issues.

I did experiment with using the color that github.com uses for links from the dark and dark dimmed themes, however using those doesn't yield the full AAA contrast on the Desktop app's background color. Given that the links within the app are relatively small, I think it makes sense to overshoot what github.com is using and go with `$blue-300` for full AAA contrast.

| Before | After |
| ------ | ------ |
|  ![Screenshot 2023-07-19 at 10 48 58 AM](https://github.com/desktop/desktop/assets/171215/89e7f9c1-9c52-4a73-9611-70c23b99143c) | ![Screenshot 2023-07-19 at 10 49 24 AM](https://github.com/desktop/desktop/assets/171215/4fe3f821-7e2f-4faf-9143-2b1be56cb334) |

### Screenshots

| Default | Hover | Focused |
| ------ | ------ | ------ |
| <img width="159" alt="Screenshot 2023-07-18 at 11 46 35 AM" src="https://github.com/desktop/desktop/assets/171215/3ef41114-33a1-4ac7-9ed1-c0fc3f119a22"> | <img width="168" alt="Screenshot 2023-07-18 at 11 46 40 AM" src="https://github.com/desktop/desktop/assets/171215/1a7e37cd-71d0-494f-b564-64c7077bb01b"> | <img width="155" alt="Screenshot 2023-07-18 at 11 47 00 AM" src="https://github.com/desktop/desktop/assets/171215/9fefb024-67b1-445b-8957-2a64057ddb7f"> |

![Screenshot 2023-07-19 at 11 04 17 AM](https://github.com/desktop/desktop/assets/171215/db4ed275-1ea8-4989-b384-47215388dce0)

![Screenshot 2023-07-19 at 11 04 11 AM](https://github.com/desktop/desktop/assets/171215/549420c8-ceb9-40ea-b3ca-588ef02c4881)

![Screenshot 2023-07-19 at 11 04 06 AM](https://github.com/desktop/desktop/assets/171215/ae18abab-6e0d-4490-b9f0-ea7a0ad128c9)

## Release notes

Notes: [Improved] Improve contrast of all links when using the dark theme.

2023-07-19 19:47 UTC, tidy-dev requested changes
Ok. Somewhat right direction. 😃 

This is a really tricky one. I am having a hard to easily finding a blue color that works. Because we need two criteria met:
1. The link to foreground to be 4.5. (That you have met easily with your 7.1)
2. The link needs to be 3.1 to surrounding text... unfortunately lightening the color gets it closer in colour to the white text that surrounds it. 

![CleanShot 2023-07-19 at 15 44 54](https://github.com/desktop/desktop/assets/75402236/7bc53b51-1d18-44cd-9b3b-cb7ceb78272c)

I think we are probably going to have to choose a custom blue color that has a different saturation point.


Also, I think the 3.1 isn't met in light mode either.

2023-07-19 19:52 UTC, tidy-dev commented
Helpful website for link contrast checking.
https://webaim.org/resources/linkcontrastchecker/

2023-07-24 13:51 UTC, tidy-dev requested changes
Awesome! Got the 3:1 surrounding text and 4.5 to background in dark theme!

One more change needed:
Get a 3:1 for surrounding text for light theme! I tried `--link-button-color: #{lighten($blue, 5%)};` in the `variable.scss` and it seems to work. 

Another thing that isn't needed... but.. people who use the dark theme may find that the new `--text-color` is too bright. It seems especially noticeable to me on the toolbar. Below shows top being original and bottom being the new color. 
![Top is original, bottom is new](https://github.com/desktop/desktop/assets/75402236/f6f3bc3c-af02-41b8-a72a-386810dabf56)

The toolbar already have their own: 
```
--toolbar-text-color: var(--text-color);
--toolbar-text-secondary-color: var(--text-secondary-color);

 --toolbar-button-color: var(--toolbar-text-color);
```
I am thinking we could set the `--toolbar-text-color` to that original `$gray-300` and the `--toolbar-text-secondary-color` to the original `$gray-200` so that at least the toolbar that is ever present and shouldn't contain links can maintain the less eye straining color. 

Feel free to ignore below.. just capturing thoughts..

_Other thoughts I had was to make a new variable called `--body-text-color` and use that where ever links may be.. but I think differentiating between `--body-text-color` and `--text-color` seems nuanced... plus having a body text brighter than a heading text in a passage like area (think "No local changes") might get weird looking. Which on that note.. the "No local changes" view is also now much brighter. I think more in depth tweaks to the dark theme to make it happier for dark theme lovers could be a follow up PR_

2023-07-28 16:32 UTC, jacortinas commented
@tidy-dev You're right that it felt too bright overall. I've gone ahead and updated the PR to use a brighter `--text-color` without changing the secondary text color. I think this makes the top header feel less bright. Alongside a slight change to the link color, I think this ends up being a good compromise given the constraints.

Top: Original, Bottom: New
<img width="962" alt="Screenshot 2023-07-28 at 11 30 42 AM" src="https://github.com/desktop/desktop/assets/171215/527efbd5-c9a9-4408-a54d-85bc06049d39">

2023-07-31 14:36 UTC, tidy-dev requested changes
:) I think this was buried in my last review.

One more change needed:
- Get a 3:1 for surrounding text for light theme! I tried --link-button-color: #{lighten($blue, 5%)}; in the variable.scss and it seems to work.

2023-07-31 15:05 UTC, jacortinas commented
@tidy-dev Updated the PR improve link contrast on the light theme. Your suggestion was great, thank you! :+1: 🙇

2023-07-31 16:14 UTC, tidy-dev approved these changes
✨  🎨  Thanks for all the updates!

2023-07-31 21:17 UTC, merged

2023-08-01 21:21 UTC, Moescha reviewed
Lea Laurenciana