Bump Electron to version 24.8.3
desktop/desktop pull request #17416
Opened 2023-09-21 07:38 UTC by sergiou87

# Description

As the title says, this PR upgrades Electron to version 24.8.3. I've done some regression testing around the different features, different integrations with the system, and accessibility. On both Windows and macOS. I couldn't find any regressions.

This Electron version uses node 18.14.0 which is what we already use, so no need to upgrade that

## Release notes

Notes: [Improved] Upgrade to Electron v24.8.3

2023-09-21 08:50 UTC, niik requested changes

2023-09-21 08:50 UTC, niik commented on script/validate-electron-version.ts
>    production: '24.4.0',
Shouldn't we bump this as well? We're intending to ship this to prod right?

2023-09-21 08:51 UTC, sergiou87 commented on script/validate-electron-version.ts
>    production: '24.4.0',
Yes, but I was expecting us to ship it to beta first, make sure everything is ok, then change that too and ship to prod 😳

2023-09-21 09:39 UTC, niik commented on script/validate-electron-version.ts
>    production: '24.4.0',
Yes, that's what I was expecting as well :smile: I just figured the risk would be high that we forgot to update this and the deployment would then fail but I don't care strongly about it.

2023-09-21 09:39 UTC, niik approved these changes

2023-09-21 10:54 UTC, tidy-dev approved these changes
I pulled it down and bumped around on macOS. Haven't run into anything.

I will test Windows on beta.

2023-09-21 11:54 UTC, merged

2023-10-04 06:16 UTC, Tangshan01 commented
#17481

2023-10-04 16:49 UTC, SnowballXueQiu commented
> #17481 

i wonder why you referenced my pr ❓

2023-10-06 03:08 UTC, SnowballXueQiu reviewed
👍

2023-10-15 01:17 UTC, Samari4052 commented
https://github.com/desktop/desktop/actions/runs/6258643647/job/16993045491#step:1:1

2023-10-15 08:27 UTC, rafa852 commented on app/.npmrc
> +target = 24.8.3
{®©{®®©(●'◡'●)╰(*°▽°*)╯¯\_(ツ)_/¯