Fix staged file renamed with changes showing no diff
desktop/desktop pull request #17467
Opened 2023-09-30 02:40 UTC by ssigwart

- Closes desktop/desktop#6014

## Description
Fixes the case where a staged file is moved and modified. Previously, it would say it was moved with no changes.

### Screenshots

<img width="970" alt="image" src="https://github.com/desktop/desktop/assets/1426848/ca0bc3f4-812c-4d5e-8815-40a007ed232d">

2024-11-26 17:32 UTC, tidy-dev commented on app/src/lib/git/status.ts
> +      renameIncludesModifications,
```suggestion
    return {
      kind: AppFileStatusKind.Renamed,
      oldPath,
      submoduleStatus: entry.submoduleStatus,
      renameIncludesModifications: entry.workingTree === GitStatusEntry.Modified ||
      (entry.renameOrCopyScore !== undefined && entry.renameOrCopyScore < 100),
```

We[ prefer Immutability when possible.](https://github.com/desktop/desktop/blob/development/docs/contributing/engineering-values.md#immutability-is-good)

2024-11-26 17:34 UTC, tidy-dev commented on app/src/lib/git/log.ts
> +    return { kind: AppFileStatusKind.Copied, oldPath, submoduleStatus, renameIncludesModifications }
Nit: I think this would be cleaner if we did the assigning on the object 

{
 ... 
 renameIncludesModifications: false
 }

2024-11-26 17:35 UTC, tidy-dev commented on app/src/ui/diff/index.tsx
> +        }
```suggestion
          return (
            <div className="panel renamed">
              The file was renamed but not changed
            </div>
          )
```

Unnecessary else statement

2024-11-26 17:40 UTC, tidy-dev requested changes
@ssigwart  Thanks for this contribution. I apologize for the long delay in review (small team, pr's are as we can get to them). I understand if you do not want to pick this back up after so much time. But if you do, here is some feedback:

I believe it is fairly non-invasive approach to having better messaging and appears to work as expected.  I have left some code-base stylistic comments. Also, I can tell that if the CI had triggered, the linter would have failed. Thus, to get this PR another review, we will need to bring it up to date with development and run yarn:lint:fix 

As said above, totally understand if you do not want to pick this back up. If that is the case we will close it in a couple of weeks.

2024-11-27 03:26 UTC, ssigwart commented
Thanks, @ tidy-dev. I rebased and applied the updates you suggested. The GitHub actions don't run without approval for me, but I ran `yarn lint` and `yarn lint:fix` locally.

2024-11-27 14:40 UTC, tidy-dev commented
@ssigwart We have some failing unit test since the status module has changed. Can you address those?

To run unit tests, use `yarn test:unit`.
To only run unit tests for only one of those files, you can run something like `yarn test:unit log` to do the log-test file and `yarn test:unit status` for the status-test file.

![Showing four failed unit tests](https://github.com/user-attachments/assets/2c381c84-6dea-4342-af5d-7f3fc04c97dc)

2024-11-28 03:07 UTC, ssigwart commented
@tidy-dev, I fixed them. Thanks for the pointers on how to run the tests that failed.

2024-12-05 01:25 UTC, ssigwart commented
@tidy-dev, I noticed that the unit tests ran today and there were some lint errors, so I ran `yarn lint:fix` and pushed a new commit.

2024-12-05 16:05 UTC, tidy-dev approved these changes
Works as expected. Thank you!

2024-12-05 16:05 UTC, merged

2024-12-07 02:58 UTC, ssigwart commented
Thanks for reviewing and merging, @tidy-dev!