Allow StatsStore consumers to increment metrics directly
desktop/desktop pull request #17500
Opened 2023-10-05 13:44 UTC by niik

## Description

I found this branch laying on my machine today and took some time to clean it up while I waited for enterprise2 builds. This adds a new method called `increment` to the stats store class which lets consumers increment a numeric metric just using the name of said metric. This means we can get rid off many of our proxy methods and do away with some pretty boring boilerplate in StatsStore and Dispatcher.

I found that the `cherryPickSuccessfulWithConflictsCount` does not appear to be incremented anywhere which seemed odd but I don't believe that's my doing so I've just removed the proxy method but we should probably consider removing the metric altogether (or fixing it).

I also took the opportunity here to rewrap comments in StatStore to make it just a little bit less awful to scroll through.

### Screenshots

## Release notes

Notes: no-notes

2023-10-05 14:07 UTC, tidy-dev commented
> cherryPickSuccessfulWithConflictsCount 

My guess is this was accidentally removed during cherry pick change to multi commit operation.  I only added it because I was following the stats pattern of Rebase and figured that if we wanted data around operations that could conflict like tracked in the Merge Workflow data tiles.. We would want it for a cherry-picking as well.  If we do not care about tracking when a user successfully completes an operation with conflicts, then removing it is fine. Otherwise, I can figure out where it should be.

2023-10-06 15:54 UTC, sergiou87 requested changes
I love this cleanup!!!

I only found a few places where a function called was replaced with an increment to the wrong property.

2023-10-06 15:54 UTC, sergiou87 commented on app/src/ui/dispatcher/dispatcher.ts
> +      this.statsStore.increment('cherryPickSuccessfulCount')
I think this is the one you were looking for, @niik !
```suggestion
      this.statsStore.increment('cherryPickSuccessfulWithConflictsCount')
```

2023-10-06 15:54 UTC, sergiou87 commented on app/src/ui/check-runs/ci-check-run-popover.tsx
> +    this.props.dispatcher.incrementMetric('opensCheckRunsPopover')
```suggestion
    this.props.dispatcher.incrementMetric('viewsCheckOnline')
```

2023-10-06 15:54 UTC, sergiou87 commented on app/src/ui/dispatcher/dispatcher.ts
> +    this.incrementMetric = statsStore.increment.bind(statsStore)
❤️

2023-10-06 15:54 UTC, sergiou87 commented on app/src/ui/banners/rebase-conflicts-banner.tsx
> +    this.props.dispatcher.incrementMetric('rebaseConflictsDialogDismissalCount')
```suggestion
    this.props.dispatcher.incrementMetric('rebaseConflictsDialogReopenedCount')
```

2023-10-11 14:18 UTC, niik commented
> I only found a few places where a function called was replaced with an increment to the wrong property.

Thank you thank you thank you. I thought about writing some godawful tool to do this but I figured I could do it copy-pasta style without regressing. I was wrong!

2023-10-18 10:16 UTC, sergiou87 approved these changes
Sorry, I missed your new changes 😳  It looks all good now! :shipit:

2023-10-19 12:06 UTC, merged