Diff check all logic iteration.
desktop/desktop pull request #18232
Opened 2024-02-28 17:25 UTC by tidy-dev

## Description

This PR:
1. Fixes the issue where if you scroll the first row out of the virtual scroll rendering, the check all control disappears.
2. Fixes the issue where one line is modified doesn't have a check all, but has a deleted and removed line check.
3. Uses the grids rendered row index to make the calculation of the height more performant by no longer looping through all the rows, but only a loop of the rendered rows and only the rows of the group. 
4. Makes the logic more performant by implementing a cache for the data that is obtained by looping through all the rows, but does not change on row re render.

Both 3-4 together have made it so that scrolling a file with lots of line (I tested on > 1000) no longer leads to noticeable increase in load time. 

### Screenshots

## Release notes
Notes: no-notes

2024-03-06 15:42 UTC, sergiou87 requested changes
Code looks good to me, only found a typo in a comment. It works great, I only found this small nit where hovering over the check all octicon doesn't use the pointer cursor:

https://github.com/desktop/desktop/assets/1083228/c47f6078-3ebf-4bd1-aff2-806d707f6552

One nice idea to discuss for a future PR (because I don't even know how to implement it 😓 ) would be to make the "check all" octicon sticky to the scroll, so it's always visible no matter how many lines are there in a hunk. I think that'd be nice to know whether the hunk is selected completely or only partially.

2024-03-06 15:42 UTC, sergiou87 commented on app/src/ui/diff/diff-helpers.tsx
> + * something line 'hunkStartLine` on it.
Nit:
```suggestion
 * something like 'hunkStartLine` on it.
```

2024-03-06 16:11 UTC, tidy-dev commented
> One nice idea to discuss for a future PR (because I don't even know how to implement it 😓 ) would be to make the "check all" octicon sticky to the scroll, so it's always visible no matter how many lines are there in a hunk. I think that'd be nice to know whether the hunk is selected completely or only partially. 

A version of this might not actually be difficult because I can just have the check all icons rendered on the "visible" check all thing. I would have to try it tho.. it may be too flickery looking.

2024-03-07 12:37 UTC, tidy-dev commented
Fixed cursor pointer 
![](https://github.com/desktop/desktop/assets/75402236/9f6c97df-1307-416c-ad2b-689dbab87e9f)

2024-03-07 12:41 UTC, tidy-dev commented
>  it may be too flickery looking

The idea I had definitely not good as renderer to slow and not quite always visible. Tho, I like the idea, I am going to table it for now as css sticky sorcery can be tedious and I am not 100% I can make it work.

![](https://github.com/desktop/desktop/assets/75402236/db47cb3d-b69b-473e-a3e9-48b4baad608a)

2024-03-07 14:51 UTC, sergiou87 approved these changes

2024-03-07 14:51 UTC, merged