Add link role to the "Open pull request" button in tutorial sidebar
desktop/desktop pull request #18245
Opened 2024-03-01 18:15 UTC by jacortinas

Issue: https://github.com/github/accessibility-audits/issues/6865

## Description
This PR adds a `role="link"` attribute to a button within the tutorial panel. The button technically functions as a link that sends the user to a specific URL so a link role is the more correct role for the button.

This PR adds a role rather than converting the button to an anchor element because the href is not immediately available when rendering the component. Functionally, the button marks the tutorial as complete, then directs the user to the new pull request page in the browser, this means that the final URL is computed after clicking and not immediately available in the component code for the `href` attribute of a link.

### Screenshots
<img width="1185" alt="Screenshot of open pull request button and voiceover output" src="https://github.com/desktop/desktop/assets/171215/107edc32-df52-4967-aa94-e1f901d937ce">

## Release notes

Notes:

2024-03-02 09:14 UTC, onu11 reviewed
<!-- Error while uploading 600x0w.webp -->![Screenshot_2024-03-02-10-49-41-613_com.android.chrome.jpg](https://github.com/desktop/desktop/assets/152846116/edb6d27c-dc65-4f71-90aa-4073cb9ff73d)

- [ ] ```
![Screenshot_2024-02-29-16-33-17-012_com.github.android.jpg](https://github.com/desktop/desktop/assets/152846116/b90d372f-5120-4fc8-9800-038fdb641596)

![Screenshot_2024-03-01-10-09-16-529_com.github.android.jpg](https://github.com/desktop/desktop/assets/152846116/745f1538-7166-44cc-aa15-90aeac90d249)


```

2024-03-02 09:14 UTC, onu11 commented on app/src/ui/tutorial/tutorial-panel.tsx
> +              <Button onClick={this.openPullRequest} role="link">
![309462771-b90d372f-5120-4fc8-9800-038fdb641596.jpg](https://github.com/desktop/desktop/assets/152846116/2dae0c44-8ad2-4ad4-aba3-da1790985499)

2024-03-02 09:14 UTC, onu11 commented on app/src/ui/tutorial/tutorial-panel.tsx
> +              <Button onClick={this.openPullRequest} role="link">
![ascii-text-art.png](https://github.com/desktop/desktop/assets/152846116/82628747-4c6f-49e7-b6f6-5248684e1e15)

![86add3984cc5a78357d398d35ac1e553.jpg](https://github.com/desktop/desktop/assets/152846116/7e64eb3e-436d-4f3d-a4ef-19a507b8a2bc)

2024-03-04 13:12 UTC, tidy-dev requested changes
This appears to work to communicate to screen readers users that the button behaves as a link in terms of opening out to a webpage.

Can you do a code search for the `octicons.linkExternal` and add this role to those buttons as well so that we are consistent through the app?

2024-03-05 11:50 UTC, tidy-dev approved these changes
Looks good!

2024-03-05 16:27 UTC, merged