Create Function to Unify isOSNoLongerSupportedByElectron
desktop/desktop pull request #18333
Opened 2024-03-20 16:50 UTC by say25

Closes #[issue number]

## Description

- I noticed #18320 and thought we could make the code a little easier to maintain by unifying the checks vs doing an OR check always

### Screenshots

## Release notes

Notes:

2024-03-20 18:44 UTC, tidy-dev requested changes

2024-03-20 18:44 UTC, tidy-dev commented on app/src/lib/get-os.ts
> +  }
```suggestion
return isMacOSAndNoLongerSupportedByElectron() || isWindowsAndNoLongerSupportedByElectron()
```

The above methods already check for OS so I think that is redundant and this method could simplified. (Drive-by review from my phone so warning formatting of the above suggestion is probably not ideal)

2024-03-22 14:09 UTC, sergiou87 requested changes

2024-03-22 14:09 UTC, sergiou87 commented on app/src/lib/get-os.ts
> +  isWindowsAndNoLongerSupportedByElectron()
I think this should be a function (memoized or not):
```suggestion
export const isOSNoLongerSupportedByElectron = memoizeOne(
  () =>
    isMacOSAndNoLongerSupportedByElectron() ||
    isWindowsAndNoLongerSupportedByElectron()
)
```

2024-03-27 12:27 UTC, sergiou87 approved these changes
Tested and works as expected!

2024-03-27 12:49 UTC, tidy-dev approved these changes

2024-04-02 16:51 UTC, merged