Remove remaining `<br />`
desktop/desktop pull request #18444
Opened 2024-04-10 15:01 UTC by sergiou87

## Description

This PR is a continuation of #18436 , going through every remaining instances of `<br />` found in our codebase and replacing them with the appropriate HTML elements.

There have been changes in these components:
- Large text diffs info text
- Force-push warning in the pull/push/fetch dropdown
- Warning in the "enable notifications" setting hint
- Content of the warning dialog of local changes before undoing
- Disclaimer footnotes in the welcome start screen
- Contents of the "add SSH host" dialog
- Contents of the dialog to confirm removing a repository
- Zero case of branch selector in the Preview Pull Request dialog
- Path error message in the "add existing repo" dialog
- Label of the repository URL textbox in the clone dialog (URL tab)

Only these instances have been left:
- All the ones from the Test Notifications dialog (since that's only for dev usage)
- [`<br />` elements added to blank lines in diffs](https://github.com/desktop/desktop/blob/c6edb587abb49a01ae947bde177a538a23994005/app/src/ui/diff/side-by-side-diff-row.tsx/#L454-L455), so that copy&pasting those work as expected

### Screenshots

Everything should still look the same!

## Release notes

Notes: [Fixed] Remove unnecessary br elements and make the app easier to navigate with screen readers

2024-04-15 18:30 UTC, tidy-dev commented on app/src/ui/diff/index.tsx
> +        <p>The diff is too large to be displayed by default.</p>
Before
![CleanShot 2024-04-15 at 14 26 42](https://github.com/desktop/desktop/assets/75402236/39248e12-2a42-4b5f-ba0c-00241fb25ad0)


After
![Large text diffs with extra space.](https://github.com/desktop/desktop/assets/75402236/840c4096-74aa-48a4-af86-b1fd5ffb7dbf)

From accessibility audit documentation, I have branch https://github.com/githuba11y/repo_the_second2/tree/with-github-desktop-readme.md) for reproducing this screen handy.

2024-04-15 18:39 UTC, tidy-dev commented on app/src/ui/remove-repository/confirm-remove-repository.tsx
> +          </div>
Before:
![CleanShot 2024-04-15 at 14 39 24](https://github.com/desktop/desktop/assets/75402236/bbf6f3a6-dd32-4efa-8a1c-a53c4f58ea95)


After:
![CleanShot 2024-04-15 at 14 38 14](https://github.com/desktop/desktop/assets/75402236/7222933b-ea48-4aeb-80c3-b334d22e6ace)

2024-04-15 18:52 UTC, tidy-dev requested changes
You can see in the comments I noticed a couple places where these changes introduced additional whitespace. Other than that, everything looks good. Thank you for going through all these places

2024-04-16 15:05 UTC, sergiou87 commented
Thanks for your feedback! Hopefully all fixed now:

<img width="470" alt="image" src="https://github.com/desktop/desktop/assets/1083228/dd1adea0-9765-45d7-9096-cbfb99bd90c3">

<img width="459" alt="image" src="https://github.com/desktop/desktop/assets/1083228/d3d86404-dd52-431a-bc22-383ebf8a928a">

2024-04-16 15:15 UTC, tidy-dev approved these changes
✨ Looks good! Thanks for those changes.

2024-04-17 10:34 UTC, merged