fix the check run filter by id
desktop/desktop pull request #18650
Opened 2024-05-20 13:32 UTC by saurabh-git-dev

Closes #18648

## Description

Fixes the issue of the same job name. Instead of filtering with check-run "name". we now have the option to use check-run "id".
If we change the name with id. We can see all the jobs with the same name.

### Screenshots
![image](https://github.com/desktop/desktop/assets/68720731/56e2f607-6aa0-4fb4-89f7-1c201628e464)

2024-05-20 19:22 UTC, Chukwumaelesachi reviewed
Approve

2024-05-22 10:40 UTC, niik commented
Hey @saurabh-git-dev, thanks so much for taking the time to contribute to Desktop!

I _believe_ this change makes sense but I'd really like for @tidy-dev (the original author of this) to take a look as well. My concern is centered around the fact that we named this function getLatestCheckRunsBy**Name** so I want to make sure that id is a suitable replacement. If it is then we should update the name of the function as well.

2024-05-23 13:59 UTC, tidy-dev commented
I did some digging to see if I could find reasoning for using the name versus the id. (I couldn't remember this method)

@niik you are the original author of the function for the pr status work.

https://github.com/desktop/desktop/blame/36e957897eae6d4a491ddd6dd41fb119f0f1a12e/app/src/lib/stores/commit-status-store.ts

I only added filter based on if it was a push or a pull.

https://github.com/desktop/desktop/commit/1eed3bc720ddc045eb64eaf5542c37b370d80d7a#diff-e3f9f5058c055c6e578c6019115cad54a10a80455eeeb4c4afca17df1b86150cL352

[Looking at the docs](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28), I cannot see a reason not to use id here instead of name.

2024-05-23 13:59 UTC, tidy-dev requested changes
@saurabh-git-dev Could you please update the function name to getLatestCheckRunsById?

2024-05-23 15:30 UTC, saurabh-git-dev commented
I actually had the same thought as to why the "id" was not used.
If we take a look in detail there are one more issue due to the "name". It's not the single place where "name" is used. the workflows are also grouped by names instead of by "id". That is why if there are 2 workflows with the same name, they will appear in a single group.

In the shared picture there are 2 jobs with the same name. And also the same workflow name. That's why appear in a 'Test' group.

I looked at the grouping method. But it is used in many places. So did not change that. 
Group Method - https://github.com/desktop/desktop/blob/b80f540b63e7806a764b57e4cf02d41d1084f300/app/src/lib/ci-checks/ci-checks.ts#L598

Although there is not a big impact with the grouping issue.

2024-05-23 17:35 UTC, tidy-dev approved these changes
💖  Thanks for the fix. 

I tested across GitHub Action and Non-GitHub Action checks and works as expected. 

Sounds like it would be more accurate to use id for unique workflow names as well.

2024-05-23 17:43 UTC, merged