Prompt to sign in to GitHub hosts in credential helper
desktop/desktop pull request #18773
Opened 2024-06-05 20:57 UTC by niik

## Description

Follow-up to #18700. This PR adds support for prompting users to sign in to GitHub hosts in the credential helper. In order to accomplish this we need a way to abstract the entire sign-in state machine in one operation (i.e. a promise).

This moves the OAuth dance into the sign-in store and creates a promise that encompasses the entire sign-in flow.

Further more this works around the issue in #187000 where we would show the user an error saying 'fatal: could not read Username for '': terminal prompts disabled' when we couldn't find credentials. We now detect that case and throw the good old fashioned "Authentication failed" error instead.

### Screenshots

## Release notes

Notes:

2024-06-07 06:07 UTC, niik commented
@sergiou87 @tidy-dev I feel like this should be a required piece of #18700 so I'd love it if we could review it here and merge it into #18700 and then land the entire piece on development

2024-06-07 15:30 UTC, sergiou87 requested changes
Looks good overall, only found a few things

2024-06-07 15:30 UTC, sergiou87 commented on app/src/lib/api.ts
> +    return true
Shouldn't this be false? What am I missing?

2024-06-07 15:30 UTC, sergiou87 commented on app/src/lib/git/credential.ts
> +      cred.set(newKey, v)
Am I missing something here? `newKey` never changes 🤔 

Could you add to the comment a sample input for `parseCredential` and then the expected output for `formatCredential` for that same info?

2024-06-07 15:30 UTC, sergiou87 commented on app/src/lib/trampoline/trampoline-credential-helper.ts
I guess we can get the accounts after the `if (ghCred)`?

2024-06-07 15:32 UTC, niik commented on app/src/lib/api.ts
> +    return true
You're not missing anything, last minute addition by a sleep deprived mind. I'll fix this!

2024-06-07 15:36 UTC, niik commented on app/src/lib/git/credential.ts
> +      cred.set(newKey, v)
yeah 🤦 I should stop doing last minute cleanups

2024-06-07 15:41 UTC, niik commented on app/src/lib/git/credential.ts
> +      cred.set(newKey, v)
I added two tests that hopefully should explain this clearly

2024-06-10 09:00 UTC, sergiou87 commented on app/src/lib/git/credential.ts
> +      cred.set(newKey, v)
Those tests are perfect, thank you!

2024-06-10 09:21 UTC, sergiou87 approved these changes
Thank you for those changes! I've been testing this and it works great 😍

2024-06-10 09:22 UTC, merged

2024-06-10 09:23 UTC, niik commented
Thank you @sergiou87!