Fix incorrect commit range check when checking if there's anything to rebase
desktop/desktop pull request #19031
Opened 2024-07-29 20:35 UTC by Leroy231

Closes #17892

## Description

The logic for when you can rebase was incorrect, only based on what new commits are on the current branch disregarding new commits on the other branch. So if you had a branch you created off of main branch, then on main branch you created a new commit, on the other branch if you tried to rebase main it wouldn't let you even though it should.

-

### Screenshots

Before in the scenario mentioned above you can't rebase:
![before](https://github.com/user-attachments/assets/97aa1b42-212d-45a6-81f7-3a0eec971430)

Now you can rebase:
![after-branch-with-no-commits](https://github.com/user-attachments/assets/910637f7-663c-4c51-bd93-85601df1320e)

If the branch has a commit it still mentions it:
![after-branch-with-1-commit](https://github.com/user-attachments/assets/713d52b8-4132-446f-91f5-8d227a9ad30f)

If the branch has been rebased and you try again it still tells you it's up to date:
![after-up-to-date-branch](https://github.com/user-attachments/assets/0a600351-e746-494e-8abc-40a4a1fa5648)

## Release notes

Notes:

2024-07-31 11:23 UTC, sergiou87 reviewed
Shouldn't these changes take into account commits from **both** branches? 🤔  What am I missing?

2024-07-31 11:23 UTC, sergiou87 commented on app/src/ui/lib/update-branch.ts
> +  if (commitsFromOtherBranch === null) {
Shouldn't this check for both kinds of commits?
```suggestion
  if (commits === null && commitsFromOtherBranch === null) {
```

2024-08-06 16:23 UTC, sergiou87 requested changes
I think it makes sense! But I also think this requires changes in `app/src/ui/history/merge-call-to-action-with-conflicts.tsx` similar to the ones in `app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx`

2024-08-06 16:23 UTC, sergiou87 commented on app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx
> +    const areCommitsToBringFromOtherBranch =
I think this would be a better name:
```suggestion
    const areCommitsToRebaseOnto =
```

2024-08-06 16:23 UTC, sergiou87 commented on app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx
> +    commitsToRebase: number,
I think we should include an `if (commits <= 0)` to render a specific message when there are no new commits to rebase in the current branch, and the branch ref itself will be just moved / fast forwarded to the other branch.

Maybe something like this?
```typescript
if (commits <= 0) {
  return (
    <>
      This branch will be fast-forwarded to{` `}
      <strong>{currentBranch.name}</strong>
    </>
  )
}
```

2024-12-25 18:34 UTC, sfadschm commented
@Leroy231 are you available to tackle the requested changes? If not I am keen to take over, as it really bugs me out that it is not possible to merge feature branches properly.

2024-12-26 15:17 UTC, Leroy231 commented
@sfadschm sorry for the delay here, I haven't had time to get back to this and I won't for the foreseeable future. If you can take it over please do so and thanks!

2024-12-27 10:49 UTC, sfadschm commented
No worries, thanks for starting the topic :-)

2024-12-30 20:28 UTC, tidy-dev commented
@sfadschm Can I take this to mean, you intend to pick this up and incorporate @sergiou87 feedback?

2024-12-30 20:45 UTC, sfadschm commented
@tidy-dev 
Yes, will take some days, though. Just got the environment running and now setting up a dummy repository for testing. I will open a new draft PR to supersede and address related issues once setup is finished and then work from there.

2024-12-31 14:53 UTC, tidy-dev commented
@sfadschm Great. Then I will go ahead and close this one out. :)

2024-12-31 14:53 UTC, closed without merging