Push default branch first if not checkout on publish
desktop/desktop pull request #19151
Opened 2024-08-22 17:24 UTC by tidy-dev

Related to https://github.com/desktop/desktop/issues/19121

## Description
In the associated issue, the way git naturally works of setting the first pushed branch  to a repositories default branch (as it is the only branch available) got a user is a predicament not knowing how to switch it back. 

Generally when someone adds a new repository locally, they immediately push to a remote. This naturally sets the first branch created that is the default as the default on the remote.  However, if a user creates a local repository and then creates a new branch and works on it and then decides to publish the repository without switching back to their default. They will mistakenly switch their default branch. (To fix it, they can go to their remote and update their default branch there and then fetch in Desktop.. but that is not likely for a user to know)

This PR checks for that scenario and goes ahead and pushes the default branch first instead.

Other thoughts:
- What if someone was intending to use this default behavior in Git to set a different branch as their default? What I could have done instead was not automatically push the default.. but popup a dialog that informs the user that they are not on the default branch and what will happen (allowing them to continue anyway or cancel (with instruction to switch to their default then push?)). But... I believe (don't have data aside from the opened issue) this to be more of an edge case than someone accidentally publishing on the wrong ranch and switching their default branch. Also if this is the users intention, they can intentionally go and switch their default branch on the remote after creation. 

### Screenshots

https://github.com/user-attachments/assets/4c635edc-9017-48a2-8c6b-25f70bfbc03e

## Release notes
Notes: [Improved] When publishing a new repository, publish the default branch as opposed to the currently checked out branch.

2024-08-23 10:47 UTC, sergiou87 requested changes
Just two lines that I think should be deleted. Other than that LGTM!

2024-08-23 10:47 UTC, sergiou87 commented on app/src/lib/stores/app-store.ts
> +    ) {
I think these two lines should be removed to preserve the previous behavior (and they're already in the nested `if` anyway, which I guess is where they belong)

```suggestion
    if (gitStore.tip.kind === TipState.Valid) {
```

2024-08-23 17:13 UTC, steveward commented
Great fix! This will close out https://github.com/desktop/desktop/issues/10293 as well. ✨

2024-08-23 17:15 UTC, steveward commented
>But... I believe (don't have data aside from the opened issue) this to be more of an edge case than someone accidentally publishing on the wrong branch and unintentionally switching their default branch. Also if this is the users intention, they can intentionally go and switch their default branch on the remote after repository publishing.

This sounds right to me. 👍🏻

2024-09-04 18:11 UTC, tidy-dev commented
Did another bit of testing after accepting the suggestions, it worked as expected for:
1. publishing from the default
2. not publishing from the default.

I believe I tested both those before... but the suggestions appeared correct and it has been a minute since I did this PR. 🤷

2024-09-05 16:19 UTC, sergiou87 approved these changes
✨

2024-09-05 16:19 UTC, merged