Prioritized updates
desktop/desktop pull request #19655
Opened 2024-12-03 15:33 UTC by niik

xref https://github.com/github/desktop/issues/894 

## Description

From time to time we ship new releases containing fixes for high severity security vulnerabilities. Most frequently this has been a vulnerability in a third-party dependency (Git, Git LFS etc) but it could also be a vulnerability within Desktop itself. Over Desktop's [lifetime](https://github.blog/news-insights/announcing-github-for-mac/) we've had a few releases where we've wanted to get the word out to users that they should update as soon as possible to stay safe.

With this change we'll be able to communicate to Desktop clients that they should prioritize updating to the latest version ASAP. When we do so we'll make remove the ability to dismiss the update banner, as well as change the styling and text to convey the urgency of updating.

### Screenshots

![A screenshot of GitHub Desktop using the dark theme showing a banner with the text This version of GitHub Desktop is missing important updates. Please restart GitHub Desktop now to install pending updates](https://github.com/user-attachments/assets/da68dded-8699-4158-90bf-084a01efe236)

![A screenshot of GitHub Desktop using the light theme showing a banner with the text This version of GitHub Desktop is missing important updates. Please restart GitHub Desktop now to install pending updates](https://github.com/user-attachments/assets/0c07adca-5fdd-4d6a-8151-41b69c8de2ef)

## Release notes

Notes:

2024-12-04 12:57 UTC, tidy-dev requested changes
Looking good! 

I have left a comment as we have one accessibility contrast issue to resolve, but other than that looks great.

2024-12-04 12:57 UTC, tidy-dev commented on app/styles/themes/_dark.scss
> +  --banner-warning-link-color: #4285fb;
Good contrast for dark mode. :)

2024-12-04 12:57 UTC, tidy-dev commented on app/styles/_variables.scss
> +  --banner-warning-link-color: #{$blue-700};
For accessibility, we need:
link -> text = 3:1 
link/text -> background: 4.5:1 

Unfortunately, this is giving link:text of 1.5:1 for light mode. 

Here is a link checker tool that has inputs for the link, the text, and the background to make verification easier.
https://webaim.org/resources/linkcontrastchecker/

Feel free to fix as you see fit. When I was testing locally, I tried the hidden bidi characters styles (which have been modified recently for accessibility.)  These colors were inspired by https://primer.style/components/banner. ... which one could argue that maybe we could use there "Critical" banner styles which would be a redish color kind of like dark mode. https://primer.style/foundations/primitives/color has a `--bgColor-danger-muted` (for background) and `--bgColor-danger-emphasis` (for icon)

```
  /** Banner */
  --banner-warning-background: #{$yellow-100}; // copied from --file-warning-background-color
  --banner-warning-text-color: var(--text-color);
  --banner-warning-link-color: var(--link-button-color);
  
  /_update-available.css 
    &.priority {
      .octicon {
          color: var(--file-warning-color);
        }
    ...
  ```
![Showing using same styles as from bidi character warning](https://github.com/user-attachments/assets/a602a15c-d9b3-4b5e-8ea5-facdcee06d7e)

2024-12-05 08:01 UTC, niik commented
> I have left a comment as we have one accessibility contrast issue to resolve, but other than that looks great.

Thanks a bunch. I aligned the dark banner with the file warning in the dark theme and (believe) I've covered all the contrast issues

![A screenshot of GitHub Desktop using the dark theme showing a banner with the text This version of GitHub Desktop is missing important updates. Please restart GitHub Desktop now to install pending updates](https://github.com/user-attachments/assets/031b124d-3e0e-4c98-a367-59e3f53bee94)
![A screenshot of GitHub Desktop using the light theme showing a banner with the text This version of GitHub Desktop is missing important updates. Please restart GitHub Desktop now to install pending updates](https://github.com/user-attachments/assets/5ad0d699-9393-42b3-8916-01f46a4d0c97)

2024-12-05 14:07 UTC, tidy-dev requested changes
Super close... :P 

In light and dark theme we are not quite to the 3:1 for link to body text. 
 
![CleanShot 2024-12-05 at 09 00 22](https://github.com/user-attachments/assets/cf67bc2e-5fcc-4e5e-a667-d5c8611e652d)

![CleanShot 2024-12-05 at 09 05 23](https://github.com/user-attachments/assets/bd1163c8-23cf-4023-b715-9d4c20fa22ed)


I found if we used the original link button blue it works on both dark/light themes, so I think we can just not apply any special css to the links in this banner and we will be good. 

![CleanShot 2024-12-05 at 09 02 06](https://github.com/user-attachments/assets/660c8a79-a7e5-4ec2-82c1-3f809c5fc3db)

![CleanShot 2024-12-05 at 09 05 47](https://github.com/user-attachments/assets/573e2ab3-93bd-4ea7-b4ce-b2ce3a5b8f64)

2024-12-05 14:09 UTC, tidy-dev commented
Lol.. after I posted I didn't catch that the link to background failing in light theme.

![image](https://github.com/user-attachments/assets/119143d2-a997-4dbf-bf70-915dbc19ec9f)

So, we need to figure that out... I wonder if bidi character is failing that.

2024-12-05 14:20 UTC, niik commented
Alright, I somehow missed the contrast between the text and the link and only cared about link to background. Here's [new results for the light theme](https://webaim.org/resources/linkcontrastchecker/?fcolor=24292E&bcolor=FFFBDD&lcolor=046EE7) and [dark theme](https://webaim.org/resources/linkcontrastchecker/?fcolor=F6F8FA&bcolor=272216&lcolor=6682FF)

![image](https://github.com/user-attachments/assets/103635e6-534d-4d61-aca2-b20ce1a076f6)

![image](https://github.com/user-attachments/assets/5cf41820-da7e-4944-afea-eb43201038d3)

2024-12-05 14:25 UTC, tidy-dev approved these changes
💖  Thank you for those fixes!

2024-12-05 14:34 UTC, merged

2024-12-11 01:04 UTC, 72158895omar1 commented
> xref https://github.com/github/desktop/issues/894
> 
> ## Description
> From time to time we ship new releases containing fixes for high severity security vulnerabilities. Most frequently this has been a vulnerability in a third-party dependency (Git, Git LFS etc) but it could also be a vulnerability within Desktop itself. Over Desktop's [lifetime](https://github.blog/news-insights/announcing-github-for-mac/) we've had a few releases where we've wanted to get the word out to users that they should update as soon as possible to stay safe.
> 
> With this change we'll be able to communicate to Desktop clients that they should prioritize updating to the latest version ASAP. When we do so we'll make remove the ability to dismiss the update banner, as well as change the styling and text to convey the urgency of updating.
> 
> ### Screenshots
> ![A screenshot of GitHub Desktop using the dark theme showing a banner with the text This version of GitHub Desktop is missing important updates. Please restart GitHub Desktop now to install pending updates](https://private-user-images.githubusercontent.com/634063/392030050-da68dded-8699-4158-90bf-084a01efe236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NzkyOTYsIm5iZiI6MTczMzg3ODk5NiwicGF0aCI6Ii82MzQwNjMvMzkyMDMwMDUwLWRhNjhkZGVkLTg2OTktNDE1OC05MGJmLTA4NGEwMWVmZTIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMTAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjY3ZTdiMDFiM2QzZjBmY2Q3Y2ZmZWU0ZjQ0NTg0N2EzNWI5ZTVlMmM1NDJmYzk5MjRiZWRkMDdlMGJkMzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JvHv1Rltaytmynjtf2JPB5n33uNxz96fezqPj3tYPxc)
> 
> ![A screenshot of GitHub Desktop using the light theme showing a banner with the text This version of GitHub Desktop is missing important updates. Please restart GitHub Desktop now to install pending updates](https://private-user-images.githubusercontent.com/634063/392030190-0c07adca-5fdd-4d6a-8151-41b69c8de2ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NzkyOTYsIm5iZiI6MTczMzg3ODk5NiwicGF0aCI6Ii82MzQwNjMvMzkyMDMwMTkwLTBjMDdhZGNhLTVmZGQtNGQ2YS04MTUxLTQxYjY5YzhkZTJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMTAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjgyY2FmZmRjMDMzYjJhNWI4OTE3MGVlZDFhM2JkMzVkNGMzOThiMDJiYTRhOWQwMDE2NzM1NWIzYmI0YjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1HYvat0GG8pvpCRFQUtW4od2SWWIQINxBWoVLK2S9Z4)
> 
> ## Release notes Omar a Rodríguez botja
> Notes:

72158895omat1

2024-12-15 01:18 UTC, dav3yblaz3 commented on app/styles/themes/_dark.scss
> +  --banner-warning-link-color: #4285fb;
thank you yes couldnt agree more

2025-01-19 02:08 UTC, F-fengzi commented
That did not take too long to put into use! :D

2025-04-08 04:39 UTC, 137613413 commented on app/styles/themes/_dark.scss
> +  --banner-warning-link-color: #4285fb;
Name (required

2025-04-28 12:22 UTC, skyskygreen93 commented on app/styles/_variables.scss
> +  --banner-warning-link-color: #{$blue-700};
/** Banner */
  --banner-warning-background: #{$yellow-100}; // copied from --file-warning-background-color
  --banner-warning-text-color: var(--text-color);
  --banner-warning-link-color: var(--link-button-color);
  
  /_update-available.css 
    &.priority {
      .octicon {
          color: var(--file-warning-color);
        }
    ...