Change merge hint and merge button order
desktop/desktop pull request #6611
Opened 2019-01-14 17:46 UTC by Raul6469

## Overview
This PR is a fix proposition for #6467 

## Description
This changes the order of merge elements in order to be in sync with what is in the merge modal.

![image](https://user-images.githubusercontent.com/24607388/51130023-4498c100-182c-11e9-891d-09c266af79b5.png)

However, as you can see, I just changed the order by now, but it looks like there is some styling needed, but I'm unsure about what is expected...

2019-01-14 19:04 UTC, shiftkey commented
cc @desktop/design for thoughts about that subtle line wrapping the  ✅ or ❌

2019-01-14 19:37 UTC, ampinsk commented
@shiftkey I think we need to get rid of the rule around the octicon and add a little padding between the message and the button. I can push a commit fixing if that works for you?

2019-01-15 10:00 UTC, Raul6469 commented
Thanks @ampinsk for your help! I did the changes you asked, and here is what it looks like now:
![image](https://user-images.githubusercontent.com/24607388/51172927-a43aaf00-18b4-11e9-8d59-bf7913047305.png)

2019-01-24 14:15 UTC, shiftkey approved these changes
Changes seem fine and address the order issue, but I'd love a quick :eyes: and ✅ from @desktop/design about the visuals with the border now gone. The merge status does seem a bit isolated (if that's the right word?) when surrounded by all this whitespace in the merge dialog footer:

<img width="468" src="https://user-images.githubusercontent.com/359239/51683725-ddfc6b80-1fc0-11e9-9ff5-eb282618378e.png">

2019-01-25 00:15 UTC, ampinsk reviewed
This is looking great! Just a few tweaks 😄

2019-01-25 00:15 UTC, ampinsk commented on app/styles/ui/_merge-status.scss
> +    padding-bottom: 10px;
We can use a spacing variable here:
```suggestion
    padding-bottom: var(--spacing);
```

2019-01-25 00:15 UTC, ampinsk commented on app/styles/ui/_merge-status.scss
>      &:after {
I don't think we need this whole `:after` element now that we aren't using the rule anywhere

2019-01-25 00:17 UTC, ampinsk commented
We can also get rid of this margin here: 

https://github.com/desktop/desktop/blob/0a80e0a8c370593b4c0520b317f8ebcff45660c4/app/styles/ui/_merge-status.scss#L1-L2

Thanks again @Raul6469 👏

2019-01-25 13:38 UTC, shiftkey requested changes
On hold pending styling tweaks

2019-01-25 15:13 UTC, Raul6469 commented
Many thanks @ampinsk @shiftkey for the review! I made changes according to your feedback, let me know if I forgot something 👍

2019-01-25 15:33 UTC, shiftkey approved these changes
LGTM. Updated screenshots:

<img width="344"  src="https://user-images.githubusercontent.com/359239/51755363-ddcda000-2094-11e9-80f2-8a16a4fc2e04.png">
<img width="474"  src="https://user-images.githubusercontent.com/359239/51755364-ddcda000-2094-11e9-8986-a8a9f01d3cde.png">

And dark theme:

<img width="360" src="https://user-images.githubusercontent.com/359239/51755357-dad2af80-2094-11e9-8d89-dea39460b35e.png">

<img width="479" src="https://user-images.githubusercontent.com/359239/51755365-de663680-2094-11e9-80ad-67f44e5b7d72.png">

2019-01-25 18:53 UTC, ampinsk approved these changes
LGTM! Thanks so much @Raul6469!

2019-01-26 17:21 UTC, merged