Rename pull-request-triage.md to pull-requests.md
desktop/desktop pull request #8222
Opened 2019-09-06 15:47 UTC by outofambit

this has been confusing people as we onboard and kind of irks me so here's a quick fix.

2019-09-06 16:00 UTC, mislav submitted a review, later dismissed
Thanks; makes sense! ✨

2019-09-06 16:31 UTC, billygriffin requested changes
Super minor suggestion.

2019-09-06 16:31 UTC, billygriffin commented on .github/CONTRIBUTING.md
> +#### How Do I Submit A Enhancement Suggestion?
```suggestion
#### How Do I Submit An Enhancement Suggestion?
```

2019-09-06 21:33 UTC, billygriffin approved these changes

2019-09-09 14:40 UTC, outofambit commented
merging! :)

2019-09-09 14:40 UTC, merged